# Generated by Django 6.0.4 on 2026-04-29 10:28

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import djmoney.money
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0036_initial_provider_registry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcsPickupList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('pickup_list_no', models.CharField(help_text='PickupList_No returned by ACS_Issue_Pickup_List.', max_length=32, unique=True, verbose_name='Pickup list number')),
                ('issued_at', models.DateTimeField(verbose_name='Issued at')),
                ('billing_code', models.CharField(help_text='Billing_Code captured at issuance time so historical manifests stay reprintable even if the env var changes.', max_length=32, verbose_name='Billing code')),
                ('voucher_count', models.PositiveIntegerField(default=0, verbose_name='Voucher count')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Cached print PDF (base64), unprinted-vouchers list, and raw API response for debugging.', verbose_name='Metadata')),
                ('issued_by', models.ForeignKey(blank=True, help_text='Admin who triggered the manual issue. Null when the daily Celery beat task issued the list.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acs_pickup_lists_issued', to=settings.AUTH_USER_MODEL, verbose_name='Issued by')),
            ],
            options={
                'verbose_name': 'ACS pickup list',
                'verbose_name_plural': 'ACS pickup lists',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='AcsStation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(help_text='ACS_SHOP_STATION_ID — used as Acs_Station_Destination.', max_length=32, unique=True, verbose_name='External ID')),
                ('branch_code', models.CharField(blank=True, default='', help_text='ACS_SHOP_BRANCH_ID — paired with external_id when creating vouchers (Acs_Station_Branch_Destination).', max_length=32, verbose_name='Branch code')),
                ('shop_kind', models.PositiveSmallIntegerField(choices=[(1, 'Shop'), (2, 'Partner shop (2)'), (3, 'Partner shop (3)'), (4, 'Xpress Point'), (5, 'Kiosk'), (7, 'Smartpoint (inbound)'), (8, 'Smartpoint (outbound)')], help_text='ACS_SHOP_KIND — 1 shop, 7/8 Smartpoint locker.', verbose_name='Shop kind')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Name')),
                ('address_line_1', models.CharField(blank=True, default='', max_length=255, verbose_name='Address line 1')),
                ('address_line_2', models.CharField(blank=True, default='', max_length=255, verbose_name='Address line 2')),
                ('city', models.CharField(blank=True, default='', max_length=120, verbose_name='City')),
                ('postal_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Postal code')),
                ('region', models.CharField(blank=True, default='', max_length=120, verbose_name='Region')),
                ('country_code', models.CharField(default='GR', help_text='ISO 3166-1 alpha-2 country code.', max_length=2, verbose_name='Country code')),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitude')),
                ('lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitude')),
                ('phone', models.CharField(blank=True, default='', max_length=120, verbose_name='Phone')),
                ('working_hours', models.TextField(blank=True, default='', verbose_name='Working hours')),
                ('max_weight_kg', models.DecimalField(decimal_places=2, default=6, help_text='Smartpoint lockers cap at 6 kg per ACS docs; non-locker stations have no fixed cap (still stored as 6 by default).', max_digits=5, verbose_name='Max weight (kg)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Last synced at')),
            ],
            options={
                'verbose_name': 'ACS station',
                'verbose_name_plural': 'ACS stations',
                'ordering': ['postal_code', 'external_id'],
                'indexes': [django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='acsstation_created_at_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['updated_at'], name='acsstation_updated_at_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['external_id'], name='acs_station_ext_id_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['postal_code'], name='acs_station_postal_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['shop_kind'], name='acs_station_shop_kind_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['is_active'], name='acs_station_active_ix')],
            },
        ),
        migrations.CreateModel(
            name='AcsShipment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('voucher_no', models.CharField(blank=True, default=None, help_text='10-digit ACS voucher (Voucher_No from ACS_Create_Voucher).', max_length=20, null=True, unique=True, verbose_name='Voucher number')),
                ('station_destination_external_id', models.CharField(blank=True, default='', help_text='Denormalised ACS_SHOP_STATION_ID — preserved even if the AcsStation row is deleted.', max_length=32, verbose_name='Destination station external ID')),
                ('station_branch_destination', models.CharField(blank=True, default='', help_text='Acs_Station_Branch_Destination value.', max_length=32, verbose_name='Destination branch')),
                ('delivery_kind', models.CharField(choices=[('home_delivery', 'Home delivery'), ('pickup_point', 'Pickup point / locker')], default='home_delivery', max_length=32, verbose_name='Delivery kind')),
                ('shipment_state', models.CharField(choices=[('pending_creation', 'Pending creation'), ('new', 'New'), ('in_transit', 'In transit'), ('at_destination', 'At destination station'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('attempted', 'Delivery attempted'), ('returned', 'Returned'), ('canceled', 'Canceled'), ('lost', 'Lost')], default='pending_creation', max_length=32, verbose_name='Shipment state')),
                ('weight_grams', models.PositiveIntegerField(default=0, help_text='Internal grams; converted to kilograms (>= 0.5) at API call time per ACS Weight requirements.', verbose_name='Weight (grams)')),
                ('item_quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Item quantity')),
                ('charge_type', models.PositiveSmallIntegerField(choices=[(1, 'Prepaid'), (2, 'Cash on delivery')], default=1, verbose_name='Charge type')),
                ('cod_amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3)),
                ('cod_amount', djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'EUR'), help_text='Amount collected at delivery. Required when ``charge_type`` = COD; ignored otherwise.', max_digits=11, verbose_name='COD amount')),
                ('cod_payment_way', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Cash'), (1, 'Card')], null=True, verbose_name='COD payment way')),
                ('delivery_products', models.CharField(blank=True, default='', help_text='Comma-separated Acs_Delivery_Products codes (COD, REC, SAT, RDO …).', max_length=64, verbose_name='Delivery products')),
                ('delivery_flag', models.CharField(blank=True, default='', help_text='Raw delivery_flag value from ACS_Trackingsummary.', max_length=4, verbose_name='Delivery flag')),
                ('returned_flag', models.CharField(blank=True, default='', max_length=4, verbose_name='Returned flag')),
                ('raw_shipment_status', models.CharField(blank=True, default='', max_length=8, verbose_name='Raw shipment status')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Delivery date')),
                ('last_polled_at', models.DateTimeField(blank=True, help_text='Used by poll_acs_tracking_batch to spread load and skip shipments polled within the last 15 minutes.', null=True, verbose_name='Last polled at')),
                ('last_event_at', models.DateTimeField(blank=True, null=True, verbose_name='Last event at')),
                ('cancel_requested_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancel requested at')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Multipart child voucher numbers, last create-voucher response, last error envelope, cached POD URL.', verbose_name='Metadata')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acs_shipment', to='order.order', verbose_name='Order')),
                ('pickup_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='shipping_acs.acspickuplist', verbose_name='Pickup list')),
                ('station_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='shipping_acs.acsstation', verbose_name='Destination station')),
            ],
            options={
                'verbose_name': 'ACS shipment',
                'verbose_name_plural': 'ACS shipments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AcsTrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('event_time', models.DateTimeField(help_text='Checkpoint_Date_Time from ACS_TrackingDetails.', verbose_name='Event time')),
                ('checkpoint_action', models.CharField(help_text='Checkpoint_Action_Description — human-readable Greek text describing the event.', max_length=255, verbose_name='Checkpoint action')),
                ('checkpoint_location', models.CharField(blank=True, default='', help_text='Checkpoint_Location_Description.', max_length=255, verbose_name='Checkpoint location')),
                ('notes', models.TextField(blank=True, default='', help_text='ACS Comments field.', verbose_name='Notes')),
                ('event_fingerprint', models.CharField(help_text="SHA-1 of shipment_id|event_time|action|location — replaces BoxNow's webhook_message_id since ACS has no event ID.", max_length=64, unique=True, verbose_name='Event fingerprint')),
                ('raw_payload', models.JSONField(help_text='Full row from ACS_TrackingDetails Table_Data.', verbose_name='Raw payload')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Wall-clock time when the polling task observed this event.', verbose_name='Received at')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shipping_acs.acsshipment', verbose_name='Shipment')),
            ],
            options={
                'verbose_name': 'ACS tracking event',
                'verbose_name_plural': 'ACS tracking events',
                'ordering': ['-event_time'],
            },
        ),
        migrations.AddIndex(
            model_name='acspickuplist',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='acspickuplist_created_at_ix'),
        ),
        migrations.AddIndex(
            model_name='acspickuplist',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['updated_at'], name='acspickuplist_updated_at_ix'),
        ),
        migrations.AddIndex(
            model_name='acspickuplist',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['pickup_list_no'], name='acs_pickup_list_no_ix'),
        ),
        migrations.AddIndex(
            model_name='acspickuplist',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['issued_at'], name='acs_pickup_issued_ix'),
        ),
        migrations.AddIndex(
            model_name='acsshipment',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='acsshipment_created_at_ix'),
        ),
        migrations.AddIndex(
            model_name='acsshipment',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['updated_at'], name='acsshipment_updated_at_ix'),
        ),
        migrations.AddIndex(
            model_name='acsshipment',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['voucher_no'], name='acs_shipment_voucher_ix'),
        ),
        migrations.AddIndex(
            model_name='acsshipment',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['shipment_state'], name='acs_shipment_state_ix'),
        ),
        migrations.AddIndex(
            model_name='acsshipment',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['pickup_list'], name='acs_shipment_pickup_ix'),
        ),
        migrations.AddIndex(
            model_name='acsshipment',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['last_polled_at'], name='acs_shipment_polled_ix'),
        ),
        migrations.AddIndex(
            model_name='acsshipment',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['shipment_state', 'last_polled_at'], name='acs_shipment_state_polled_ix'),
        ),
        migrations.AddIndex(
            model_name='acstrackingevent',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='acstrackingevent_created_at_ix'),
        ),
        migrations.AddIndex(
            model_name='acstrackingevent',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['updated_at'], name='acstrackingevent_updated_at_ix'),
        ),
        migrations.AddIndex(
            model_name='acstrackingevent',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['shipment'], name='acs_event_shipment_ix'),
        ),
        migrations.AddIndex(
            model_name='acstrackingevent',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['event_time'], name='acs_event_time_ix'),
        ),
        migrations.AddIndex(
            model_name='acstrackingevent',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['event_fingerprint'], name='acs_event_fingerprint_ix'),
        ),
    ]
