# Generated by Django 6.0.4 on 2026-04-29 12:48

import django.contrib.postgres.indexes
import django.db.models.deletion
import djmoney.models.fields
import djmoney.money
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_acs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcsCodPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('voucher_no', models.CharField(help_text='ACS voucher number — links back to AcsShipment.voucher_no without a hard FK so historic rows survive shipment deletions.', max_length=20, verbose_name='Voucher number')),
                ('customer_code', models.CharField(blank=True, default='', max_length=32, verbose_name='ACS customer code')),
                ('pod', models.CharField(blank=True, default='', max_length=255, verbose_name='Proof of delivery')),
                ('parcel_sender', models.CharField(blank=True, default='', max_length=255, verbose_name='Parcel sender')),
                ('parcel_receiver', models.CharField(blank=True, default='', max_length=255, verbose_name='Parcel receiver')),
                ('parcel_pickup_date', models.DateTimeField(blank=True, null=True, verbose_name='Parcel pickup date')),
                ('parcel_delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Parcel delivery date')),
                ('customer_ref_no_1', models.CharField(blank=True, default='', help_text='Reference_Key1 from voucher creation — matches Order.id for our partner-side reconciliation.', max_length=32, verbose_name='Customer reference 1')),
                ('customer_ref_no_2', models.CharField(blank=True, default='', max_length=64, verbose_name='Customer reference 2')),
                ('cod_amount_total_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3)),
                ('cod_amount_total', djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'EUR'), help_text='Parcel_COD_Amount from ACS.', max_digits=11, verbose_name='COD amount total')),
                ('cod_amount_cash_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3)),
                ('cod_amount_cash', djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'EUR'), max_digits=11, verbose_name='COD amount cash')),
                ('cod_amount_card_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3)),
                ('cod_amount_card', djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'EUR'), max_digits=11, verbose_name='COD amount card')),
                ('cod_payment_date', models.DateField(blank=True, help_text='Date ACS paid (or expects to pay) the partner. Forms half of the idempotency key together with voucher_no.', null=True, verbose_name='COD payment date')),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Full row from ACS_COD_Beneficiary_Info Table_Data.', verbose_name='Raw payload')),
                ('shipment', models.ForeignKey(blank=True, help_text='Resolved at upsert time when the matching AcsShipment row exists. Null for orphan rows (parcels paid via ACS before they were minted through this system, or rows where the shipment has been hard-deleted).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cod_payouts', to='shipping_acs.acsshipment', verbose_name='Shipment')),
            ],
            options={
                'verbose_name': 'ACS COD payout',
                'verbose_name_plural': 'ACS COD payouts',
                'ordering': ['-parcel_delivery_date', '-created_at'],
                'indexes': [django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='acscodpayout_created_at_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['updated_at'], name='acscodpayout_updated_at_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['voucher_no'], name='acs_cod_payout_voucher_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['cod_payment_date'], name='acs_cod_payout_paydate_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['customer_ref_no_1'], name='acs_cod_payout_ref1_ix')],
                'constraints': [models.UniqueConstraint(fields=('voucher_no', 'cod_payment_date'), name='acs_cod_payout_voucher_date_uq')],
            },
        ),
    ]
