# Generated by Django 6.0.4 on 2026-04-30 23:37

import django.db.models.deletion
import djmoney.models.fields
import djmoney.money
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0038_drop_shipping_method'),
        ('shipping_acs', '0002_acs_cod_payout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAcsShipment',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created At')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('id', models.BigIntegerField(blank=True, db_index=True)),
                ('voucher_no', models.CharField(blank=True, db_index=True, default=None, help_text='10-digit ACS voucher (Voucher_No from ACS_Create_Voucher).', max_length=20, null=True, verbose_name='Voucher number')),
                ('station_destination_external_id', models.CharField(blank=True, default='', help_text='Denormalised ACS_SHOP_STATION_ID — preserved even if the AcsStation row is deleted.', max_length=32, verbose_name='Destination station external ID')),
                ('station_branch_destination', models.CharField(blank=True, default='', help_text='Acs_Station_Branch_Destination value.', max_length=32, verbose_name='Destination branch')),
                ('delivery_kind', models.CharField(choices=[('home_delivery', 'Home delivery'), ('pickup_point', 'Pickup point / locker')], default='home_delivery', max_length=32, verbose_name='Delivery kind')),
                ('shipment_state', models.CharField(choices=[('pending_creation', 'Pending creation'), ('new', 'New'), ('in_transit', 'In transit'), ('at_destination', 'At destination station'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('attempted', 'Delivery attempted'), ('returned', 'Returned'), ('canceled', 'Canceled'), ('lost', 'Lost')], default='pending_creation', max_length=32, verbose_name='Shipment state')),
                ('weight_grams', models.PositiveIntegerField(default=0, help_text='Internal grams; converted to kilograms (>= 0.5) at API call time per ACS Weight requirements.', verbose_name='Weight (grams)')),
                ('item_quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Item quantity')),
                ('charge_type', models.PositiveSmallIntegerField(choices=[(1, 'Prepaid'), (2, 'Cash on delivery')], default=1, verbose_name='Charge type')),
                ('cod_amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3)),
                ('cod_amount', djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'EUR'), help_text='Amount collected at delivery. Required when ``charge_type`` = COD; ignored otherwise.', max_digits=11, verbose_name='COD amount')),
                ('cod_payment_way', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Cash'), (1, 'Card')], null=True, verbose_name='COD payment way')),
                ('delivery_products', models.CharField(blank=True, default='', help_text='Comma-separated Acs_Delivery_Products codes (COD, REC, SAT, RDO …).', max_length=64, verbose_name='Delivery products')),
                ('delivery_flag', models.CharField(blank=True, default='', help_text='Raw delivery_flag value from ACS_Trackingsummary.', max_length=4, verbose_name='Delivery flag')),
                ('returned_flag', models.CharField(blank=True, default='', max_length=4, verbose_name='Returned flag')),
                ('raw_shipment_status', models.CharField(blank=True, default='', max_length=8, verbose_name='Raw shipment status')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Delivery date')),
                ('last_event_at', models.DateTimeField(blank=True, null=True, verbose_name='Last event at')),
                ('cancel_requested_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancel requested at')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.order', verbose_name='Order')),
                ('pickup_list', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shipping_acs.acspickuplist', verbose_name='Pickup list')),
                ('station_destination', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shipping_acs.acsstation', verbose_name='Destination station')),
            ],
            options={
                'verbose_name': 'historical ACS shipment',
                'verbose_name_plural': 'historical ACS shipments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
