# Generated by Django 6.0.5 on 2026-05-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_acs', '0003_historicalacsshipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acsshipment',
            name='charge_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Prepaid'), (2, 'Cash on delivery')], default=2, verbose_name='Charge type'),
        ),
        migrations.AlterField(
            model_name='historicalacsshipment',
            name='charge_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Prepaid'), (2, 'Cash on delivery')], default=2, verbose_name='Charge type'),
        ),
    ]
