# Generated by Django 6.0.7 on 2026-07-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_acs', '0004_acsshipment_default_charge_type_cod'),
    ]

    operations = [
        migrations.AddField(
            model_name='acsshipment',
            name='stale_alert_sent',
            field=models.BooleanField(default=False, help_text='Set by check_stale_acs_shipments after admins were alerted that this shipment shows no tracking movement; cleared automatically when a new tracking event arrives.', verbose_name='Stale alert sent'),
        ),
    ]
