# Generated by Django 6.0.7 on 2026-07-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_acs', '0005_acsshipment_stale_alert_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acsstation',
            name='branch_code',
            field=models.CharField(blank=True, default='', help_text='ACS_SHOP_BRANCH_ID — paired with external_id when creating vouchers (Acs_Station_Branch_Destination). Distinguishes individual lockers within a station area.', max_length=32, verbose_name='Branch code'),
        ),
        migrations.AlterField(
            model_name='acsstation',
            name='external_id',
            field=models.CharField(help_text="ACS_SHOP_STATION_ID_EN — the AREA station code, used as Acs_Station_Destination. NOT unique on its own: every Smartpoint locker in an area shares it (e.g. 50 lockers under 'ATH'); the (external_id, branch_code) pair is the locker's identity.", max_length=32, verbose_name='External ID'),
        ),
        migrations.AlterField(
            model_name='acsstation',
            name='shop_kind',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Shop'), (2, 'Partner shop (2)'), (3, 'Partner shop (3)'), (4, 'Xpress Point'), (5, 'Kiosk'), (7, 'Smartpoint (no locker)'), (8, 'Smartpoint locker')], help_text='ACS_SHOP_KIND — 1 shop, 7/8 Smartpoint locker.', verbose_name='Shop kind'),
        ),
        migrations.AddConstraint(
            model_name='acsstation',
            constraint=models.UniqueConstraint(fields=('external_id', 'branch_code'), name='acs_station_ext_branch_uq'),
        ),
    ]
