# Generated by Django 6.0.8 on 2026-08-19 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_acs', '0007_alter_historicalacsshipment_history_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='acspickuplist',
            name='issued_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Admin who triggered the manual issue. Null when the daily Celery beat task issued the list. Stores a PLATFORM-schema user id; not FK-enforced (see db_constraint above).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acs_pickup_lists_issued', to=settings.AUTH_USER_MODEL, verbose_name='Issued by'),
        ),
    ]
