# Generated by Django 6.0.8 on 2026-09-02 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_acs', '0008_alter_acspickuplist_issued_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='acsshipment',
            name='label_printed_at',
            field=models.DateTimeField(blank=True, help_text="When ACS_Print_Voucher was last run for this voucher. ACS refuses to issue the daily pickup list while any voucher on it is unprinted, and that state lives on ACS's side — this column is the local mirror so unprinted vouchers are visible BEFORE the 16:30 manifest run rejects them. Advisory only: a label printed from ACS's own portal never reaches this code, so nothing gates on it.", null=True, verbose_name='Label printed at'),
        ),
        migrations.AddField(
            model_name='historicalacsshipment',
            name='label_printed_at',
            field=models.DateTimeField(blank=True, help_text="When ACS_Print_Voucher was last run for this voucher. ACS refuses to issue the daily pickup list while any voucher on it is unprinted, and that state lives on ACS's side — this column is the local mirror so unprinted vouchers are visible BEFORE the 16:30 manifest run rejects them. Advisory only: a label printed from ACS's own portal never reaches this code, so nothing gates on it.", null=True, verbose_name='Label printed at'),
        ),
    ]
