# Generated by Django 6.0.8 on 2026-09-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_acs', '0009_acsshipment_label_printed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acsshipment',
            name='arrival_notified_at',
            field=models.DateTimeField(blank=True, help_text="When the customer was told the parcel is out for delivery. ACS's shipment_status is a snapshot of the parcel's current leg, not a monotonic sequence: a parcel loaded on a vehicle (4), returned to the depot at end of shift (3) and loaded again next morning (4) re-enters OUT_FOR_DELIVERY, and the notification fired on every edge. Set once, under the same lock as the state change.", null=True, verbose_name='Arrival notified at'),
        ),
        migrations.AddField(
            model_name='historicalacsshipment',
            name='arrival_notified_at',
            field=models.DateTimeField(blank=True, help_text="When the customer was told the parcel is out for delivery. ACS's shipment_status is a snapshot of the parcel's current leg, not a monotonic sequence: a parcel loaded on a vehicle (4), returned to the depot at end of shift (3) and loaded again next morning (4) re-enters OUT_FOR_DELIVERY, and the notification fired on every edge. Set once, under the same lock as the state change.", null=True, verbose_name='Arrival notified at'),
        ),
    ]
