# Generated by Django 6.0.8 on 2026-10-05 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_acs', '0011_field_verbose_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acsshipment',
            name='cod_received_outside_acs_at',
            field=models.DateTimeField(blank=True, help_text="When an operator recorded that the merchant received this parcel's COD money by a route ACS never reported. Clears the unremitted-COD alert for the parcel; ACS's own payout rows are untouched.", null=True, verbose_name='COD received outside ACS at'),
        ),
        migrations.AddField(
            model_name='acsshipment',
            name='cod_received_outside_acs_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Operator who recorded the settlement. Stores a PLATFORM-schema user id; not FK-enforced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acs_cod_settlements_recorded', to=settings.AUTH_USER_MODEL, verbose_name='COD received outside ACS by'),
        ),
        migrations.AddField(
            model_name='acsshipment',
            name='cod_received_outside_acs_note',
            field=models.TextField(blank=True, db_default='', default='', help_text='How and when the money arrived (bank transfer reference, hand delivery, ...), as written by the operator.', verbose_name='COD received outside ACS note'),
        ),
        migrations.AddField(
            model_name='historicalacsshipment',
            name='cod_received_outside_acs_at',
            field=models.DateTimeField(blank=True, help_text="When an operator recorded that the merchant received this parcel's COD money by a route ACS never reported. Clears the unremitted-COD alert for the parcel; ACS's own payout rows are untouched.", null=True, verbose_name='COD received outside ACS at'),
        ),
        migrations.AddField(
            model_name='historicalacsshipment',
            name='cod_received_outside_acs_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Operator who recorded the settlement. Stores a PLATFORM-schema user id; not FK-enforced.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='COD received outside ACS by'),
        ),
        migrations.AddField(
            model_name='historicalacsshipment',
            name='cod_received_outside_acs_note',
            field=models.TextField(blank=True, db_default='', default='', help_text='How and when the money arrived (bank transfer reference, hand delivery, ...), as written by the operator.', verbose_name='COD received outside ACS note'),
        ),
    ]
