# Generated by Django 4.2 on 2023-04-13 23:50

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "sort_order",
                    models.IntegerField(db_index=True, editable=False, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "alpha_2",
                    models.CharField(
                        max_length=2, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("alpha_3", models.CharField(max_length=3, unique=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "iso_cc",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, unique=True
                    ),
                ),
                (
                    "phone_code",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, unique=True
                    ),
                ),
                (
                    "image_flag",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/country/"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Countries",
            },
        ),
    ]
