# Generated by Django 5.0.4 on 2024-04-11 11:43
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("country", "0002_country_country_created_at_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={
                "ordering": ["-sort_order"],
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
            },
        ),
    ]
