# Generated by Django 6.0.5 on 2026-05-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0006_remove_country_country_cou_alpha_2_398383_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='countrytranslation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='countrytranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='country_country_translation_uniq_lang'),
        ),
    ]
