# Generated by Django 6.0.7 on 2026-07-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0008_alter_country_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='phone_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Phone Code'),
        ),
    ]
