# Generated by Django 6.0.8 on 2026-10-01 00:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0012_seed_iso_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
