/**
 * PostToolUse hook: Auto-lint Python files after Edit/Write.
 *
 * Runs `uv run ruff check --fix` and `uv run ruff format` on .py files.
 * Skips migration files (auto-generated by Django).
 * Silently catches errors (Ruff failures don't block the workflow).
 *
 * Receives JSON on stdin: { tool_name, tool_input: { file_path, ... } }
 */
import { readFileSync } from 'node:fs'
import { execSync } from 'node:child_process'

const input = JSON.parse(readFileSync(0, 'utf8'))
const filePath = input.tool_input?.file_path

if (filePath && /\.py$/.test(filePath) && !/\/migrations\//.test(filePath.replace(/\\/g, '/'))) {
  try {
    execSync(`uv run ruff check --fix --quiet ${JSON.stringify(filePath)}`, { stdio: 'pipe' })
    execSync(`uv run ruff format --quiet ${JSON.stringify(filePath)}`, { stdio: 'pipe' })
  }
  catch {
    // Ruff errors are non-blocking
  }
}
