# Generated by Django 4.2 on 2023-04-13 23:50
import uuid

import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vat",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.DecimalField(decimal_places=1, max_digits=11)),
            ],
            options={
                "verbose_name_plural": "Value Added Tax",
                "ordering": ["-updated_at"],
            },
        ),
    ]
