# Generated by Django 6.0.8 on 2026-08-30 18:45

import django.core.validators
import vat.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vat", "0007_seed_default_vat_rates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vat",
            name="value",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("0.0"),
                max_digits=11,
                validators=[
                    django.core.validators.MinValueValidator(
                        Decimal("0.0"),
                        message="VAT value must be at least %(limit_value)s.",
                    ),
                    django.core.validators.MaxValueValidator(
                        Decimal("100.0"),
                        message="VAT value cannot exceed %(limit_value)s.",
                    ),
                    vat.models.validate_mydata_vat_rate,
                ],
                verbose_name="Value",
            ),
        ),
    ]
