# Generated by Django 6.0.8 on 2026-08-30 20:01

import b2b.validators
import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import djmoney.models.fields
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0042_seo_description_plain_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Percent off the retail NET (VAT-exclusive) price. A fixed price-list entry for a product wins over this.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Discount percent')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Customer Group',
                'verbose_name_plural': 'Customer Groups',
                'db_table': 'b2b_customer_group',
                'ordering': ['name'],
                'indexes': [django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='customergroup_created_at_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['updated_at'], name='customergroup_updated_at_ix')],
            },
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=10, verbose_name='Status')),
                ('company_name', models.CharField(max_length=255, verbose_name='Company name')),
                ('vat_id', models.CharField(help_text='Stored normalised: 9 digits, no EL/GR prefix', max_length=12, validators=[b2b.validators.validate_greek_vat], verbose_name='VAT number (ΑΦΜ)')),
                ('tax_office', models.CharField(max_length=100, verbose_name='Tax office (ΔΟΥ)')),
                ('activity', models.CharField(max_length=255, verbose_name='Business activity')),
                ('billing_street', models.CharField(blank=True, default='', max_length=255, verbose_name='Billing street')),
                ('billing_street_number', models.CharField(blank=True, default='', max_length=50, verbose_name='Billing street number')),
                ('billing_city', models.CharField(blank=True, default='', max_length=100, verbose_name='Billing city')),
                ('billing_zipcode', models.CharField(blank=True, default='', max_length=20, verbose_name='Billing zipcode')),
                ('vies_status', models.CharField(choices=[('UNCHECKED', 'Not checked'), ('VALID', 'Valid'), ('INVALID', 'Invalid'), ('UNAVAILABLE', 'Service unavailable')], default='UNCHECKED', max_length=12, verbose_name='VIES status')),
                ('vies_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='VIES checked at')),
                ('vies_name', models.CharField(blank=True, default='', max_length=255, verbose_name='VIES name')),
                ('vies_address', models.CharField(blank=True, default='', max_length=255, verbose_name='VIES address')),
                ('vies_error', models.CharField(blank=True, default='', max_length=255, verbose_name='VIES error')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed at')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='Rejection reason')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_profiles_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
                ('customer_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_profiles', to='b2b.customergroup')),
            ],
            options={
                'verbose_name': 'Business Profile',
                'verbose_name_plural': 'Business Profiles',
                'db_table': 'b2b_business_profile',
                'ordering': ['-created_at'],
                'indexes': [django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='businessprofile_created_at_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['updated_at'], name='businessprofile_updated_at_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['status'], name='b2b_profile_status_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['vat_id'], name='b2b_profile_vat_ix')],
            },
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('net_price_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3)),
                ('net_price', djmoney.models.fields.MoneyField(decimal_places=2, help_text="Fixed NET (VAT-exclusive) price for this group. Wins over the group's discount percent.", max_digits=11, verbose_name='Net price override')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_items', to='b2b.customergroup')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_prices', to='product.product')),
            ],
            options={
                'verbose_name': 'B2B Price List Item',
                'verbose_name_plural': 'B2B Price List Items',
                'db_table': 'b2b_price_list_item',
                'ordering': ['-created_at'],
                'indexes': [django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='pricelistitem_created_at_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['updated_at'], name='pricelistitem_updated_at_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['product'], name='b2b_price_product_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['group'], name='b2b_price_group_ix')],
                'constraints': [models.UniqueConstraint(fields=('group', 'product'), name='unique_b2b_group_product')],
            },
        ),
    ]
