# Generated by Django 6.0.8 on 2026-08-31 04:00

import djmoney.models.fields
import djmoney.money
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customergroup',
            name='min_order_value',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(Decimal('0'), 'EUR'), help_text="Minimum cart items total (VAT-inclusive) required to place an order at this group's prices — a standard wholesale term. 0 disables the check.", max_digits=11, verbose_name='Minimum order value'),
        ),
        migrations.AddField(
            model_name='customergroup',
            name='min_order_value_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3),
        ),
    ]
