# Generated by Django 6.0.8 on 2026-09-05 09:35

import djmoney.models.fields
import djmoney.models.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0002_customergroup_min_order_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelistitem',
            name='net_price',
            field=djmoney.models.fields.MoneyField(currency_choices=[('EUR', 'EUR')], decimal_places=2, help_text="Fixed NET (VAT-exclusive) price for this group. Wins over the group's discount percent.", max_digits=11, validators=[djmoney.models.validators.MinMoneyValidator(0)], verbose_name='Net price override'),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='net_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR')], default='EUR', editable=False, max_length=3),
        ),
    ]
