# Generated by Django 6.0.8 on 2026-10-01 00:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0003_b2b_price_override_bounds'),
        ('product', '0048_field_verbose_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='customer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_profiles', to='b2b.customergroup', verbose_name='Customer group'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_profiles_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed by'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='customergroup',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_items', to='b2b.customergroup', verbose_name='Customer group'),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_prices', to='product.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
