exclude: '^$'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: fix-byte-order-marker
  - repo: https://github.com/ambv/black
    rev: 24.10.0
    hooks:
      - id: black
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.14.0
    hooks:
      -   id: reorder-python-imports
  - repo: https://github.com/pycqa/flake8
    rev: '7.1.1'
    hooks:
      - id: flake8
        args: ["--config=.flake8"]
        language_version: python3
  - repo: local
    hooks:
      - id: coverage
        name: coverage
        stages: [pre-push]
        language: system
        entry: coverage run
        types: [python]
        pass_filenames: false

default_language_version:
  python: python3.12.0
