# Generated by Django 6.0.4 on 2026-04-17 23:22

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10, verbose_name='Language Code')),
                ('msgid', models.TextField(verbose_name='Message ID')),
                ('msgid_plural', models.TextField(blank=True, default='', help_text='Empty for singular entries. Set for ngettext / msgid_plural entries; in that case each plural form has its own row identified by plural_index.', verbose_name='Plural Message ID')),
                ('plural_index', models.PositiveSmallIntegerField(default=0, help_text="0 for singular entries or for the first plural form; 1, 2, ... for subsequent plural forms defined by the language's plural rule.", verbose_name='Plural Index')),
                ('msgstr', models.TextField(blank=True, default='', verbose_name='Translation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
                'ordering': ['language_code', 'msgid', 'plural_index'],
                'indexes': [django.contrib.postgres.indexes.BTreeIndex(fields=['language_code'], name='translation_lang_ix')],
                'constraints': [models.UniqueConstraint(fields=('language_code', 'msgid', 'plural_index'), name='translation_lang_msgid_idx_uniq')],
            },
        ),
    ]
