# Generated by Django 6.0.4 on 2026-05-05 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_translation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CachePurgeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('surfaces', models.JSONField(default=list, verbose_name='Surfaces')),
                ('dry_run', models.BooleanField(default=False, verbose_name='Dry run')),
                ('total_django', models.PositiveIntegerField(default=0, verbose_name='Django keys')),
                ('total_nuxt', models.PositiveIntegerField(default=0, verbose_name='Nuxt keys')),
                ('total_blocked', models.PositiveIntegerField(default=0, verbose_name='Blocked keys')),
                ('detail', models.JSONField(default=list, verbose_name='Detail')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cache_purge_logs', to=settings.AUTH_USER_MODEL, verbose_name='Actor')),
            ],
            options={
                'verbose_name': 'Cache purge log',
                'verbose_name_plural': 'Cache purge logs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['-created_at'], name='cachelog_created_idx')],
            },
        ),
    ]
