# Generated by Django 6.0.8 on 2026-09-13 14:03

from django.conf import settings
from django.db import migrations, models


def backfill_actor_email(apps, schema_editor):
    """Copy each existing row's actor address into the new column.

    Safe to resolve here, and only here: this table lives in the public
    schema and the migration runs there, so ``actor_id`` refers to the user
    table the FK was written against. That is exactly the lookup the admin
    panel must NOT do at read time, because a tenant host resolves the same
    id against its own user table.

    ``schema_name`` is deliberately left empty. Which store caused a given
    historical purge is not recoverable, and guessing would put another
    store's activity on a merchant's page — the bug this migration exists to
    close. Empty rows stay on the control plane.
    """
    CachePurgeLog = apps.get_model("core", "CachePurgeLog")
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))

    emails = dict(User.objects.values_list("pk", "email"))
    updates = []
    for row in CachePurgeLog.objects.exclude(actor_id=None).only(
        "id", "actor_id", "actor_email"
    ):
        email = emails.get(row.actor_id)
        if email and not row.actor_email:
            row.actor_email = email
            updates.append(row)
    if updates:
        CachePurgeLog.objects.bulk_update(updates, ["actor_email"], batch_size=500)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_drop_orphaned_token_blacklist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cachepurgelog",
            name="actor_email",
            field=models.EmailField(
                blank=True,
                default="",
                max_length=254,
                verbose_name="Actor email",
            ),
        ),
        migrations.AddField(
            model_name="cachepurgelog",
            name="schema_name",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=63,
                verbose_name="Schema",
            ),
        ),
        # Both AddFields are additive with defaults, so the old code keeps
        # running against the new schema — required, because the PreSync hook
        # migrates before the new image rolls out.
        migrations.RunPython(
            backfill_actor_email,
            migrations.RunPython.noop,
            elidable=True,
        ),
    ]
