# Generated by Django 6.0.8 on 2026-09-30 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cache_purge_log_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cachepurgelog',
            options={'ordering': ('-created_at',), 'permissions': [('purge_cache', 'Can purge caches')], 'verbose_name': 'Cache purge log', 'verbose_name_plural': 'Cache purge logs'},
        ),
    ]
