# Generated by Django 4.2 on 2023-04-13 23:50
import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import tinymce.models
from django.db import migrations
from django.db import models

import product.models.product


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        max_length=70,
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(70)],
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(300)],
                    ),
                ),
                (
                    "seo_keywords",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(255)],
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "product_code",
                    models.CharField(
                        default=product.models.product.generate_unique_code,
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", tinymce.models.HTMLField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=11)),
                ("active", models.BooleanField(default=True)),
                ("stock", models.PositiveIntegerField(default=1)),
                (
                    "discount_percent",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
                ),
                ("hits", models.PositiveIntegerField(default=0)),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=11,
                        verbose_name="Weight (kg)",
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        decimal_places=2, default=0.0, editable=False, max_digits=11
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2, default=0.0, editable=False, max_digits=11
                    ),
                ),
                (
                    "price_save_percent",
                    models.DecimalField(
                        decimal_places=2, default=0.0, editable=False, max_digits=11
                    ),
                ),
            ],
            options={
                "ordering": ("-id",),
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        max_length=70,
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(70)],
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(300)],
                    ),
                ),
                (
                    "seo_keywords",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(255)],
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", tinymce.models.HTMLField(blank=True, null=True)),
                (
                    "menu_image_one",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/categories/"
                    ),
                ),
                (
                    "menu_image_two",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/categories/"
                    ),
                ),
                (
                    "menu_main_banner",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/categories/"
                    ),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="ProductFavourite",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name_plural": "Favourite Products",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImages",
            fields=[
                (
                    "sort_order",
                    models.IntegerField(db_index=True, editable=False, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="uploads/products/")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/products/thumbnails/"
                    ),
                ),
                ("is_main", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Product Images",
            },
        ),
        migrations.CreateModel(
            name="ProductTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "language_code",
                    models.CharField(
                        choices=[("en-US", "EN"), ("gr-GR", "GR")],
                        max_length=35,
                        unique=True,
                    ),
                ),
                (
                    "seo_title",
                    models.CharField(
                        blank=True,
                        max_length=70,
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(70)],
                    ),
                ),
                (
                    "seo_description",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(300)],
                    ),
                ),
                (
                    "seo_keywords",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        validators=[django.core.validators.MaxLengthValidator(255)],
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=250, null=True)),
                ("description", tinymce.models.HTMLField(blank=True, null=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_translations",
                        to="product.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=False)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("comment", models.CharField(blank=True, max_length=250)),
                (
                    "rate",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "ONE"),
                            (2, "TWO"),
                            (3, "THREE"),
                            (4, "FOUR"),
                            (5, "FIVE"),
                            (6, "SIX"),
                            (7, "SEVEN"),
                            (8, "EIGHT"),
                            (9, "NINE"),
                            (10, "TEN"),
                        ]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("New", "NEW"), ("True", "TRUE"), ("False", "FALSE")],
                        default="New",
                        max_length=250,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_review_product",
                        to="product.product",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Product Reviews",
                "ordering": ["-updated_at"],
            },
        ),
    ]
