# Generated by Django 5.1 on 2024-08-24 22:51
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0017_product_changed_by_historicalproduct"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategory",
            name="sort_order",
            field=models.IntegerField(editable=False, null=True, verbose_name="Sort Order"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="sort_order",
            field=models.IntegerField(editable=False, null=True, verbose_name="Sort Order"),
        ),
    ]
