# Generated by Django 6.0.4 on 2026-04-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_alter_historicalproduct_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='low_stock_alert_sent',
            field=models.BooleanField(default=False, help_text='Internal flag — prevents duplicate alerts. Automatically cleared when stock rises above the threshold.', verbose_name='Low Stock Alert Sent'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10, help_text='Stock level at or below which admins get a low-stock alert. Set to 0 to disable alerts for this product.', verbose_name='Low Stock Threshold'),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_alert_sent',
            field=models.BooleanField(default=False, help_text='Internal flag — prevents duplicate alerts. Automatically cleared when stock rises above the threshold.', verbose_name='Low Stock Alert Sent'),
        ),
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=10, help_text='Stock level at or below which admins get a low-stock alert. Set to 0 to disable alerts for this product.', verbose_name='Low Stock Threshold'),
        ),
    ]
