# Generated by Django 6.0.4 on 2026-04-19 19:28

import django.contrib.postgres.indexes
import django.db.models.deletion
import djmoney.models.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_historicalproduct_low_stock_alert_sent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAlert',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('restock', 'Restock'), ('price_drop', 'Price drop')], max_length=16, verbose_name='Kind')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('target_price_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3, null=True)),
                ('target_price', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, help_text="For price_drop alerts: trigger when the product's price falls to or below this value. Ignored for restock alerts.", max_digits=11, null=True, verbose_name='Target price')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Notified at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='product.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product alert',
                'verbose_name_plural': 'Product alerts',
                'ordering': ['-created_at'],
                'indexes': [django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='productalert_created_at_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['updated_at'], name='productalert_updated_at_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['product', 'kind', 'is_active'], name='product_alert_active_ix')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('kind', 'product', 'user'), name='unique_product_alert_user'), models.UniqueConstraint(condition=models.Q(('user__isnull', True), models.Q(('email', ''), _negated=True)), fields=('kind', 'product', 'email'), name='unique_product_alert_email'), models.CheckConstraint(condition=models.Q(('user__isnull', False), models.Q(('email', ''), _negated=True), _connector='OR'), name='product_alert_has_recipient')],
            },
        ),
    ]
