# Generated by Django 6.0.4 on 2026-04-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_productalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='price_drop_alerts_enabled',
            field=models.BooleanField(default=False, help_text="When enabled, customers can subscribe to a one-time email when this product's price drops below a target. Disabled by default — admins opt products in per SKU.", verbose_name='Price-drop Alerts Enabled'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_drop_alerts_enabled',
            field=models.BooleanField(default=False, help_text="When enabled, customers can subscribe to a one-time email when this product's price drops below a target. Disabled by default — admins opt products in per SKU.", verbose_name='Price-drop Alerts Enabled'),
        ),
    ]
