# Generated by Django 6.0.4 on 2026-05-02 13:51

from django.db import migrations, models


def deduplicate_main_product_images(apps, schema_editor):
    """
    Ensure no product has more than one is_main=True ProductImage.

    For each product that has multiple main images, keep the one with the
    lowest primary-key (oldest) and set is_main=False on the rest.
    This is idempotent: products with 0 or 1 main image are untouched.
    """
    ProductImage = apps.get_model("product", "ProductImage")
    db_alias = schema_editor.connection.alias

    # Find products with more than one main image
    from django.db.models import Count

    products_with_multiple_mains = (
        ProductImage.objects.using(db_alias)
        .filter(is_main=True)
        .values("product_id")
        .annotate(cnt=Count("id"))
        .filter(cnt__gt=1)
        .values_list("product_id", flat=True)
    )

    for product_id in products_with_multiple_mains:
        main_images = (
            ProductImage.objects.using(db_alias)
            .filter(product_id=product_id, is_main=True)
            .order_by("id")
        )
        # Keep the first (lowest pk), unset the rest
        ids_to_clear = list(main_images.values_list("id", flat=True)[1:])
        if ids_to_clear:
            ProductImage.objects.using(db_alias).filter(
                id__in=ids_to_clear
            ).update(is_main=False)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0032_product_price_drop_alerts_enabled"),
    ]

    operations = [
        migrations.RunPython(
            deduplicate_main_product_images,
            reverse_code=noop,
        ),
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_main", True)),
                fields=("product",),
                name="unique_main_product_image",
            ),
        ),
    ]
