# Generated by Django 6.0.5 on 2026-05-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_productimage_unique_main_constraint'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attributetranslation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='attributevaluetranslation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='productcategoryimagetranslation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='productcategorytranslation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='productimagetranslation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='productreviewtranslation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='attributetranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='product_attribute_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='attributevaluetranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='product_attributevalue_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='productcategoryimagetranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='product_productcategoryimage_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='productcategorytranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='product_productcategory_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='productimagetranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='product_productimage_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='productreviewtranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='product_productreview_translation_uniq_lang'),
        ),
    ]
