# Generated by Django 6.0.5 on 2026-05-22 09:55

import core.fields.measurement
import core.weight
import measurement.measures.mass
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_alter_attributetranslation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='weight',
            field=core.fields.measurement.MeasurementField(default=core.weight.zero_weight, measurement=measurement.measures.mass.Mass, verbose_name='Βάρος'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=core.fields.measurement.MeasurementField(default=core.weight.zero_weight, measurement=measurement.measures.mass.Mass, verbose_name='Βάρος'),
        ),
    ]
