# Generated by Django 6.0.5 on 2026-05-22 11:00

import core.fields.measurement
import core.weight
import measurement.measures.mass
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_alter_historicalproduct_weight_alter_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='weight',
            field=core.fields.measurement.MeasurementField(default=core.weight.zero_weight, measurement=measurement.measures.mass.Mass, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=core.fields.measurement.MeasurementField(default=core.weight.zero_weight, measurement=measurement.measures.mass.Mass, verbose_name='Weight'),
        ),
    ]
