# Generated by Django 6.0.5 on 2026-05-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_alter_historicalproduct_weight_alter_product_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='sort_order',
            field=models.IntegerField(null=True, verbose_name='Sort Order'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='sort_order',
            field=models.IntegerField(null=True, verbose_name='Sort Order'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='sort_order',
            field=models.IntegerField(null=True, verbose_name='Sort Order'),
        ),
        migrations.AlterField(
            model_name='productcategoryimage',
            name='sort_order',
            field=models.IntegerField(null=True, verbose_name='Sort Order'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='sort_order',
            field=models.IntegerField(null=True, verbose_name='Sort Order'),
        ),
    ]
