# Generated by Django 6.0.6 on 2026-06-29 15:14

import django.contrib.postgres.indexes
import django.db.models.deletion
import parler.fields
import parler.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_alter_attribute_sort_order_and_more'),
        ('vat', '0006_rename_vat_created_at_idx_vat_created_at_ix_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Product Variant Group',
                'verbose_name_plural': 'Product Variant Groups',
                'ordering': ['-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductVariantGroupTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Product Variant Group Translation',
                'db_table': 'product_productvariantgroup_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='attribute',
            name='is_variant',
            field=models.BooleanField(default=False, help_text="When enabled, this attribute is rendered as a variant selector (e.g. Colour, Memory) across a product's variant group instead of as a plain read-only specification.", verbose_name='Is Variant Axis'),
        ),
        migrations.AddIndex(
            model_name='attribute',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['is_variant'], name='attribute_is_variant_ix'),
        ),
        migrations.AddIndex(
            model_name='productvariantgroup',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='pvgroup_created_at_ix'),
        ),
        migrations.AddIndex(
            model_name='productvariantgroup',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['updated_at'], name='pvgroup_updated_at_ix'),
        ),
        migrations.AddIndex(
            model_name='productvariantgroup',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['active'], name='pvgroup_active_ix'),
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='variant_group',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Links this product to its sibling variations (e.g. the same item in other colours). Members share variant selectors on the storefront.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='product.productvariantgroup'),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_group',
            field=models.ForeignKey(blank=True, help_text='Links this product to its sibling variations (e.g. the same item in other colours). Members share variant selectors on the storefront.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='product.productvariantgroup'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['variant_group'], name='product_variant_group_ix'),
        ),
        migrations.AddField(
            model_name='productvariantgrouptranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='product.productvariantgroup'),
        ),
        migrations.AddConstraint(
            model_name='productvariantgrouptranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='product_productvariantgroup_translation_uniq_lang'),
        ),
    ]
