# Generated by Django 6.0.8 on 2026-08-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_add_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='click_score',
            field=models.PositiveIntegerField(db_default=0, editable=False, help_text='Search click-through ranking signal - trailing-window click count refreshed by search.tasks.update_click_scores', verbose_name='Click Score'),
        ),
        migrations.AddField(
            model_name='product',
            name='click_score',
            field=models.PositiveIntegerField(db_default=0, editable=False, help_text='Search click-through ranking signal - trailing-window click count refreshed by search.tasks.update_click_scores', verbose_name='Click Score'),
        ),
    ]
