# Generated by Django 6.0.8 on 2026-09-10 17:02

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_seo_description_plain_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(null=True, verbose_name='Sort Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('relation_type', models.CharField(choices=[('similar', 'Similar product'), ('complementary', 'Goes well with'), ('accessory', 'Accessory for'), ('replacement', 'Replacement for'), ('bundle', 'Bundle with')], default='similar', max_length=20, verbose_name='Relation type')),
                ('from_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='product.product', verbose_name='From product')),
                ('to_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_from', to='product.product', verbose_name='To product')),
            ],
            options={
                'verbose_name': 'Product relation',
                'verbose_name_plural': 'Product relations',
                'ordering': ['from_product_id', 'sort_order'],
                'indexes': [django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='productrelation_created_at_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['updated_at'], name='productrelation_updated_at_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['sort_order'], name='productrelation_sort_order_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['from_product', 'relation_type'], name='product_relation_from_type_ix')],
                'constraints': [models.UniqueConstraint(fields=('from_product', 'to_product', 'relation_type'), name='product_relation_unique_typed_pair'), models.CheckConstraint(condition=models.Q(('from_product', models.F('to_product')), _negated=True), name='product_relation_not_self')],
            },
        ),
    ]
