# Generated by Django 6.0.2 on 2026-03-02 20:59

import django.core.validators
import django.db.models.deletion
import django_tenants.postgresql_backend.base
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('owner_email', models.EmailField(max_length=254, verbose_name='Owner Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('plan', models.CharField(choices=[('trial', 'Trial'), ('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='trial', max_length=20, verbose_name='Plan')),
                ('paid_until', models.DateField(blank=True, null=True, verbose_name='Paid Until')),
                ('store_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Store Name')),
                ('store_description', models.TextField(blank=True, default='', verbose_name='Store Description')),
                ('default_locale', models.CharField(default='el', max_length=10, verbose_name='Default Locale')),
                ('default_currency', models.CharField(default='EUR', max_length=3, verbose_name='Default Currency')),
                ('logo_light_url', models.URLField(blank=True, default='', verbose_name='Logo (Light)')),
                ('logo_dark_url', models.URLField(blank=True, default='', verbose_name='Logo (Dark)')),
                ('favicon_url', models.URLField(blank=True, default='', verbose_name='Favicon URL')),
                ('primary_color', models.CharField(choices=[('slate', 'Slate'), ('gray', 'Gray'), ('zinc', 'Zinc'), ('neutral', 'Neutral'), ('stone', 'Stone'), ('red', 'Red'), ('orange', 'Orange'), ('amber', 'Amber'), ('yellow', 'Yellow'), ('lime', 'Lime'), ('green', 'Green'), ('emerald', 'Emerald'), ('teal', 'Teal'), ('cyan', 'Cyan'), ('sky', 'Sky'), ('blue', 'Blue'), ('indigo', 'Indigo'), ('violet', 'Violet'), ('purple', 'Purple'), ('fuchsia', 'Fuchsia'), ('pink', 'Pink'), ('rose', 'Rose')], default='neutral', max_length=20, verbose_name='Primary Color')),
                ('neutral_color', models.CharField(choices=[('slate', 'Slate'), ('gray', 'Gray'), ('zinc', 'Zinc'), ('neutral', 'Neutral'), ('stone', 'Stone'), ('red', 'Red'), ('orange', 'Orange'), ('amber', 'Amber'), ('yellow', 'Yellow'), ('lime', 'Lime'), ('green', 'Green'), ('emerald', 'Emerald'), ('teal', 'Teal'), ('cyan', 'Cyan'), ('sky', 'Sky'), ('blue', 'Blue'), ('indigo', 'Indigo'), ('violet', 'Violet'), ('purple', 'Purple'), ('fuchsia', 'Fuchsia'), ('pink', 'Pink'), ('rose', 'Rose')], default='zinc', max_length=20, verbose_name='Neutral Color')),
                ('accent_hex', models.CharField(default='#003DFF', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color (e.g., #003DFF).', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Accent Hex')),
                ('success_hex', models.CharField(default='#16a34a', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color (e.g., #003DFF).', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Success Hex')),
                ('warning_hex', models.CharField(default='#ca8a04', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color (e.g., #003DFF).', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Warning Hex')),
                ('error_hex', models.CharField(default='#dc2626', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color (e.g., #003DFF).', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Error Hex')),
                ('info_hex', models.CharField(default='#2563eb', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color (e.g., #003DFF).', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Info Hex')),
                ('theme_preset', models.CharField(choices=[('default', 'Default'), ('minimal', 'Minimal'), ('bold', 'Bold'), ('custom', 'Custom')], default='default', max_length=20, verbose_name='Theme Preset')),
                ('theme_metadata', models.JSONField(blank=True, default=dict, verbose_name='Theme Metadata')),
                ('loyalty_enabled', models.BooleanField(default=False, verbose_name='Loyalty Enabled')),
                ('blog_enabled', models.BooleanField(default=True, verbose_name='Blog Enabled')),
                ('stripe_connect_account_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Stripe Connect Account ID')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
            },
        ),
        migrations.CreateModel(
            name='TenantDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenant.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Domain',
                'verbose_name_plural': 'Tenant Domains',
            },
        ),
    ]
