# Generated by Django 6.0.4 on 2026-04-24 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_seed_webside_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('role', models.CharField(choices=[('member', 'Member'), ('staff', 'Staff'), ('admin', 'Admin'), ('owner', 'Owner')], default='member', max_length=20, verbose_name='Role')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_memberships', to='tenant.tenant', verbose_name='Tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Tenant Membership',
                'verbose_name_plural': 'User Tenant Memberships',
                'indexes': [models.Index(fields=['tenant', 'is_active'], name='tenant_user_tenant__2a191c_idx'), models.Index(fields=['user', 'is_active'], name='tenant_user_user_id_199dc5_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'tenant'), name='unique_user_tenant_membership')],
            },
        ),
    ]
