# Generated by Django 6.0.4 on 2026-05-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_backfill_webside_memberships'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='allowed_csp_sources',
            field=models.JSONField(blank=True, default=list, help_text='Additional origins allowed by the storefront CSP (connect-src, img-src, script-src, frame-src). Each entry must start with https://, http://localhost, or wss://.', verbose_name='Allowed CSP sources'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='stripe_publishable_key',
            field=models.CharField(blank=True, default='', help_text='Per-tenant Stripe publishable key (pk_live_* or pk_test_*). This value is public by design and is safe to expose to unauthenticated callers. Leave blank to use the platform-wide key.', max_length=255, verbose_name='Stripe publishable key'),
        ),
    ]
