# Generated by Django 6.0.4 on 2026-05-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0005_add_stripe_publishable_key_and_allowed_csp_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='acs_api_key',
            field=models.CharField(blank=True, default='', help_text='ACS courier API key. Empty falls back to settings.ACS_API_KEY.', max_length=255, verbose_name='ACS API Key'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='acs_billing_code',
            field=models.CharField(blank=True, default='', help_text="ACS billing code (e.g. 'ΑΚ12345678'). Empty falls back to settings.ACS_BILLING_CODE.", max_length=64, verbose_name='ACS Billing Code'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='acs_company_id',
            field=models.CharField(blank=True, default='', help_text='ACS company identifier. Empty falls back to settings.ACS_COMPANY_ID.', max_length=64, verbose_name='ACS Company ID'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='acs_company_password',
            field=models.CharField(blank=True, default='', help_text='ACS company password. Empty falls back to settings.ACS_COMPANY_PASSWORD.', max_length=128, verbose_name='ACS Company Password'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='acs_station_origin',
            field=models.CharField(blank=True, default='', help_text='ACS origin station code (up to 8 chars). Empty falls back to settings.ACS_STATION_ORIGIN.', max_length=8, verbose_name='ACS Station Origin'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='acs_user_id',
            field=models.CharField(blank=True, default='', help_text='ACS API user identifier. Empty falls back to settings.ACS_USER_ID.', max_length=64, verbose_name='ACS User ID'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='acs_user_password',
            field=models.CharField(blank=True, default='', help_text='ACS API user password. Empty falls back to settings.ACS_USER_PASSWORD.', max_length=128, verbose_name='ACS User Password'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='box_now_client_id',
            field=models.CharField(blank=True, default='', help_text='BoxNow OAuth2 client ID. Empty falls back to settings.BOXNOW_CLIENT_ID.', max_length=64, verbose_name='BoxNow Client ID'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='box_now_client_secret',
            field=models.CharField(blank=True, default='', help_text='BoxNow OAuth2 client secret. Empty falls back to settings.BOXNOW_CLIENT_SECRET.', max_length=255, verbose_name='BoxNow Client Secret'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='box_now_notify_phone',
            field=models.CharField(blank=True, default='', help_text='Phone number for BoxNow shipment notifications. Empty falls back to settings.BOXNOW_NOTIFY_PHONE.', max_length=32, verbose_name='BoxNow Notify Phone'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='box_now_partner_id',
            field=models.CharField(blank=True, default='', help_text='BoxNow partner identifier (digits only). Used by the storefront BoxNow widget. Empty falls back to settings.BOXNOW_PARTNER_ID.', max_length=32, verbose_name='BoxNow Partner ID'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='box_now_warehouse_id',
            field=models.CharField(blank=True, default='', help_text='BoxNow warehouse identifier. Empty falls back to settings.BOXNOW_WAREHOUSE_ID.', max_length=32, verbose_name='BoxNow Warehouse ID'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='contact_email',
            field=models.EmailField(blank=True, default='', help_text='Public contact email shown in storefront footer and contact page. Empty falls back to settings.INFO_EMAIL.', max_length=254, verbose_name='Contact Email'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='from_email',
            field=models.EmailField(blank=True, default='', help_text="Sender address for outbound email from this tenant (e.g. 'no-reply@myshop.com'). Empty falls back to settings.DEFAULT_FROM_EMAIL.", max_length=254, verbose_name='From Email'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='ga_tracking_id',
            field=models.CharField(blank=True, default='', help_text='Google Analytics 4 measurement ID (G-XXXXXXXXXX) or Universal Analytics property (UA-XXXXXXXX-X). Empty → GA is disabled for this tenant.', max_length=32, verbose_name='Google Analytics Tracking ID'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='meta_capi_access_token',
            field=models.CharField(blank=True, default='', help_text='Meta Conversions API system user access token. Secret — never expose to the browser. Empty falls back to settings.META_CAPI_ACCESS_TOKEN.', max_length=255, verbose_name='Meta CAPI Access Token'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='meta_capi_dataset_id',
            field=models.CharField(blank=True, default='', help_text='Meta Conversions API dataset (pixel) ID used for server-side event deduplication. Empty falls back to settings.META_PIXEL_ID.', max_length=64, verbose_name='Meta CAPI Dataset ID'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='meta_pixel_id',
            field=models.CharField(blank=True, default='', help_text="Meta (Facebook) Pixel ID for the storefront. Digits only (e.g. '123456789012345'). Empty → browser pixel is disabled for this tenant.", max_length=64, verbose_name='Meta Pixel ID'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='socials_discord',
            field=models.URLField(blank=True, default='', help_text='Discord server invite URL. Must use https://. Empty → link hidden in storefront footer.', verbose_name='Discord URL'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='socials_facebook',
            field=models.URLField(blank=True, default='', help_text='Facebook page URL. Must use https://. Empty → link hidden in storefront footer.', verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='socials_instagram',
            field=models.URLField(blank=True, default='', help_text='Instagram profile URL. Must use https://. Empty → link hidden in storefront footer.', verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='socials_pinterest',
            field=models.URLField(blank=True, default='', help_text='Pinterest profile URL. Must use https://. Empty → link hidden in storefront footer.', verbose_name='Pinterest URL'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='socials_reddit',
            field=models.URLField(blank=True, default='', help_text='Reddit community/profile URL. Must use https://. Empty → link hidden in storefront footer.', verbose_name='Reddit URL'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='socials_tiktok',
            field=models.URLField(blank=True, default='', help_text='TikTok profile URL. Must use https://. Empty → link hidden in storefront footer.', verbose_name='TikTok URL'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='socials_twitter',
            field=models.URLField(blank=True, default='', help_text='Twitter/X profile URL. Must use https://. Empty → link hidden in storefront footer.', verbose_name='Twitter / X URL'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='socials_youtube',
            field=models.URLField(blank=True, default='', help_text='YouTube channel URL. Must use https://. Empty → link hidden in storefront footer.', verbose_name='YouTube URL'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='totp_issuer',
            field=models.CharField(blank=True, default='', help_text="Issuer name shown in authenticator apps when the user scans the TOTP QR code (e.g. 'MyShop'). Empty falls back to settings.MFA_TOTP_ISSUER.", max_length=64, verbose_name='TOTP Issuer'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='turnstile_secret_key',
            field=models.CharField(blank=True, default='', help_text='Cloudflare Turnstile secret key (server-side validation). Never expose to the browser. Empty falls back to settings.TURNSTILE_SECRET_KEY.', max_length=64, verbose_name='Turnstile Secret Key'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='turnstile_site_key',
            field=models.CharField(blank=True, default='', help_text='Cloudflare Turnstile site key (public). Shown to browsers for the CAPTCHA widget. Empty → Turnstile widget is disabled for this tenant.', max_length=64, verbose_name='Turnstile Site Key'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='viva_wallet_api_key',
            field=models.CharField(blank=True, default='', help_text='Viva Wallet API key (classic auth). Empty falls back to settings.VIVA_WALLET_API_KEY.', max_length=255, verbose_name='Viva Wallet API Key'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='viva_wallet_client_id',
            field=models.CharField(blank=True, default='', help_text='Viva Wallet OAuth2 client ID. Empty falls back to settings.VIVA_WALLET_CLIENT_ID.', max_length=255, verbose_name='Viva Wallet Client ID'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='viva_wallet_client_secret',
            field=models.CharField(blank=True, default='', help_text='Viva Wallet OAuth2 client secret. Empty falls back to settings.VIVA_WALLET_CLIENT_SECRET.', max_length=255, verbose_name='Viva Wallet Client Secret'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='viva_wallet_merchant_id',
            field=models.CharField(blank=True, default='', help_text='Viva Wallet merchant ID. Empty falls back to settings.VIVA_WALLET_MERCHANT_ID.', max_length=64, verbose_name='Viva Wallet Merchant ID'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='viva_wallet_webhook_verification_key',
            field=models.CharField(blank=True, default='', help_text='Viva Wallet webhook verification key for HMAC validation. Empty falls back to settings.VIVA_WALLET_WEBHOOK_VERIFICATION_KEY.', max_length=255, verbose_name='Viva Wallet Webhook Verification Key'),
        ),
    ]
