# Generated by Django 6.0.4 on 2026-05-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0006_add_per_tenant_config_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='suspended_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this tenant was last suspended. Set automatically by the suspend admin action. Required to be at least 24 hours in the past before the tenant can be permanently destroyed.', null=True, verbose_name='Suspended At'),
        ),
    ]
