# Generated by Django 6.0.7 on 2026-07-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0007_add_suspended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='tiktok_pixel_id',
            field=models.CharField(blank=True, default='', help_text="TikTok Pixel ID for the storefront (e.g. 'C0ABCDEFGH123'). Alphanumeric only. Empty → TikTok pixel is disabled for this tenant.", max_length=64, verbose_name='TikTok Pixel ID'),
        ),
    ]
