# Generated by Django 6.0.7 on 2026-08-17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0008_tenant_tiktok_pixel_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="chat_api_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "LLM API key for the storefront chat assistant "
                    "(served to the agent gateway only via the "
                    "internal-token-gated tenant resolve endpoint). "
                    "Each tenant brings their own key — own quota, "
                    "consent, and billing. Never expose to the "
                    "browser. Empty disables the chat assistant for "
                    "this tenant."
                ),
                max_length=255,
                verbose_name="Chat API Key",
            ),
        ),
    ]
