# Generated by Django 6.0.8 on 2026-08-17 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0009_tenant_chat_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='box_now_webhook_secret',
            field=models.CharField(blank=True, default='', help_text='HMAC secret for verifying BoxNow webhook deliveries — per-tenant, since each tenant holds their own BoxNow contract. Empty falls back to settings.BOXNOW_WEBHOOK_SECRET.', max_length=255, verbose_name='BoxNow Webhook Secret'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='stripe_secret_key',
            field=models.CharField(blank=True, default='', help_text="The tenant's OWN Stripe secret key (sk_live_*, sk_test_* or a restricted rk_* key). Secret — never expose to the browser. Empty means Stripe is unavailable for this tenant unless 'use platform account' is enabled.", max_length=255, verbose_name='Stripe secret key'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='stripe_use_platform_account',
            field=models.BooleanField(default=False, help_text='When enabled AND no per-tenant secret key is set, Stripe calls fall back to the platform-wide settings keys. Intended only for the founding tenant during migration.', verbose_name='Use platform Stripe account'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='viva_wallet_live_mode',
            field=models.BooleanField(blank=True, default=None, help_text="Whether this tenant's Viva credentials are live (demo otherwise). Unset falls back to settings.VIVA_WALLET_LIVE_MODE.", null=True, verbose_name='Viva Wallet Live Mode'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='viva_wallet_source_code',
            field=models.CharField(blank=True, default='', help_text='Viva Wallet Smart Checkout payment source code — a per-merchant identifier, so each tenant needs their own. Empty falls back to settings.VIVA_WALLET_SOURCE_CODE.', max_length=32, verbose_name='Viva Wallet Source Code'),
        ),
    ]
