# Generated by Django 6.0.8 on 2026-08-17 23:41

import tenant.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0010_tenant_box_now_webhook_secret_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='theme_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Per-token theme overrides on top of the preset. Legal keys: radius, fontSans, container, colors.primaryScale / colors.neutralScale (shade → #RRGGBB). Anything else is rejected — the storefront token compiler ignores invalid metadata entirely.', validators=[tenant.validators.validate_theme_metadata], verbose_name='Theme Metadata'),
        ),
    ]
