# Generated by Django 6.0.8 on 2026-08-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0011_alter_tenant_theme_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='acp_bearer_token',
            field=models.CharField(blank=True, default='', help_text="Bearer token the agent platform uses on this tenant's /acp/* checkout surface (served to the agent gateway only via the internal-token-gated tenant resolve endpoint). Per-tenant — a token minted for one store must never drive another store's checkout. Empty disables ACP for this tenant.", max_length=255, verbose_name='ACP Bearer Token'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='agent_stripe_delegated_enabled',
            field=models.BooleanField(default=False, help_text="Allow AI-agent platforms to complete Stripe payments server-side with SharedPaymentTokens on this store. Requires the tenant's Stripe account to be enrolled in Stripe Agentic Commerce.", verbose_name='Agent Stripe Delegated Payments'),
        ),
    ]
