# Generated by Django 6.0.8 on 2026-08-18 10:11

import django_tenants.postgresql_backend.base
import tenant.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0012_tenant_acp_bearer_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='schema_name',
            field=models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name, tenant.validators.validate_reserved_schema_name]),
        ),
    ]
