# Generated by Django 6.0.8 on 2026-08-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0013_alter_tenant_schema_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='stripe_use_platform_account',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='turnstile_secret_key',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='turnstile_site_key',
        ),
        migrations.AlterField(
            model_name='tenant',
            name='stripe_publishable_key',
            field=models.CharField(blank=True, default='', help_text='Per-tenant Stripe publishable key (pk_live_* or pk_test_*). This value is public by design and is safe to expose to unauthenticated callers. Leave blank if Stripe is not configured for this tenant.', max_length=255, verbose_name='Stripe publishable key'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='stripe_secret_key',
            field=models.CharField(blank=True, default='', help_text="The tenant's OWN Stripe secret key (sk_live_*, sk_test_* or a restricted rk_* key). Secret — never expose to the browser. Empty means Stripe is unavailable for this tenant — there is no platform-wide fallback.", max_length=255, verbose_name='Stripe secret key'),
        ),
    ]
