# Generated by Django 6.0.8 on 2026-08-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0015_drop_customer_memberships"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="viva_wallet_live_mode",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Whether this tenant's Viva credentials are live (demo otherwise). There is NO settings fallback: unset is read as demo, so a live merchant MUST set this explicitly or real payments are sent to the Viva demo environment.",
                null=True,
                verbose_name="Viva Wallet Live Mode",
            ),
        ),
    ]
