# Generated by Django 6.0.8 on 2026-08-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0017_platformstafftoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='billing_notice_stage',
            field=models.PositiveSmallIntegerField(default=0, help_text='Highest dunning stage already notified for the current term (0 none, 1 expiry warning, 2 expired, 3 suspended).', verbose_name='Billing Notice Stage'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='billing_notice_term',
            field=models.DateField(blank=True, help_text='The paid_until value the notice stage refers to. A mismatch with the current paid_until means the stage is stale and resets to 0 on the next billing run.', null=True, verbose_name='Billing Notice Term'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='suspended_reason',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('billing', 'Billing')], default='', help_text="Why this tenant is suspended: 'manual' for operator action, 'billing' for the automated dunning task. Empty when not suspended. Renewal-driven auto-reactivation applies to 'billing' suspensions only.", max_length=20, verbose_name='Suspended Reason'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='paid_until',
            field=models.DateField(blank=True, help_text='Last day (inclusive) of the current term — trial or paid. Empty means the term never expires (legacy rows, the platform row). The daily billing task warns, dunns, and optionally suspends from this date.', null=True, verbose_name='Paid Until'),
        ),
    ]
