# Generated by Django 6.0.8 on 2026-08-24 10:14

import django.core.validators
import django.db.models.deletion
import django_tenants.postgresql_backend.base
import simple_history.models
import tenant.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0018_tenant_billing_notice_stage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTenant',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Updated At')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('schema_name', models.CharField(db_index=True, max_length=63, validators=[django_tenants.postgresql_backend.base._check_schema_name, tenant.validators.validate_reserved_schema_name])),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('owner_email', models.EmailField(max_length=254, verbose_name='Owner Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('suspended_at', models.DateTimeField(blank=True, help_text='Timestamp when this tenant was last suspended. Set automatically by the suspend admin action. Required to be at least 24 hours in the past before the tenant can be permanently destroyed.', null=True, verbose_name='Suspended At')),
                ('suspended_reason', models.CharField(blank=True, choices=[('manual', 'Manual'), ('billing', 'Billing')], default='', help_text="Why this tenant is suspended: 'manual' for operator action, 'billing' for the automated dunning task. Empty when not suspended. Renewal-driven auto-reactivation applies to 'billing' suspensions only.", max_length=20, verbose_name='Suspended Reason')),
                ('plan', models.CharField(choices=[('trial', 'Trial'), ('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='trial', max_length=20, verbose_name='Plan')),
                ('paid_until', models.DateField(blank=True, help_text='Last day (inclusive) of the current term — trial or paid. Empty means the term never expires (legacy rows, the platform row). The daily billing task warns, dunns, and optionally suspends from this date.', null=True, verbose_name='Paid Until')),
                ('billing_notice_stage', models.PositiveSmallIntegerField(default=0, help_text='Highest dunning stage already notified for the current term (0 none, 1 expiry warning, 2 expired, 3 suspended).', verbose_name='Billing Notice Stage')),
                ('billing_notice_term', models.DateField(blank=True, help_text='The paid_until value the notice stage refers to. A mismatch with the current paid_until means the stage is stale and resets to 0 on the next billing run.', null=True, verbose_name='Billing Notice Term')),
                ('store_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Store Name')),
                ('store_description', models.TextField(blank=True, default='', verbose_name='Store Description')),
                ('default_locale', models.CharField(default='el', max_length=10, verbose_name='Default Locale')),
                ('default_currency', models.CharField(default='EUR', max_length=3, verbose_name='Default Currency')),
                ('logo_light_url', models.URLField(blank=True, default='', verbose_name='Logo (Light)')),
                ('logo_dark_url', models.URLField(blank=True, default='', verbose_name='Logo (Dark)')),
                ('favicon_url', models.URLField(blank=True, default='', verbose_name='Favicon URL')),
                ('primary_color', models.CharField(choices=[('slate', 'Slate'), ('gray', 'Gray'), ('zinc', 'Zinc'), ('neutral', 'Neutral'), ('stone', 'Stone'), ('red', 'Red'), ('orange', 'Orange'), ('amber', 'Amber'), ('yellow', 'Yellow'), ('lime', 'Lime'), ('green', 'Green'), ('emerald', 'Emerald'), ('teal', 'Teal'), ('cyan', 'Cyan'), ('sky', 'Sky'), ('blue', 'Blue'), ('indigo', 'Indigo'), ('violet', 'Violet'), ('purple', 'Purple'), ('fuchsia', 'Fuchsia'), ('pink', 'Pink'), ('rose', 'Rose')], default='neutral', max_length=20, verbose_name='Primary Color')),
                ('neutral_color', models.CharField(choices=[('slate', 'Slate'), ('gray', 'Gray'), ('zinc', 'Zinc'), ('neutral', 'Neutral'), ('stone', 'Stone'), ('red', 'Red'), ('orange', 'Orange'), ('amber', 'Amber'), ('yellow', 'Yellow'), ('lime', 'Lime'), ('green', 'Green'), ('emerald', 'Emerald'), ('teal', 'Teal'), ('cyan', 'Cyan'), ('sky', 'Sky'), ('blue', 'Blue'), ('indigo', 'Indigo'), ('violet', 'Violet'), ('purple', 'Purple'), ('fuchsia', 'Fuchsia'), ('pink', 'Pink'), ('rose', 'Rose')], default='zinc', max_length=20, verbose_name='Neutral Color')),
                ('accent_hex', models.CharField(default='#003DFF', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color (e.g., #003DFF).', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Accent Hex')),
                ('success_hex', models.CharField(default='#16a34a', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color (e.g., #003DFF).', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Success Hex')),
                ('warning_hex', models.CharField(default='#ca8a04', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color (e.g., #003DFF).', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Warning Hex')),
                ('error_hex', models.CharField(default='#dc2626', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color (e.g., #003DFF).', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Error Hex')),
                ('info_hex', models.CharField(default='#2563eb', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color (e.g., #003DFF).', regex='^#[0-9a-fA-F]{6}$')], verbose_name='Info Hex')),
                ('theme_preset', models.CharField(choices=[('default', 'Default'), ('minimal', 'Minimal'), ('bold', 'Bold'), ('custom', 'Custom')], default='default', max_length=20, verbose_name='Theme Preset')),
                ('theme_metadata', models.JSONField(blank=True, default=dict, help_text='Per-token theme overrides on top of the preset. Legal keys: radius, fontSans, container, colors.primaryScale / colors.neutralScale (shade → #RRGGBB). Anything else is rejected — the storefront token compiler ignores invalid metadata entirely.', validators=[tenant.validators.validate_theme_metadata], verbose_name='Theme Metadata')),
                ('loyalty_enabled', models.BooleanField(default=False, verbose_name='Loyalty Enabled')),
                ('blog_enabled', models.BooleanField(default=True, verbose_name='Blog Enabled')),
                ('stripe_connect_account_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Stripe Connect Account ID')),
                ('stripe_publishable_key', models.CharField(blank=True, default='', help_text='Per-tenant Stripe publishable key (pk_live_* or pk_test_*). This value is public by design and is safe to expose to unauthenticated callers. Leave blank if Stripe is not configured for this tenant.', max_length=255, verbose_name='Stripe publishable key')),
                ('allowed_csp_sources', models.JSONField(blank=True, default=list, help_text='Additional origins allowed by the storefront CSP (connect-src, img-src, script-src, frame-src). Each entry must start with https://, http://localhost, or wss://.', verbose_name='Allowed CSP sources')),
                ('meta_pixel_id', models.CharField(blank=True, default='', help_text="Meta (Facebook) Pixel ID for the storefront. Digits only (e.g. '123456789012345'). Empty → browser pixel is disabled for this tenant.", max_length=64, verbose_name='Meta Pixel ID')),
                ('tiktok_pixel_id', models.CharField(blank=True, default='', help_text="TikTok Pixel ID for the storefront (e.g. 'C0ABCDEFGH123'). Alphanumeric only. Empty → TikTok pixel is disabled for this tenant.", max_length=64, verbose_name='TikTok Pixel ID')),
                ('ga_tracking_id', models.CharField(blank=True, default='', help_text='Google Analytics 4 measurement ID (G-XXXXXXXXXX) or Universal Analytics property (UA-XXXXXXXX-X). Empty → GA is disabled for this tenant.', max_length=32, verbose_name='Google Analytics Tracking ID')),
                ('totp_issuer', models.CharField(blank=True, default='', help_text="Issuer name shown in authenticator apps when the user scans the TOTP QR code (e.g. 'MyShop'). Empty falls back to settings.MFA_TOTP_ISSUER.", max_length=64, verbose_name='TOTP Issuer')),
                ('socials_discord', models.URLField(blank=True, default='', help_text='Discord server invite URL. Must use https://. Empty → link hidden in storefront footer.', verbose_name='Discord URL')),
                ('socials_facebook', models.URLField(blank=True, default='', help_text='Facebook page URL. Must use https://. Empty → link hidden in storefront footer.', verbose_name='Facebook URL')),
                ('socials_instagram', models.URLField(blank=True, default='', help_text='Instagram profile URL. Must use https://. Empty → link hidden in storefront footer.', verbose_name='Instagram URL')),
                ('socials_pinterest', models.URLField(blank=True, default='', help_text='Pinterest profile URL. Must use https://. Empty → link hidden in storefront footer.', verbose_name='Pinterest URL')),
                ('socials_reddit', models.URLField(blank=True, default='', help_text='Reddit community/profile URL. Must use https://. Empty → link hidden in storefront footer.', verbose_name='Reddit URL')),
                ('socials_tiktok', models.URLField(blank=True, default='', help_text='TikTok profile URL. Must use https://. Empty → link hidden in storefront footer.', verbose_name='TikTok URL')),
                ('socials_twitter', models.URLField(blank=True, default='', help_text='Twitter/X profile URL. Must use https://. Empty → link hidden in storefront footer.', verbose_name='Twitter / X URL')),
                ('socials_youtube', models.URLField(blank=True, default='', help_text='YouTube channel URL. Must use https://. Empty → link hidden in storefront footer.', verbose_name='YouTube URL')),
                ('box_now_partner_id', models.CharField(blank=True, default='', help_text='BoxNow partner identifier (digits only). Used by the storefront BoxNow widget. Empty falls back to settings.BOXNOW_PARTNER_ID.', max_length=32, verbose_name='BoxNow Partner ID')),
                ('from_email', models.EmailField(blank=True, default='', help_text="Sender address for outbound email from this tenant (e.g. 'no-reply@myshop.com'). Empty falls back to settings.DEFAULT_FROM_EMAIL.", max_length=254, verbose_name='From Email')),
                ('contact_email', models.EmailField(blank=True, default='', help_text='Public contact email shown in storefront footer and contact page. Empty falls back to settings.INFO_EMAIL.', max_length=254, verbose_name='Contact Email')),
                ('meta_capi_dataset_id', models.CharField(blank=True, default='', help_text='Meta Conversions API dataset (pixel) ID used for server-side event deduplication. Empty falls back to settings.META_PIXEL_ID.', max_length=64, verbose_name='Meta CAPI Dataset ID')),
                ('viva_wallet_merchant_id', models.CharField(blank=True, default='', help_text='Viva Wallet merchant ID. Empty falls back to settings.VIVA_WALLET_MERCHANT_ID.', max_length=64, verbose_name='Viva Wallet Merchant ID')),
                ('viva_wallet_client_id', models.CharField(blank=True, default='', help_text='Viva Wallet OAuth2 client ID. Empty falls back to settings.VIVA_WALLET_CLIENT_ID.', max_length=255, verbose_name='Viva Wallet Client ID')),
                ('viva_wallet_source_code', models.CharField(blank=True, default='', help_text='Viva Wallet Smart Checkout payment source code — a per-merchant identifier, so each tenant needs their own. Empty falls back to settings.VIVA_WALLET_SOURCE_CODE.', max_length=32, verbose_name='Viva Wallet Source Code')),
                ('viva_wallet_live_mode', models.BooleanField(blank=True, default=None, help_text="Whether this tenant's Viva credentials are live (demo otherwise). There is NO settings fallback: unset is read as demo, so a live merchant MUST set this explicitly or real payments are sent to the Viva demo environment.", null=True, verbose_name='Viva Wallet Live Mode')),
                ('acs_company_id', models.CharField(blank=True, default='', help_text='ACS company identifier. Empty falls back to settings.ACS_COMPANY_ID.', max_length=64, verbose_name='ACS Company ID')),
                ('acs_user_id', models.CharField(blank=True, default='', help_text='ACS API user identifier. Empty falls back to settings.ACS_USER_ID.', max_length=64, verbose_name='ACS User ID')),
                ('acs_billing_code', models.CharField(blank=True, default='', help_text="ACS billing code (e.g. 'ΑΚ12345678'). Empty falls back to settings.ACS_BILLING_CODE.", max_length=64, verbose_name='ACS Billing Code')),
                ('acs_station_origin', models.CharField(blank=True, default='', help_text='ACS origin station code (up to 8 chars). Empty falls back to settings.ACS_STATION_ORIGIN.', max_length=8, verbose_name='ACS Station Origin')),
                ('box_now_client_id', models.CharField(blank=True, default='', help_text='BoxNow OAuth2 client ID. Empty falls back to settings.BOXNOW_CLIENT_ID.', max_length=64, verbose_name='BoxNow Client ID')),
                ('box_now_warehouse_id', models.CharField(blank=True, default='', help_text='BoxNow warehouse identifier. Empty falls back to settings.BOXNOW_WAREHOUSE_ID.', max_length=32, verbose_name='BoxNow Warehouse ID')),
                ('box_now_notify_phone', models.CharField(blank=True, default='', help_text='Phone number for BoxNow shipment notifications. Empty falls back to settings.BOXNOW_NOTIFY_PHONE.', max_length=32, verbose_name='BoxNow Notify Phone')),
                ('agent_stripe_delegated_enabled', models.BooleanField(default=False, help_text="Allow AI-agent platforms to complete Stripe payments server-side with SharedPaymentTokens on this store. Requires the tenant's Stripe account to be enrolled in Stripe Agentic Commerce.", verbose_name='Agent Stripe Delegated Payments')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Tenant',
                'verbose_name_plural': 'historical Tenants',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
