# Generated by Django 6.0.8 on 2026-08-24 17:39

import django_tenants.postgresql_backend.base
import tenant.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0019_historicaltenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltenant',
            name='schema_name',
            field=models.CharField(db_index=True, max_length=63, validators=[django_tenants.postgresql_backend.base._check_schema_name, tenant.validators.validate_reserved_schema_name], verbose_name='Schema name'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='schema_name',
            field=models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name, tenant.validators.validate_reserved_schema_name], verbose_name='Schema name'),
        ),
    ]
