# Generated by Django 6.0.8 on 2026-08-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0020_alter_historicaltenant_schema_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltenant',
            name='gift_cards_enabled',
            field=models.BooleanField(default=False, verbose_name='Gift Cards Enabled'),
        ),
        migrations.AddField(
            model_name='historicaltenant',
            name='promotions_enabled',
            field=models.BooleanField(default=False, verbose_name='Promotions Enabled'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='gift_cards_enabled',
            field=models.BooleanField(default=False, verbose_name='Gift Cards Enabled'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='promotions_enabled',
            field=models.BooleanField(default=False, verbose_name='Promotions Enabled'),
        ),
    ]
