# Generated by Django 6.0.8 on 2026-08-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0021_historicaltenant_gift_cards_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltenant',
            name='agent_commerce_enabled',
            field=models.BooleanField(default=True, verbose_name='Agent Commerce Enabled'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='agent_commerce_enabled',
            field=models.BooleanField(default=True, verbose_name='Agent Commerce Enabled'),
        ),
    ]
