# Generated by Django 6.0.8 on 2026-08-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0022_historicaltenant_agent_commerce_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltenant',
            name='from_email',
            field=models.EmailField(blank=True, default='', help_text='Reserved for a future per-tenant SMTP transport — NOT currently used. All mail is sent from the platform address with your store name as the display name, which is what keeps it DMARC-aligned. Set Contact Email instead: that is the reply-to address customers actually reach you on.', max_length=254, verbose_name='From Email'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='from_email',
            field=models.EmailField(blank=True, default='', help_text='Reserved for a future per-tenant SMTP transport — NOT currently used. All mail is sent from the platform address with your store name as the display name, which is what keeps it DMARC-aligned. Set Contact Email instead: that is the reply-to address customers actually reach you on.', max_length=254, verbose_name='From Email'),
        ),
    ]
