# Generated by Django 6.0.8 on 2026-08-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0023_tenant_from_email_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('schema_name', models.CharField(help_text='Schema of the destroyed tenant. Kept as a plain value, not a foreign key — the Tenant row it named no longer exists.', max_length=63, unique=True, verbose_name='Schema Name')),
                ('tenant_name', models.CharField(help_text='Store name at the time of destruction, for the audit trail.', max_length=255, verbose_name='Tenant Name')),
                ('destroyed_at', models.DateTimeField(help_text='When the schema and non-retained data were erased.', verbose_name='Destroyed At')),
                ('destroyed_by', models.CharField(blank=True, default='', help_text='Operator identity recorded for accountability (art. 5(2)).', max_length=255, verbose_name='Destroyed By')),
                ('data_exported', models.BooleanField(default=False, help_text="Whether the controller took the 'return' half of the art. 28(3)(g) choice before erasure.", verbose_name='Data Exported')),
                ('retained_invoice_path', models.CharField(blank=True, default='', help_text="Private-media directory still holding this store's invoices. Empty when the store issued none and nothing was retained.", max_length=512, verbose_name='Retained Invoice Path')),
                ('retention_until', models.DateField(blank=True, help_text="Date the statutory retention expires, derived from the LAST invoice's tax year plus TENANT_INVOICE_RETENTION_YEARS. Null when nothing is retained.", null=True, verbose_name='Retention Until')),
                ('retention_basis', models.CharField(blank=True, default='', help_text='The legal obligation the retention rests on.', max_length=255, verbose_name='Retention Basis')),
                ('purged_at', models.DateTimeField(blank=True, help_text='When the retained records were finally erased. Null while retention is still running.', null=True, verbose_name='Purged At')),
            ],
            options={
                'verbose_name': 'Tenant Archive',
                'verbose_name_plural': 'Tenant Archives',
                'ordering': ['-destroyed_at'],
                'indexes': [models.Index(fields=['retention_until'], name='tenant_arch_ret_ix'), models.Index(fields=['purged_at'], name='tenant_arch_purged_ix')],
            },
        ),
    ]
