# Generated by Django 6.0.8 on 2026-08-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0024_tenant_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltenant',
            name='agent_hosted_payment_enabled',
            field=models.BooleanField(default=True, help_text='Let AI-agent platforms choose an online payment method, placing the order and handing the buyer the payment page. When off, agents can only complete with methods they can settle themselves (e.g. cash on delivery) and card buyers are handed off to the storefront checkout.', verbose_name='Agent Hosted Payment Selection'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='agent_hosted_payment_enabled',
            field=models.BooleanField(default=True, help_text='Let AI-agent platforms choose an online payment method, placing the order and handing the buyer the payment page. When off, agents can only complete with methods they can settle themselves (e.g. cash on delivery) and card buyers are handed off to the storefront checkout.', verbose_name='Agent Hosted Payment Selection'),
        ),
    ]
