# Generated by Django 6.0.8 on 2026-08-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0025_historicaltenant_agent_hosted_payment_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltenant',
            name='b2b_enabled',
            field=models.BooleanField(default=False, verbose_name='B2B Enabled'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='b2b_enabled',
            field=models.BooleanField(default=False, verbose_name='B2B Enabled'),
        ),
    ]
