# Generated by Django 6.0.8 on 2026-09-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0026_historicaltenant_b2b_enabled_tenant_b2b_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltenant',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='This tenant is a disposable showcase, not a real merchant. Allows manage.py seed_demo_store to overwrite its catalogue, layouts and navigation without --force. Never set this on a store that takes real orders.', verbose_name='Demo Store'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='This tenant is a disposable showcase, not a real merchant. Allows manage.py seed_demo_store to overwrite its catalogue, layouts and navigation without --force. Never set this on a store that takes real orders.', verbose_name='Demo Store'),
        ),
    ]
