# Generated by Django 6.0.8 on 2026-09-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0027_historicaltenant_is_demo_tenant_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltenant',
            name='is_protected',
            field=models.BooleanField(default=False, help_text='Never suspend, reactivate or destroy this tenant through admin actions, the platform API or automation.', verbose_name='Protected'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_protected',
            field=models.BooleanField(default=False, help_text='Never suspend, reactivate or destroy this tenant through admin actions, the platform API or automation.', verbose_name='Protected'),
        ),
    ]
