# Generated by Django 6.0.8 on 2026-09-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0029_mark_protected_tenants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltenant',
            name='acs_billing_code',
            field=models.CharField(blank=True, default='', help_text="ACS billing code (e.g. 'ΑΚ12345678'). No platform fallback — empty disables ACS.", max_length=64, verbose_name='ACS Billing Code'),
        ),
        migrations.AlterField(
            model_name='historicaltenant',
            name='acs_company_id',
            field=models.CharField(blank=True, default='', help_text='ACS company identifier. No platform fallback — empty disables ACS.', max_length=64, verbose_name='ACS Company ID'),
        ),
        migrations.AlterField(
            model_name='historicaltenant',
            name='acs_station_origin',
            field=models.CharField(blank=True, default='', help_text='ACS origin station code (up to 8 chars). No platform fallback — empty disables ACS.', max_length=8, verbose_name='ACS Station Origin'),
        ),
        migrations.AlterField(
            model_name='historicaltenant',
            name='acs_user_id',
            field=models.CharField(blank=True, default='', help_text='ACS API user identifier. No platform fallback — empty disables ACS.', max_length=64, verbose_name='ACS User ID'),
        ),
        migrations.AlterField(
            model_name='historicaltenant',
            name='box_now_client_id',
            field=models.CharField(blank=True, default='', help_text='BoxNow OAuth2 client ID. No platform fallback — empty disables BoxNow.', max_length=64, verbose_name='BoxNow Client ID'),
        ),
        migrations.AlterField(
            model_name='historicaltenant',
            name='box_now_notify_phone',
            field=models.CharField(blank=True, default='', help_text='Phone number for BoxNow shipment notifications. No platform fallback — empty disables BoxNow.', max_length=32, verbose_name='BoxNow Notify Phone'),
        ),
        migrations.AlterField(
            model_name='historicaltenant',
            name='box_now_partner_id',
            field=models.CharField(blank=True, default='', help_text='BoxNow partner identifier (digits only). Used by the storefront BoxNow widget. No platform fallback — empty disables BoxNow.', max_length=32, verbose_name='BoxNow Partner ID'),
        ),
        migrations.AlterField(
            model_name='historicaltenant',
            name='box_now_warehouse_id',
            field=models.CharField(blank=True, default='', help_text='BoxNow warehouse identifier. No platform fallback — empty disables BoxNow.', max_length=32, verbose_name='BoxNow Warehouse ID'),
        ),
        migrations.AlterField(
            model_name='historicaltenant',
            name='meta_capi_dataset_id',
            field=models.CharField(blank=True, default='', help_text='Meta Conversions API dataset (pixel) ID used for server-side event deduplication. No platform fallback — empty disables Meta CAPI.', max_length=64, verbose_name='Meta CAPI Dataset ID'),
        ),
        migrations.AlterField(
            model_name='historicaltenant',
            name='viva_wallet_client_id',
            field=models.CharField(blank=True, default='', help_text='Viva Wallet OAuth2 client ID. No platform fallback — empty disables Viva Wallet.', max_length=255, verbose_name='Viva Wallet Client ID'),
        ),
        migrations.AlterField(
            model_name='historicaltenant',
            name='viva_wallet_merchant_id',
            field=models.CharField(blank=True, default='', help_text='Viva Wallet merchant ID. No platform fallback — empty disables Viva Wallet.', max_length=64, verbose_name='Viva Wallet Merchant ID'),
        ),
        migrations.AlterField(
            model_name='historicaltenant',
            name='viva_wallet_source_code',
            field=models.CharField(blank=True, default='', help_text='Viva Wallet Smart Checkout payment source code — a per-merchant identifier, so each tenant needs their own. No platform fallback — empty disables Viva Wallet.', max_length=32, verbose_name='Viva Wallet Source Code'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='acs_api_key',
            field=models.CharField(blank=True, default='', help_text='ACS courier API key. No platform fallback — empty disables ACS.', max_length=255, verbose_name='ACS API Key'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='acs_billing_code',
            field=models.CharField(blank=True, default='', help_text="ACS billing code (e.g. 'ΑΚ12345678'). No platform fallback — empty disables ACS.", max_length=64, verbose_name='ACS Billing Code'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='acs_company_id',
            field=models.CharField(blank=True, default='', help_text='ACS company identifier. No platform fallback — empty disables ACS.', max_length=64, verbose_name='ACS Company ID'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='acs_company_password',
            field=models.CharField(blank=True, default='', help_text='ACS company password. No platform fallback — empty disables ACS.', max_length=128, verbose_name='ACS Company Password'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='acs_station_origin',
            field=models.CharField(blank=True, default='', help_text='ACS origin station code (up to 8 chars). No platform fallback — empty disables ACS.', max_length=8, verbose_name='ACS Station Origin'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='acs_user_id',
            field=models.CharField(blank=True, default='', help_text='ACS API user identifier. No platform fallback — empty disables ACS.', max_length=64, verbose_name='ACS User ID'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='acs_user_password',
            field=models.CharField(blank=True, default='', help_text='ACS API user password. No platform fallback — empty disables ACS.', max_length=128, verbose_name='ACS User Password'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='box_now_client_id',
            field=models.CharField(blank=True, default='', help_text='BoxNow OAuth2 client ID. No platform fallback — empty disables BoxNow.', max_length=64, verbose_name='BoxNow Client ID'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='box_now_client_secret',
            field=models.CharField(blank=True, default='', help_text='BoxNow OAuth2 client secret. No platform fallback — empty disables BoxNow.', max_length=255, verbose_name='BoxNow Client Secret'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='box_now_notify_phone',
            field=models.CharField(blank=True, default='', help_text='Phone number for BoxNow shipment notifications. No platform fallback — empty disables BoxNow.', max_length=32, verbose_name='BoxNow Notify Phone'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='box_now_partner_id',
            field=models.CharField(blank=True, default='', help_text='BoxNow partner identifier (digits only). Used by the storefront BoxNow widget. No platform fallback — empty disables BoxNow.', max_length=32, verbose_name='BoxNow Partner ID'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='box_now_warehouse_id',
            field=models.CharField(blank=True, default='', help_text='BoxNow warehouse identifier. No platform fallback — empty disables BoxNow.', max_length=32, verbose_name='BoxNow Warehouse ID'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='box_now_webhook_secret',
            field=models.CharField(blank=True, default='', help_text='HMAC secret for verifying BoxNow webhook deliveries — per-tenant, since each tenant holds their own BoxNow contract. No platform fallback — empty disables BoxNow.', max_length=255, verbose_name='BoxNow Webhook Secret'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='meta_capi_access_token',
            field=models.CharField(blank=True, default='', help_text='Meta Conversions API system user access token. Secret — never expose to the browser. No platform fallback — empty disables Meta CAPI.', max_length=255, verbose_name='Meta CAPI Access Token'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='meta_capi_dataset_id',
            field=models.CharField(blank=True, default='', help_text='Meta Conversions API dataset (pixel) ID used for server-side event deduplication. No platform fallback — empty disables Meta CAPI.', max_length=64, verbose_name='Meta CAPI Dataset ID'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='viva_wallet_api_key',
            field=models.CharField(blank=True, default='', help_text='Viva Wallet API key (classic auth). No platform fallback — empty disables Viva Wallet.', max_length=255, verbose_name='Viva Wallet API Key'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='viva_wallet_client_id',
            field=models.CharField(blank=True, default='', help_text='Viva Wallet OAuth2 client ID. No platform fallback — empty disables Viva Wallet.', max_length=255, verbose_name='Viva Wallet Client ID'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='viva_wallet_client_secret',
            field=models.CharField(blank=True, default='', help_text='Viva Wallet OAuth2 client secret. No platform fallback — empty disables Viva Wallet.', max_length=255, verbose_name='Viva Wallet Client Secret'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='viva_wallet_merchant_id',
            field=models.CharField(blank=True, default='', help_text='Viva Wallet merchant ID. No platform fallback — empty disables Viva Wallet.', max_length=64, verbose_name='Viva Wallet Merchant ID'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='viva_wallet_source_code',
            field=models.CharField(blank=True, default='', help_text='Viva Wallet Smart Checkout payment source code — a per-merchant identifier, so each tenant needs their own. No platform fallback — empty disables Viva Wallet.', max_length=32, verbose_name='Viva Wallet Source Code'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='viva_wallet_webhook_verification_key',
            field=models.CharField(blank=True, default='', help_text='Viva Wallet webhook verification key for HMAC validation. No platform fallback — empty disables Viva Wallet.', max_length=255, verbose_name='Viva Wallet Webhook Verification Key'),
        ),
    ]
