# Generated by Django 6.0.8 on 2026-09-07 05:35

import tenant.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0030_alter_historicaltenant_acs_billing_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltenant',
            name='available_locales',
            field=models.JSONField(blank=True, default=list, help_text='Locales this store serves, e.g. ["el", "en"]. Empty means single-language on the default locale — the storefront then 404s every other locale prefix and hides it from the language switcher, hreflang set and sitemap. Must contain default_locale when non-empty.', validators=[tenant.validators.validate_available_locales], verbose_name='Available Locales'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='available_locales',
            field=models.JSONField(blank=True, default=list, help_text='Locales this store serves, e.g. ["el", "en"]. Empty means single-language on the default locale — the storefront then 404s every other locale prefix and hides it from the language switcher, hreflang set and sitemap. Must contain default_locale when non-empty.', validators=[tenant.validators.validate_available_locales], verbose_name='Available Locales'),
        ),
    ]
