# Generated by Django 6.0.8 on 2026-09-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0031_historicaltenant_available_locales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltenant',
            name='socials_linkedin',
            field=models.URLField(blank=True, default='', help_text='LinkedIn company page URL. Must use https://. Empty → link hidden in storefront footer.', verbose_name='LinkedIn URL'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='socials_linkedin',
            field=models.URLField(blank=True, default='', help_text='LinkedIn company page URL. Must use https://. Empty → link hidden in storefront footer.', verbose_name='LinkedIn URL'),
        ),
    ]
