# Generated by Django 6.0.8 on 2026-09-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0032_historicaltenant_socials_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltenant',
            name='openai_pixel_id',
            field=models.CharField(blank=True, default='', help_text="OpenAI / ChatGPT Ads conversion pixel ID (e.g. '8MktrqpXN1MRdD2NUfkXmU'). Alphanumeric only. Empty → the ChatGPT Ads pixel is disabled for this tenant, and its origin is left out of the CSP.", max_length=64, verbose_name='ChatGPT Ads Pixel ID'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='openai_pixel_id',
            field=models.CharField(blank=True, default='', help_text="OpenAI / ChatGPT Ads conversion pixel ID (e.g. '8MktrqpXN1MRdD2NUfkXmU'). Alphanumeric only. Empty → the ChatGPT Ads pixel is disabled for this tenant, and its origin is left out of the CSP.", max_length=64, verbose_name='ChatGPT Ads Pixel ID'),
        ),
    ]
