# Generated by Django 6.0.8 on 2026-09-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0033_historicaltenant_openai_pixel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltenant',
            name='google_site_verification',
            field=models.CharField(blank=True, db_default='', default='', help_text='Google Search Console verification token (the content of the google-site-verification meta tag). Empty → not emitted.', max_length=128, verbose_name='Google site verification'),
        ),
        migrations.AddField(
            model_name='historicaltenant',
            name='is_platform_storefront',
            field=models.BooleanField(db_default=False, default=False, help_text="This store is the platform's own storefront: it renders the brand assets bundled in the storefront image. At most one tenant may carry this.", verbose_name='Platform storefront'),
        ),
        migrations.AddField(
            model_name='historicaltenant',
            name='pinterest_domain_verify',
            field=models.CharField(blank=True, db_default='', default='', help_text='Pinterest domain verification token (the content of the p:domain_verify meta tag). Empty → not emitted.', max_length=128, verbose_name='Pinterest domain verification'),
        ),
        migrations.AddField(
            model_name='historicaltenant',
            name='seo_author',
            field=models.CharField(blank=True, db_default='', default='', help_text="Rendered as the storefront's author/creator/publisher meta tags. Empty → the tags are not emitted.", max_length=120, verbose_name='SEO author'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='google_site_verification',
            field=models.CharField(blank=True, db_default='', default='', help_text='Google Search Console verification token (the content of the google-site-verification meta tag). Empty → not emitted.', max_length=128, verbose_name='Google site verification'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_platform_storefront',
            field=models.BooleanField(db_default=False, default=False, help_text="This store is the platform's own storefront: it renders the brand assets bundled in the storefront image. At most one tenant may carry this.", verbose_name='Platform storefront'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='pinterest_domain_verify',
            field=models.CharField(blank=True, db_default='', default='', help_text='Pinterest domain verification token (the content of the p:domain_verify meta tag). Empty → not emitted.', max_length=128, verbose_name='Pinterest domain verification'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='seo_author',
            field=models.CharField(blank=True, db_default='', default='', help_text="Rendered as the storefront's author/creator/publisher meta tags. Empty → the tags are not emitted.", max_length=120, verbose_name='SEO author'),
        ),
        migrations.AddConstraint(
            model_name='tenant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_platform_storefront', True)), fields=('is_platform_storefront',), name='tenant_single_platform_storefront'),
        ),
    ]
