# Generated by Django 6.0.8 on 2026-09-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0035_mark_platform_storefront'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltenant',
            name='contact_email',
            field=models.EmailField(blank=True, default='', help_text='Public contact email shown in storefront footer and contact page, and the inbox for contact-form submissions. Empty means the store has no contact address: submissions are not delivered and outbound mail carries no Reply-To.', max_length=254, verbose_name='Contact Email'),
        ),
        migrations.AlterField(
            model_name='historicaltenant',
            name='totp_issuer',
            field=models.CharField(blank=True, default='', help_text="Issuer name shown in authenticator apps when the user scans the TOTP QR code (e.g. 'MyShop'). Empty uses the store name.", max_length=64, verbose_name='TOTP Issuer'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='contact_email',
            field=models.EmailField(blank=True, default='', help_text='Public contact email shown in storefront footer and contact page, and the inbox for contact-form submissions. Empty means the store has no contact address: submissions are not delivered and outbound mail carries no Reply-To.', max_length=254, verbose_name='Contact Email'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='totp_issuer',
            field=models.CharField(blank=True, default='', help_text="Issuer name shown in authenticator apps when the user scans the TOTP QR code (e.g. 'MyShop'). Empty uses the store name.", max_length=64, verbose_name='TOTP Issuer'),
        ),
    ]
