# Generated by Django 6.0.8 on 2026-09-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0036_tenant_contact_email_totp_issuer_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltenant',
            name='recommendations_enabled',
            field=models.BooleanField(default=False, verbose_name='Recommendations Enabled'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='recommendations_enabled',
            field=models.BooleanField(default=False, verbose_name='Recommendations Enabled'),
        ),
    ]
