# Generated by Django 6.0.8 on 2026-09-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0037_tenant_recommendations_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltenant',
            name='vertical',
            field=models.CharField(choices=[('general', 'General'), ('fashion', 'Fashion & apparel'), ('plants_garden', 'Plants & garden'), ('electronics', 'Electronics & gadgets'), ('food', 'Food & drink')], default='general', help_text='What the store sells. Selects the recommendation preset the store starts from; merchants can still edit every slot.', max_length=20, verbose_name='Store vertical'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='vertical',
            field=models.CharField(choices=[('general', 'General'), ('fashion', 'Fashion & apparel'), ('plants_garden', 'Plants & garden'), ('electronics', 'Electronics & gadgets'), ('food', 'Food & drink')], default='general', help_text='What the store sells. Selects the recommendation preset the store starts from; merchants can still edit every slot.', max_length=20, verbose_name='Store vertical'),
        ),
    ]
