# Generated by Django 6.0.8 on 2026-09-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0039_drop_tenant_celery_result_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltenant',
            name='from_email_verified',
            field=models.BooleanField(default=False, help_text="Tick ONLY once this store's sending domain is authenticated on the platform mail relay — SPF and DKIM published and confirmed by the relay. Until then From Email is ignored and the platform address is used, because that is the only domain the relay can sign for. Ticking this early makes every message from this store fail DMARC and land in spam.", verbose_name='From Email verified'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='from_email_verified',
            field=models.BooleanField(default=False, help_text="Tick ONLY once this store's sending domain is authenticated on the platform mail relay — SPF and DKIM published and confirmed by the relay. Until then From Email is ignored and the platform address is used, because that is the only domain the relay can sign for. Ticking this early makes every message from this store fail DMARC and land in spam.", verbose_name='From Email verified'),
        ),
        migrations.AlterField(
            model_name='historicaltenant',
            name='from_email',
            field=models.EmailField(blank=True, default='', help_text='Your own sender address, e.g. orders@your-domain.gr. It takes effect only once the platform ticks From Email Verified, which happens after your domain is authenticated on the mail relay. Until then mail goes out from the platform address with your store name as the display name. Set Contact Email too: that is the reply-to address customers actually reach you on.', max_length=254, verbose_name='From Email'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='from_email',
            field=models.EmailField(blank=True, default='', help_text='Your own sender address, e.g. orders@your-domain.gr. It takes effect only once the platform ticks From Email Verified, which happens after your domain is authenticated on the mail relay. Until then mail goes out from the platform address with your store name as the display name. Set Contact Email too: that is the reply-to address customers actually reach you on.', max_length=254, verbose_name='From Email'),
        ),
    ]
