# Generated by Django 6.0.8 on 2026-09-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0040_tenant_from_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltenant',
            name='google_ads_add_to_cart_label',
            field=models.CharField(blank=True, default='', help_text='Conversion label for adding a product to the cart.', max_length=64, verbose_name='Google Ads Add-to-Cart Label'),
        ),
        migrations.AddField(
            model_name='historicaltenant',
            name='google_ads_begin_checkout_label',
            field=models.CharField(blank=True, default='', help_text='Conversion label for starting the checkout.', max_length=64, verbose_name='Google Ads Begin-Checkout Label'),
        ),
        migrations.AddField(
            model_name='historicaltenant',
            name='google_ads_conversion_id',
            field=models.CharField(blank=True, default='', help_text='Google Ads conversion ID (AW-XXXXXXXXXX). Empty → no conversion events are sent for this tenant, whatever the labels below say.', max_length=32, verbose_name='Google Ads Conversion ID'),
        ),
        migrations.AddField(
            model_name='historicaltenant',
            name='google_ads_page_view_label',
            field=models.CharField(blank=True, default='', help_text='Conversion label for a page view. Sent on every navigation, so leave it empty unless a campaign is built on it.', max_length=64, verbose_name='Google Ads Page-View Label'),
        ),
        migrations.AddField(
            model_name='historicaltenant',
            name='google_ads_purchase_label',
            field=models.CharField(blank=True, default='', help_text="Conversion label for a completed purchase — the part after the slash in 'AW-XXXXXXXXXX/LABEL'. Sent with the order total, currency and transaction id.", max_length=64, verbose_name='Google Ads Purchase Label'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='google_ads_add_to_cart_label',
            field=models.CharField(blank=True, default='', help_text='Conversion label for adding a product to the cart.', max_length=64, verbose_name='Google Ads Add-to-Cart Label'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='google_ads_begin_checkout_label',
            field=models.CharField(blank=True, default='', help_text='Conversion label for starting the checkout.', max_length=64, verbose_name='Google Ads Begin-Checkout Label'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='google_ads_conversion_id',
            field=models.CharField(blank=True, default='', help_text='Google Ads conversion ID (AW-XXXXXXXXXX). Empty → no conversion events are sent for this tenant, whatever the labels below say.', max_length=32, verbose_name='Google Ads Conversion ID'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='google_ads_page_view_label',
            field=models.CharField(blank=True, default='', help_text='Conversion label for a page view. Sent on every navigation, so leave it empty unless a campaign is built on it.', max_length=64, verbose_name='Google Ads Page-View Label'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='google_ads_purchase_label',
            field=models.CharField(blank=True, default='', help_text="Conversion label for a completed purchase — the part after the slash in 'AW-XXXXXXXXXX/LABEL'. Sent with the order total, currency and transaction id.", max_length=64, verbose_name='Google Ads Purchase Label'),
        ),
    ]
