# Generated by Django 6.0.8 on 2026-09-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0041_tenant_google_ads_conversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='cache_generation',
            field=models.PositiveBigIntegerField(db_default=0, default=0, editable=False, verbose_name='Cache Generation'),
        ),
    ]
