# Generated by Django 6.0.8 on 2026-09-26 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0042_tenant_cache_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltenant',
            name='cloudflare_zone_id',
            field=models.CharField(blank=True, db_default='', default='', help_text="The zone of the store's own domain, from the Cloudflare dashboard's domain overview. Empty when the store uses a platform hostname.", max_length=32, validators=[django.core.validators.RegexValidator('^[0-9a-f]{32}$', 'A Cloudflare zone ID is 32 lowercase hex characters.')], verbose_name='Cloudflare zone ID'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='cloudflare_api_token',
            field=models.CharField(blank=True, db_default='', default='', help_text="A token with only Zone → Cache Purge → Purge on that zone. Secret — used to clear the store's pages from Cloudflare's cache after an edit or a deploy.", max_length=255, verbose_name='Cloudflare API token'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='cloudflare_zone_id',
            field=models.CharField(blank=True, db_default='', default='', help_text="The zone of the store's own domain, from the Cloudflare dashboard's domain overview. Empty when the store uses a platform hostname.", max_length=32, validators=[django.core.validators.RegexValidator('^[0-9a-f]{32}$', 'A Cloudflare zone ID is 32 lowercase hex characters.')], verbose_name='Cloudflare zone ID'),
        ),
    ]
