# Generated by Django 6.0.8 on 2026-09-30 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0043_tenant_cloudflare_edge_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantStatsSnapshot',
            fields=[
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stats_snapshot', serialize=False, to='tenant.tenant', verbose_name='Store')),
                ('orders_count', models.PositiveIntegerField(verbose_name='Orders')),
                ('revenue', models.DecimalField(decimal_places=2, help_text='Paid amount of every order whose payment completed.', max_digits=14, verbose_name='Revenue')),
                ('last_order_at', models.DateTimeField(null=True, verbose_name='Last order')),
                ('refreshed_at', models.DateTimeField(verbose_name='Refreshed')),
            ],
            options={
                'verbose_name': 'Store figures',
                'verbose_name_plural': 'Store figures',
            },
        ),
    ]
