# Generated by Django 6.0.8 on 2026-09-30 23:11

import core.json_schema
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0044_tenant_stats_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltenant',
            name='allowed_csp_sources',
            field=models.JSONField(blank=True, default=list, help_text='Additional origins allowed by the storefront CSP (connect-src, img-src, script-src, frame-src). Each entry must start with https://, http://localhost, or wss://.', validators=[core.json_schema.JSONSchemaValidator('tenant.json_schemas.allowed_csp_sources')], verbose_name='Allowed CSP sources'),
        ),
        migrations.AlterField(
            model_name='historicaltenant',
            name='available_locales',
            field=models.JSONField(blank=True, default=list, help_text='Locales this store serves, e.g. ["el", "en"]. Empty means single-language on the default locale — the storefront then 404s every other locale prefix and hides it from the language switcher, hreflang set and sitemap. Must contain default_locale when non-empty.', validators=[core.json_schema.JSONSchemaValidator('tenant.json_schemas.available_locales')], verbose_name='Available Locales'),
        ),
        migrations.AlterField(
            model_name='historicaltenant',
            name='theme_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Per-token theme overrides on top of the preset. Legal keys: radius, fontSans, container, colors.primaryScale / colors.neutralScale (shade → #RRGGBB). Anything else is rejected — the storefront token compiler ignores invalid metadata entirely.', validators=[core.json_schema.JSONSchemaValidator('tenant.json_schemas.theme_metadata')], verbose_name='Theme Metadata'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='allowed_csp_sources',
            field=models.JSONField(blank=True, default=list, help_text='Additional origins allowed by the storefront CSP (connect-src, img-src, script-src, frame-src). Each entry must start with https://, http://localhost, or wss://.', validators=[core.json_schema.JSONSchemaValidator('tenant.json_schemas.allowed_csp_sources')], verbose_name='Allowed CSP sources'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='available_locales',
            field=models.JSONField(blank=True, default=list, help_text='Locales this store serves, e.g. ["el", "en"]. Empty means single-language on the default locale — the storefront then 404s every other locale prefix and hides it from the language switcher, hreflang set and sitemap. Must contain default_locale when non-empty.', validators=[core.json_schema.JSONSchemaValidator('tenant.json_schemas.available_locales')], verbose_name='Available Locales'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='theme_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Per-token theme overrides on top of the preset. Legal keys: radius, fontSans, container, colors.primaryScale / colors.neutralScale (shade → #RRGGBB). Anything else is rejected — the storefront token compiler ignores invalid metadata entirely.', validators=[core.json_schema.JSONSchemaValidator('tenant.json_schemas.theme_metadata')], verbose_name='Theme Metadata'),
        ),
    ]
