# Generated by Django 6.0.8 on 2026-09-30 23:27

import core.utils.tenant_urls
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0045_json_schema_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltenant',
            name='default_currency',
            field=models.CharField(choices=[('EUR', 'EUR €'), ('USD', 'USD $')], default='EUR', max_length=3, verbose_name='Default Currency'),
        ),
        migrations.AlterField(
            model_name='historicaltenant',
            name='default_locale',
            field=models.CharField(choices=core.utils.tenant_urls.storefront_language_choices, default='el', max_length=10, verbose_name='Default Locale'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='default_currency',
            field=models.CharField(choices=[('EUR', 'EUR €'), ('USD', 'USD $')], default='EUR', max_length=3, verbose_name='Default Currency'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='default_locale',
            field=models.CharField(choices=core.utils.tenant_urls.storefront_language_choices, default='el', max_length=10, verbose_name='Default Locale'),
        ),
    ]
