# Generated by Django 6.0.8 on 2026-10-06 09:33

import core.json_schema
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0047_field_verbose_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltenant',
            name='store_description_i18n',
            field=models.JSONField(blank=True, db_default={}, default=dict, help_text='The store line in the storefront\'s other languages, keyed by locale, e.g. {"en": "..."}. The default locale line is Store Description; a locale left out falls back to it.', validators=[core.json_schema.JSONSchemaValidator('tenant.json_schemas.store_description_i18n')], verbose_name='Store Description (other languages)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='store_description_i18n',
            field=models.JSONField(blank=True, db_default={}, default=dict, help_text='The store line in the storefront\'s other languages, keyed by locale, e.g. {"en": "..."}. The default locale line is Store Description; a locale left out falls back to it.', validators=[core.json_schema.JSONSchemaValidator('tenant.json_schemas.store_description_i18n')], verbose_name='Store Description (other languages)'),
        ),
    ]
