# Generated by Django 6.0.3 on 2026-04-05 10:16

import django.db.models.deletion
import parler.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_add_icon_to_loyalty_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltytiertranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='loyalty.loyaltytier'),
        ),
    ]
