# Generated by Django 6.0.5 on 2026-05-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0003_alter_loyaltytiertranslation_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltytier',
            name='sort_order',
            field=models.IntegerField(null=True, verbose_name='Sort Order'),
        ),
    ]
