# Generated by Django 6.0.4 on 2026-04-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0012_alter_notificationuser_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('order_created', 'Order created'), ('order_processing', 'Order processing'), ('order_shipped', 'Order shipped'), ('order_delivered', 'Order delivered'), ('order_completed', 'Order completed'), ('order_canceled', 'Order canceled'), ('order_refunded', 'Order refunded'), ('shipment_dispatched', 'Shipment dispatched'), ('payment_confirmed', 'Payment confirmed'), ('payment_failed', 'Payment failed'), ('price_drop_favourite', 'Price drop (favourited product)'), ('restock_favourite', 'Back in stock (favourited product)'), ('loyalty_tier_up', 'Loyalty tier promotion'), ('comment_liked', 'Blog comment liked')], help_text='Fine-grained event identifier. See ``notification.enum.NotificationTypeEnum`` for the full catalogue. Left blank for ad-hoc admin broadcasts.', max_length=100, verbose_name='Notification Type'),
        ),
    ]
