# Generated by Django 6.0.5 on 2026-05-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0015_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificationtranslation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='notificationtranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='notification_notification_translation_uniq_lang'),
        ),
    ]
