# Generated by Django 6.0.4 on 2026-04-27 17:08

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import djmoney.money
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0035_order_shipping_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxNowLocker',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(help_text='BoxNow APM identifier (string)', max_length=64, unique=True, verbose_name='External ID')),
                ('type', models.CharField(choices=[('apm', 'APM'), ('any_apm', 'Any APM'), ('warehouse', 'Warehouse'), ('depot', 'Depot')], default='apm', max_length=20, verbose_name='Type')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Image URL')),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Latitude')),
                ('lng', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longitude')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Title')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Name')),
                ('address_line_1', models.CharField(blank=True, default='', max_length=255, verbose_name='Address Line 1')),
                ('address_line_2', models.CharField(blank=True, default='', max_length=255, verbose_name='Address Line 2')),
                ('postal_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Postal Code')),
                ('country_code', models.CharField(default='GR', help_text='ISO 3166-1 alpha-2 country code', max_length=2, verbose_name='Country Code')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Timestamp of the most recent sync from BoxNow API', null=True, verbose_name='Last Synced At')),
            ],
            options={
                'verbose_name': 'BoxNow Locker',
                'verbose_name_plural': 'BoxNow Lockers',
                'ordering': ['-last_synced_at'],
                'indexes': [django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='boxnowlocker_created_at_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['updated_at'], name='boxnowlocker_updated_at_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['external_id'], name='boxnow_locker_ext_id_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['postal_code'], name='boxnow_locker_postal_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['is_active'], name='boxnow_locker_active_ix')],
            },
        ),
        migrations.CreateModel(
            name='BoxNowShipment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('delivery_request_id', models.CharField(blank=True, default='', help_text='BoxNow delivery-request ID returned from POST /api/v1/delivery-requests', max_length=128, unique=True, verbose_name='Delivery Request ID')),
                ('parcel_id', models.CharField(blank=True, default='', help_text='10-digit BoxNow voucher number', max_length=32, unique=True, verbose_name='Parcel ID')),
                ('locker_external_id', models.CharField(blank=True, default='', help_text='Denormalised BoxNow APM ID — preserved even if the BoxNowLocker row is deleted', max_length=64, verbose_name='Locker External ID')),
                ('parcel_state', models.CharField(choices=[('pending_creation', 'Pending creation'), ('new', 'New'), ('in_depot', 'In depot'), ('final_destination', 'At locker'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('expired', 'Expired'), ('canceled', 'Canceled'), ('accepted_for_return', 'Accepted for return'), ('accepted_to_locker', 'Accepted to locker'), ('missing', 'Missing'), ('lost', 'Lost')], default='pending_creation', max_length=30, verbose_name='Parcel State')),
                ('compartment_size', models.PositiveSmallIntegerField(choices=[(1, 'Μικρό'), (2, 'Μεσαίο'), (3, 'Μεγάλο')], default=1, verbose_name='Compartment Size')),
                ('weight_grams', models.PositiveIntegerField(default=0, verbose_name='Weight (grams)')),
                ('payment_mode', models.CharField(choices=[('prepaid', 'Prepaid'), ('cod', 'Cash on delivery')], default='prepaid', max_length=10, verbose_name='Payment Mode')),
                ('amount_to_be_collected_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3)),
                ('amount_to_be_collected', djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'EUR'), help_text='Amount collected at delivery (PoG / COD). Always 0 in Phase 1.', max_digits=11, verbose_name='Amount to be Collected')),
                ('allow_return', models.BooleanField(default=True, verbose_name='Allow Return')),
                ('label_url', models.URLField(blank=True, default='', help_text='Cached BoxNow-hosted label URL if returned', max_length=500, verbose_name='Label URL')),
                ('last_event_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Event At')),
                ('cancel_requested_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancel Requested At')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Full delivery-request response and diagnostics from BoxNow', verbose_name='Metadata')),
                ('locker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='shipping_boxnow.boxnowlocker', verbose_name='Locker')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boxnow_shipment', to='order.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'BoxNow Shipment',
                'verbose_name_plural': 'BoxNow Shipments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoxNowParcelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('webhook_message_id', models.CharField(db_index=True, help_text="CloudEvents 'id' field — idempotency key", max_length=128, unique=True, verbose_name='Webhook Message ID')),
                ('event_type', models.CharField(choices=[('pending_creation', 'Pending creation'), ('new', 'New'), ('in_depot', 'In depot'), ('final_destination', 'At locker'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('expired', 'Expired'), ('canceled', 'Canceled'), ('accepted_for_return', 'Accepted for return'), ('accepted_to_locker', 'Accepted to locker'), ('missing', 'Missing'), ('lost', 'Lost')], help_text="BoxNow event mapped from the webhook 'event' field", max_length=30, verbose_name='Event Type')),
                ('parcel_state', models.CharField(blank=True, default='', help_text="Raw 'data.parcelState' value from BoxNow webhook payload", max_length=64, verbose_name='Parcel State')),
                ('event_time', models.DateTimeField(help_text="Timestamp from 'data.time' in the webhook payload", verbose_name='Event Time')),
                ('display_name', models.CharField(blank=True, default='', help_text='data.eventLocation.displayName', max_length=255, verbose_name='Display Name')),
                ('postal_code', models.CharField(blank=True, default='', help_text='data.eventLocation.postalCode', max_length=20, verbose_name='Postal Code')),
                ('additional_information', models.TextField(blank=True, default='', verbose_name='Additional Information')),
                ('raw_payload', models.JSONField(help_text='Full webhook request body', verbose_name='Raw Payload')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when GrooveShop received the webhook (separate from event_time)', verbose_name='Received At')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shipping_boxnow.boxnowshipment', verbose_name='Shipment')),
            ],
            options={
                'verbose_name': 'BoxNow Parcel Event',
                'verbose_name_plural': 'BoxNow Parcel Events',
                'ordering': ['-event_time'],
            },
        ),
        migrations.AddIndex(
            model_name='boxnowshipment',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='boxnowshipment_created_at_ix'),
        ),
        migrations.AddIndex(
            model_name='boxnowshipment',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['updated_at'], name='boxnowshipment_updated_at_ix'),
        ),
        migrations.AddIndex(
            model_name='boxnowshipment',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['parcel_state'], name='boxnow_shipment_state_ix'),
        ),
        migrations.AddIndex(
            model_name='boxnowshipment',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['parcel_id'], name='boxnow_shipment_parcel_id_ix'),
        ),
        migrations.AddIndex(
            model_name='boxnowshipment',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['delivery_request_id'], name='boxnow_shipment_req_id_ix'),
        ),
        migrations.AddIndex(
            model_name='boxnowshipment',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['locker_external_id'], name='boxnow_shipment_locker_ext_ix'),
        ),
        migrations.AddIndex(
            model_name='boxnowparcelevent',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='boxnowparcelevent_created_at_ix'),
        ),
        migrations.AddIndex(
            model_name='boxnowparcelevent',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['updated_at'], name='boxnowparcelevent_updated_at_ix'),
        ),
        migrations.AddIndex(
            model_name='boxnowparcelevent',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['event_time'], name='boxnow_event_time_ix'),
        ),
        migrations.AddIndex(
            model_name='boxnowparcelevent',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['event_type'], name='boxnow_event_type_ix'),
        ),
        migrations.AddIndex(
            model_name='boxnowparcelevent',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['shipment'], name='boxnow_event_shipment_ix'),
        ),
    ]
