# Generated by Django 6.0.4 on 2026-04-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_boxnow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxnowshipment',
            name='delivery_request_id',
            field=models.CharField(blank=True, default=None, help_text='BoxNow delivery-request ID returned from POST /api/v1/delivery-requests', max_length=128, null=True, unique=True, verbose_name='Delivery Request ID'),
        ),
        migrations.AlterField(
            model_name='boxnowshipment',
            name='parcel_id',
            field=models.CharField(blank=True, default=None, help_text='10-digit BoxNow voucher number', max_length=32, null=True, unique=True, verbose_name='Parcel ID'),
        ),
    ]
