# Generated by Django 6.0.4 on 2026-04-30 23:37

import django.db.models.deletion
import djmoney.models.fields
import djmoney.money
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0038_drop_shipping_method'),
        ('shipping_boxnow', '0002_alter_boxnowshipment_delivery_request_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBoxNowShipment',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Created At')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('id', models.BigIntegerField(blank=True, db_index=True)),
                ('delivery_request_id', models.CharField(blank=True, db_index=True, default=None, help_text='BoxNow delivery-request ID returned from POST /api/v1/delivery-requests', max_length=128, null=True, verbose_name='Delivery Request ID')),
                ('parcel_id', models.CharField(blank=True, db_index=True, default=None, help_text='10-digit BoxNow voucher number', max_length=32, null=True, verbose_name='Parcel ID')),
                ('locker_external_id', models.CharField(blank=True, default='', help_text='Denormalised BoxNow APM ID — preserved even if the BoxNowLocker row is deleted', max_length=64, verbose_name='Locker External ID')),
                ('parcel_state', models.CharField(choices=[('pending_creation', 'Pending creation'), ('new', 'New'), ('in_depot', 'In depot'), ('final_destination', 'At locker'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('expired', 'Expired'), ('canceled', 'Canceled'), ('accepted_for_return', 'Accepted for return'), ('accepted_to_locker', 'Accepted to locker'), ('missing', 'Missing'), ('lost', 'Lost')], default='pending_creation', max_length=30, verbose_name='Parcel State')),
                ('compartment_size', models.PositiveSmallIntegerField(choices=[(1, 'Μικρό'), (2, 'Μεσαίο'), (3, 'Μεγάλο')], default=1, verbose_name='Compartment Size')),
                ('weight_grams', models.PositiveIntegerField(default=0, verbose_name='Weight (grams)')),
                ('payment_mode', models.CharField(choices=[('prepaid', 'Prepaid'), ('cod', 'Cash on delivery')], default='prepaid', max_length=10, verbose_name='Payment Mode')),
                ('amount_to_be_collected_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3)),
                ('amount_to_be_collected', djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'EUR'), help_text='Amount collected at delivery (PoG / COD). Always 0 in Phase 1.', max_digits=11, verbose_name='Amount to be Collected')),
                ('allow_return', models.BooleanField(default=True, verbose_name='Allow Return')),
                ('label_url', models.URLField(blank=True, default='', help_text='Cached BoxNow-hosted label URL if returned', max_length=500, verbose_name='Label URL')),
                ('cancel_requested_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancel Requested At')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('locker', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shipping_boxnow.boxnowlocker', verbose_name='Locker')),
                ('order', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='order.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'historical BoxNow Shipment',
                'verbose_name_plural': 'historical BoxNow Shipments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
