# Generated by Django 6.0.5 on 2026-05-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_boxnow', '0003_historicalboxnowshipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxnowshipment',
            name='last_polled_at',
            field=models.DateTimeField(blank=True, help_text='Last time we reconciled this shipment via the BoxNow REST API (defence-in-depth against missed webhooks).', null=True, verbose_name='Last Polled At'),
        ),
    ]
