# Generated by Django 6.0.7 on 2026-07-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_boxnow', '0004_add_last_polled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxnowparcelevent',
            name='data_fingerprint',
            field=models.CharField(blank=True, db_index=True, help_text="SHA-256 of the HMAC-signed 'data' bytes. The signature covers only 'data', not the envelope 'id', so replay dedup keys on this content hash as well — a captured event resubmitted under a new/forged 'id' still collides here.", max_length=64, null=True, verbose_name='Signed Data Fingerprint'),
        ),
    ]
