# Generated by Django 6.0.8 on 2026-09-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_boxnow', '0007_alter_boxnowlocker_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxnowlocker',
            name='country_code',
            field=models.CharField(help_text='ISO 3166-1 alpha-2 country code', max_length=2, verbose_name='Country Code'),
        ),
    ]
