# Generated by Django 6.0.8 on 2026-10-01 00:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_boxnow', '0008_alter_boxnowlocker_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxnowlocker',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='boxnowshipment',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='historicalboxnowshipment',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='UUID'),
        ),
    ]
