# Generated by Django 6.0.8 on 2026-08-24 19:48

import django.contrib.postgres.indexes
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_contact_contact_con_email_2ebc86_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Name')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('category', models.CharField(choices=[('general', 'General'), ('website', 'Website & UX'), ('products', 'Products'), ('delivery', 'Delivery'), ('support', 'Customer support'), ('other', 'Other')], default='general', max_length=20, verbose_name='Category')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'ordering': ['-created_at'],
                'indexes': [django.contrib.postgres.indexes.BTreeIndex(fields=['category'], name='feedback_category_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['rating'], name='feedback_rating_ix')],
            },
        ),
    ]
