# Generated by Django 6.0.8 on 2026-09-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_timestamp_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.CharField(blank=True, db_default='', max_length=150, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, db_default='', max_length=30, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.CharField(blank=True, db_default='', max_length=60, verbose_name='Subject'),
        ),
    ]
