# Generated by Django 6.0.8 on 2026-09-08 14:27

import contact.storage
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_contact_company_contact_phone_contact_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='Stored in the per-tenant PRIVATE tree. Reachable only by streaming it through the staff-gated download view; it has no public URL.', max_length=255, storage=contact.storage.private_attachment_storage, upload_to=contact.storage.attachment_upload_to, verbose_name='File')),
                ('original_name', models.CharField(max_length=255, verbose_name='Original name')),
                ('content_type', models.CharField(max_length=120, verbose_name='Content type')),
                ('size', models.PositiveIntegerField(help_text='Bytes.', verbose_name='Size')),
                ('checksum', models.CharField(db_index=True, max_length=64, verbose_name='Checksum')),
                ('scan_status', models.CharField(choices=[('PENDING', 'Pending scan'), ('CLEAN', 'Clean'), ('INFECTED', 'Infected'), ('ERROR', 'Scan failed'), ('SKIPPED', 'Not scanned')], db_default='PENDING', default='PENDING', max_length=10, verbose_name='Scan status')),
                ('scan_detail', models.CharField(blank=True, db_default='', max_length=255, verbose_name='Scan detail')),
                ('scanned_at', models.DateTimeField(blank=True, null=True, verbose_name='Scanned at')),
                ('claim_deadline', models.DateTimeField(verbose_name='Claim deadline')),
                ('contact', models.ForeignKey(blank=True, help_text='Null until the enquiry that claims this upload is submitted.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='contact.contact', verbose_name='Contact')),
            ],
            options={
                'verbose_name': 'Contact Attachment',
                'verbose_name_plural': 'Contact Attachments',
                'ordering': ['id'],
                'indexes': [django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='contactattachment_created_at_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['updated_at'], name='contactattachment_updated_at_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['claim_deadline'], name='contact_att_deadline_ix')],
            },
        ),
    ]
