# Generated by Django 6.0.2 on 2026-03-01 22:45

import django.contrib.postgres.indexes
import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
                ('page_type', models.CharField(help_text='Identifier for the page (e.g. "home", "products", "blog").', max_length=50, unique=True, verbose_name='Page Type')),
                ('title', models.CharField(help_text='Admin display name for this layout.', max_length=200, verbose_name='Title')),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Metadata')),
            ],
            options={
                'verbose_name': 'Page Layout',
                'verbose_name_plural': 'Page Layouts',
                'ordering': ['page_type'],
                'indexes': [django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='pagelayout_created_at_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['updated_at'], name='pagelayout_updated_at_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['published_at'], name='pagelayout_published_at_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['is_published'], name='pagelayout_is_published_ix')],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(editable=False, null=True, verbose_name='Sort Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('component_type', models.CharField(choices=[('hero_banner', 'Hero Banner'), ('hero_carousel', 'Hero Carousel'), ('products_slider', 'Products Slider'), ('products_grid', 'Products Grid'), ('featured_products', 'Featured Products'), ('product_categories', 'Product Categories'), ('blog_posts_carousel', 'Blog Posts Carousel'), ('blog_posts_grid', 'Blog Posts Grid'), ('rich_text', 'Rich Text Block'), ('cta_banner', 'Call to Action Banner'), ('newsletter_signup', 'Newsletter Signup'), ('testimonials', 'Testimonials'), ('spacer', 'Spacer'), ('divider', 'Divider'), ('loyalty_hero', 'Loyalty Program Hero'), ('search_bar', 'Search Bar')], max_length=50, verbose_name='Component Type')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Title')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Is Visible')),
                ('props', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Component-specific configuration as JSON.', verbose_name='Props')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='page_config.pagelayout', verbose_name='Layout')),
            ],
            options={
                'verbose_name': 'Page Section',
                'verbose_name_plural': 'Page Sections',
                'ordering': ['sort_order'],
                'indexes': [django.contrib.postgres.indexes.BTreeIndex(fields=['sort_order'], name='pagesection_sort_order_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='pagesection_created_at_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['updated_at'], name='pagesection_updated_at_ix')],
            },
        ),
    ]
