# Generated by Django 6.0.5 on 2026-05-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='sort_order',
            field=models.IntegerField(null=True, verbose_name='Sort Order'),
        ),
    ]
