# Generated by Django 6.0.8 on 2026-08-18 00:40

import django.core.serializers.json
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_config', '0003_alter_pagesection_component_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('slot', models.CharField(choices=[('header', 'Header'), ('footer', 'Footer'), ('mobile', 'Mobile')], max_length=20, unique=True, verbose_name='Slot')),
                ('items', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text="header/mobile: [{label, to|href, icon?}]; footer: [{label, icon?, children: [{label, to|href}]}]. 'to' must be an internal path starting with '/', 'href' an https URL.", verbose_name='Items')),
            ],
            options={
                'verbose_name': 'Navigation Menu',
                'verbose_name_plural': 'Navigation Menus',
                'ordering': ['slot'],
            },
        ),
    ]
