# Generated by Django 6.0.8 on 2026-08-24 17:39

import django.contrib.postgres.indexes
import django.db.models.deletion
import parler.fields
import parler.models
import tinymce.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_config', '0005_alter_pagesection_component_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, default='', max_length=70, verbose_name='Seo Title')),
                ('seo_description', models.TextField(blank=True, default='', max_length=300, verbose_name='Seo Description')),
                ('seo_keywords', models.CharField(blank=True, default='', max_length=255, verbose_name='Seo Keywords')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('is_published', models.BooleanField(default=False, verbose_name='Is Published')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Content Page',
                'verbose_name_plural': 'Content Pages',
                'ordering': ['slug'],
                'indexes': [django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='contentpage_created_at_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['updated_at'], name='contentpage_updated_at_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['published_at'], name='contentpage_published_at_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['is_published'], name='contentpage_is_published_ix')],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ContentPageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, default='', max_length=255, verbose_name='Title')),
                ('body', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Body')),
                ('master', parler.fields.TranslationsForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='page_config.contentpage')),
            ],
            options={
                'verbose_name': 'Content Page Translation',
                'verbose_name_plural': 'Content Page Translations',
                'db_table': 'page_config_contentpage_translation',
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
