# Generated by Django 6.0.8 on 2026-08-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_config', '0009_alter_pagesection_component_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='component_type',
            field=models.CharField(choices=[('hero_banner', 'Hero Banner'), ('hero_carousel', 'Hero Carousel'), ('products_slider', 'Products Slider'), ('products_grid', 'Products Grid'), ('featured_products', 'Featured Products'), ('product_categories', 'Product Categories'), ('blog_categories', 'Blog Categories Rail'), ('blog_posts_carousel', 'Blog Posts Carousel'), ('blog_posts_grid', 'Blog Posts Grid'), ('blog_posts_list', 'Blog Posts List'), ('recently_viewed', 'Recently Viewed Rail'), ('rich_text', 'Rich Text Block'), ('cta_banner', 'Call to Action Banner'), ('newsletter_signup', 'Newsletter Signup'), ('testimonials', 'Testimonials'), ('about_content', 'About Content'), ('vision_content', 'Vision Content'), ('what_is_microlearning', 'What Is Microlearning'), ('why_microlearning', 'Why Microlearning'), ('spacer', 'Spacer'), ('divider', 'Divider'), ('loyalty_hero', 'Loyalty Program Hero'), ('search_bar', 'Search Bar'), ('business_hours', 'Business Hours'), ('location_map', 'Location Map'), ('features_grid', 'Features Grid'), ('media_text', 'Media + Text'), ('image_gallery', 'Image Gallery'), ('story_timeline', 'Story Timeline'), ('faq', 'FAQ Accordion')], max_length=50, verbose_name='Component Type'),
        ),
    ]
