# Generated by Django 6.0.8 on 2026-09-07 08:24

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_config', '0011_seo_description_plain_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationmenu',
            name='i18n',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Per-locale menus, e.g. {"en": [...]}, in the same shape as Items. A menu is translated whole rather than per item, because an index-keyed overlay would retarget every label the first time the menu is reordered. Locales with no entry here get the menu above.', verbose_name='Locale Overrides'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='i18n',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Per-locale overrides, e.g. {"en": {"title": "Hero", "props": {"heading": "..."}}}. Only the keys that differ; everything else falls back to the fields above. The default locale is not a valid key — those ARE the fields above.', verbose_name='Locale Overrides'),
        ),
    ]
