# Generated by Django 6.0.8 on 2026-09-11 07:43

import core.fields.plain_text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_config', '0019_alter_pagesection_component_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagelayout',
            name='seo_description',
            field=core.fields.plain_text.PlainTextField(blank=True, default='', max_length=300, verbose_name='Seo Description'),
        ),
        migrations.AddField(
            model_name='pagelayout',
            name='seo_keywords',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Seo Keywords'),
        ),
        migrations.AddField(
            model_name='pagelayout',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=70, verbose_name='Seo Title'),
        ),
    ]
