# Generated by Django 6.0.8 on 2026-09-17 16:59

import django.contrib.postgres.indexes
import django.db.models.deletion
import page_config.schemas
import parler.fields
import parler.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_config', '0022_correct_legal_document_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(null=True, verbose_name='Sort Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('icon', models.CharField(blank=True, default='', help_text='An i-* icon name, e.g. i-heroicons-light-bulb.', max_length=64, validators=[page_config.schemas.validate_icon_name], verbose_name='Icon')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='page_config.navigationmenu', verbose_name='Menu')),
            ],
            options={
                'verbose_name': 'Navigation Column',
                'verbose_name_plural': 'Navigation Columns',
                'ordering': ['sort_order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NavigationColumnTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('label', models.CharField(max_length=100, verbose_name='Label')),
                ('master', parler.fields.TranslationsForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='page_config.navigationcolumn')),
            ],
            options={
                'verbose_name': 'Navigation Column Translation',
                'verbose_name_plural': 'Navigation Column Translations',
                'db_table': 'page_config_navigationcolumn_translation',
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NavigationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(null=True, verbose_name='Sort Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('route', models.CharField(blank=True, choices=[('/', 'Home'), ('/products', 'Products'), ('/blog', 'Blog'), ('/contact', 'Contact'), ('/offers', 'Offers'), ('/gift-cards', 'Gift cards'), ('/loyalty-program', 'Loyalty program'), ('/feedback', 'Feedback')], default='', max_length=64, verbose_name='Built-in page')),
                ('url', models.URLField(blank=True, default='', help_text='An absolute https URL on another site.', verbose_name='External link')),
                ('column', models.ForeignKey(blank=True, help_text='Footer links belong to a column.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='page_config.navigationcolumn', verbose_name='Column')),
                ('content_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navigation_links', to='page_config.contentpage', verbose_name='Content page')),
                ('menu', models.ForeignKey(blank=True, help_text='Header and mobile links hang off the menu directly.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links', to='page_config.navigationmenu', verbose_name='Menu')),
                ('page_layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='navigation_links', to='page_config.pagelayout', verbose_name='Custom page')),
            ],
            options={
                'verbose_name': 'Navigation Link',
                'verbose_name_plural': 'Navigation Links',
                'ordering': ['sort_order'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NavigationLinkTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('label', models.CharField(blank=True, default='', help_text="Leave empty for a page link to use the page's own title, which is already translated.", max_length=100, verbose_name='Label')),
                ('master', parler.fields.TranslationsForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='page_config.navigationlink')),
            ],
            options={
                'verbose_name': 'Navigation Link Translation',
                'verbose_name_plural': 'Navigation Link Translations',
                'db_table': 'page_config_navigationlink_translation',
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='navigationcolumn',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['sort_order'], name='navigationcolumn_sort_order_ix'),
        ),
        migrations.AddIndex(
            model_name='navigationcolumn',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='navigationcolumn_created_at_ix'),
        ),
        migrations.AddIndex(
            model_name='navigationcolumn',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['updated_at'], name='navigationcolumn_updated_at_ix'),
        ),
        migrations.AlterUniqueTogether(
            name='navigationcolumntranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AddIndex(
            model_name='navigationlink',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['sort_order'], name='navigationlink_sort_order_ix'),
        ),
        migrations.AddIndex(
            model_name='navigationlink',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='navigationlink_created_at_ix'),
        ),
        migrations.AddIndex(
            model_name='navigationlink',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['updated_at'], name='navigationlink_updated_at_ix'),
        ),
        migrations.AddConstraint(
            model_name='navigationlink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('column__isnull', True), ('menu__isnull', False)), models.Q(('column__isnull', False), ('menu__isnull', True)), _connector='OR'), name='navigationlink_exactly_one_parent'),
        ),
        migrations.AddConstraint(
            model_name='navigationlink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('content_page__isnull', False), ('page_layout__isnull', True), ('route', ''), ('url', '')), models.Q(('content_page__isnull', True), ('page_layout__isnull', False), ('route', ''), ('url', '')), models.Q(('content_page__isnull', True), ('page_layout__isnull', True), ('url', ''), models.Q(('route', ''), _negated=True)), models.Q(('content_page__isnull', True), ('page_layout__isnull', True), ('route', ''), models.Q(('url', ''), _negated=True)), _connector='OR'), name='navigationlink_exactly_one_target'),
        ),
        migrations.AlterUniqueTogether(
            name='navigationlinktranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
