# Generated by Django 6.0.8 on 2026-09-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page_config", "0030_remove_shared_seo_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentpage",
            name="legal_text_revision",
            field=models.PositiveSmallIntegerField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Platform legal text revision",
            ),
        ),
    ]
