# Generated by Django 6.0.8 on 2026-09-27 12:37

import core.fields.rich_text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_config', '0032_privacy_server_logs_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentpagetranslation',
            name='body',
            field=core.fields.rich_text.RichTextField(blank=True, null=True, verbose_name='Body'),
        ),
    ]
