"""Keep transactional mail away from a store's shared demo logins.

A demo store publishes an account's password on its own login page, so
that account is shared and anyone can act as it. Two kinds of mail then
get generated by strangers:

  * an order confirmation, when a visitor walks the cash-on-delivery
    checkout — which is the point of letting them;
  * a password-reset mail, whenever a curious visitor asks for one. The
    reset itself is refused (``TenantAccountAdapter.set_password``), but
    allauth still sends the message before anything can refuse it.

Neither reaches the person who triggered it — the address belongs to the
store, not to them — so the mail only ever lands in the operator's
inbox, and it lands there at the rate strangers generate it. Worse, a
demo address with no forwarding rule BOUNCES, and the bounce is counted
against the platform's sending domain.

So it is dropped here, at the one place every sender passes through.
Doing it per-sender would mean finding them all and finding the next one
too.

This is a passthrough on every ordinary store: ``demo_account_emails()``
is empty unless ``DEMO_ACCOUNT_ENABLED`` is on for that schema, and then
no recipient can match.
"""

from __future__ import annotations

import logging

from django.conf import settings
from django.core.mail import get_connection
from django.core.mail.backends.base import BaseEmailBackend

from core.demo_account import demo_account_emails

logger = logging.getLogger(__name__)


class DemoRecipientSuppressingBackend(BaseEmailBackend):
    """Delegate to the configured backend, minus demo recipients."""

    def __init__(self, fail_silently: bool = False, **kwargs) -> None:
        super().__init__(fail_silently=fail_silently)
        self._kwargs = kwargs
        self._fail_silently = fail_silently

    def _connection(self):
        # Resolved per send rather than held: the delegate may be an SMTP
        # connection, and a long-lived one in a Celery worker outlives
        # the broker's idle timeout.
        return get_connection(
            backend=settings.EMAIL_DELEGATE_BACKEND,
            fail_silently=self._fail_silently,
            **self._kwargs,
        )

    def send_messages(self, email_messages) -> int:
        if not email_messages:
            return 0

        suppressed = demo_account_emails()
        if not suppressed:
            return self._connection().send_messages(email_messages)

        kept = []
        dropped = 0
        for message in email_messages:
            if self._strip(message, suppressed):
                kept.append(message)
            else:
                dropped += 1

        if dropped:
            logger.info(
                "Suppressed %d message(s) addressed only to a shared demo "
                "account",
                dropped,
            )
        if not kept:
            # Django's contract is "number of messages SENT", and none
            # were. Reporting the dropped ones as sent would make a
            # suppressed mail look delivered in every caller's logs.
            return 0
        return self._connection().send_messages(kept)

    @staticmethod
    def _strip(message, suppressed: frozenset[str]) -> bool:
        """Remove demo addresses; return whether anything is left.

        ``cc``/``bcc`` are filtered too — a demo address copied on a
        message to somebody real is the same leak, just quieter.
        """
        for field in ("to", "cc", "bcc"):
            addresses = getattr(message, field, None)
            if not addresses:
                continue
            setattr(
                message,
                field,
                [
                    address
                    for address in addresses
                    if _mailbox(address) not in suppressed
                ],
            )
        return bool(
            getattr(message, "to", None)
            or getattr(message, "cc", None)
            or getattr(message, "bcc", None)
        )


def _mailbox(address: str) -> str:
    """The bare address out of ``Name <a@b>``, lowercased."""
    text = str(address or "").strip().lower()
    if "<" in text and text.endswith(">"):
        text = text[text.rindex("<") + 1 : -1].strip()
    return text
