# Generated by Django 6.0.5 on 2026-05-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0005_alter_tag_managers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tagtranslation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='tagtranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='tag_tag_translation_uniq_lang'),
        ),
    ]
