# Generated by Django 5.1 on 2024-09-01 21:58
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0020_alter_blogcategory_sort_order_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogposttranslation",
            options={"verbose_name": "Blog Post Translation", "verbose_name_plural": "Blog Post Translations"},
        ),
        migrations.RemoveField(
            model_name="blogposttranslation",
            name="search_document",
        ),
        migrations.RemoveField(
            model_name="blogposttranslation",
            name="search_document_dirty",
        ),
        migrations.RemoveField(
            model_name="blogposttranslation",
            name="search_vector",
        ),
        migrations.RemoveField(
            model_name="blogposttranslation",
            name="search_vector_dirty",
        ),
        migrations.AlterField(
            model_name="blogposttranslation",
            name="master",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="translations", to="blog.blogpost"
            ),
        ),
    ]
