# Generated by Django 6.0.5 on 2026-05-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_blogcategory_blog_blogcategory_tree_id_9462_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blogauthortranslation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='blogcategorytranslation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='blogcommenttranslation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='blogtagtranslation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='blogauthortranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='blog_blogauthor_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='blogcategorytranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='blog_blogcategory_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='blogcommenttranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='blog_blogcomment_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='blogtagtranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='blog_blogtag_translation_uniq_lang'),
        ),
    ]
