# Generated by Django 6.0.5 on 2026-05-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_alter_blogauthortranslation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='sort_order',
            field=models.IntegerField(null=True, verbose_name='Sort Order'),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='sort_order',
            field=models.IntegerField(null=True, verbose_name='Sort Order'),
        ),
    ]
