# Generated by Django 6.0.8 on 2026-08-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_alter_blogcategory_sort_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='click_score',
            field=models.PositiveIntegerField(db_default=0, editable=False, help_text='Search click-through ranking signal - trailing-window click count refreshed by search.tasks.update_click_scores', verbose_name='Click Score'),
        ),
    ]
