# Generated by Django 6.0.8 on 2026-08-29 09:53

import functools

import core.fields.plain_text
from core.fields.plain_text import normalize_plain_text
from django.db import migrations


def _strip_markup(apps, schema_editor, app_label, model_names):
    """Backfill: reduce stored seo_description values to plain text.

    Rows written before ``PlainTextField`` could hold pasted rich text
    (40% of Webside's blog posts carried a ``<div>`` wrapper), which the
    storefront emitted verbatim into ``<meta name="description">``.
    Historical (simple_history) tables are deliberately untouched — they
    record what was stored at the time.
    """
    for model_name in model_names:
        model = apps.get_model(app_label, model_name)
        updates = []
        for obj in model.objects.exclude(seo_description="").only(
            "pk", "seo_description"
        ):
            cleaned = normalize_plain_text(obj.seo_description)
            if cleaned != obj.seo_description:
                obj.seo_description = cleaned
                updates.append(obj)
        if updates:
            model.objects.bulk_update(
                updates, ["seo_description"], batch_size=500
            )


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_blogpost_click_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='seo_description',
            field=core.fields.plain_text.PlainTextField(blank=True, default='', max_length=300, verbose_name='Seo Description'),
        ),
        migrations.RunPython(
            functools.partial(
                _strip_markup,
                app_label='blog',
                model_names=['BlogPost'],
            ),
            migrations.RunPython.noop,
            elidable=True,
        ),
    ]
