# Generated by Django 6.0.8 on 2026-09-27 12:37

import core.fields.rich_text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_remove_shared_seo_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposttranslation',
            name='body',
            field=core.fields.rich_text.RichTextField(blank=True, null=True, verbose_name='Body'),
        ),
    ]
