# Generated by Django 6.0.8 on 2026-09-28 05:29

import re

import core.fields.rich_text
from django.db import migrations
from django.utils.html import linebreaks

# A tag opener — the mark of a bio already converted (or written in the
# editor). Plain text such as "Tom <3" has no letter after its "<".
_HTML_TAG = re.compile(r"<[A-Za-z/!]")


def _plain_bio_to_rich_text(apps, schema_editor):
    """Backfill: turn each stored plain-text bio into the rich text it
    now is.

    The bio was a plain textarea, so its paragraphs are blank-line
    separated text. Rendered as HTML that text would collapse into one
    block — the bug a merchant reported on the author page. Django's
    ``linebreaks`` escapes the text and makes each blank-line block a
    ``<p>`` and each single newline a ``<br>``, which is what the
    rich-text editor stores for the same content.

    Values and a queryset ``update`` per row, never model instances:
    parler's translation model reads its master in ``__init__``, so a
    row loaded with ``.only()`` recurses into ``refresh_from_db``. One
    row per author translation — a handful per store.

    Idempotent: a bio that already holds markup is left alone, so
    reversing to 0038 (a no-op) and re-applying never escapes converted
    HTML into ``&lt;p&gt;``.
    """
    model = apps.get_model("blog", "BlogAuthorTranslation")
    rows = (
        model.objects.exclude(bio__isnull=True)
        .exclude(bio="")
        .values_list("pk", "bio")
    )
    for pk, bio in list(rows):
        if _HTML_TAG.search(bio):
            continue
        model.objects.filter(pk=pk).update(
            bio=linebreaks(bio.strip(), autoescape=True)
        )


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_rich_text_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogauthortranslation',
            name='bio',
            field=core.fields.rich_text.RichTextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.RunPython(
            _plain_bio_to_rich_text,
            migrations.RunPython.noop,
            elidable=True,
        ),
    ]
