# Generated by Django 4.2 on 2023-04-13 23:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=40, unique=True)),
                ("url", models.CharField(blank=True, max_length=255, null=True)),
                ("title", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/sliders/"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/sliders/thumbnails/"
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="uploads/sliders/videos/"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sliders",
            },
        ),
        migrations.CreateModel(
            name="Slide",
            fields=[
                (
                    "sort_order",
                    models.IntegerField(db_index=True, editable=False, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("url", models.CharField(blank=True, max_length=255, null=True)),
                ("title", models.CharField(blank=True, max_length=40, null=True)),
                ("subtitle", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
                ),
                (
                    "button_label",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("show_button", models.BooleanField(default=True)),
                ("date_start", models.DateTimeField()),
                ("date_end", models.DateTimeField()),
                ("order_position", models.IntegerField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/slides/"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="uploads/slides/thumbnails/"
                    ),
                ),
                (
                    "slider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slide_slider",
                        to="slider.slider",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Slides",
                "ordering": ("order_position",),
            },
        ),
    ]
