# Generated by Django 5.0.6 on 2024-07-02 13:39
from django.db import migrations

import core.fields.image


class Migration(migrations.Migration):
    dependencies = [
        ("slider", "0004_alter_slide_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slide",
            name="image",
            field=core.fields.image.ImageAndSvgField(
                blank=True, null=True, upload_to="uploads/slides/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="slider",
            name="image",
            field=core.fields.image.ImageAndSvgField(
                blank=True, null=True, upload_to="uploads/sliders/", verbose_name="Image"
            ),
        ),
    ]
