# Generated by Django 5.2.1 on 2025-05-14 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0007_alter_slide_sort_order'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='slide',
            new_name='slide_created_at_ix',
            old_name='slide_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='slide',
            new_name='slide_updated_at_ix',
            old_name='slide_updated_at_idx',
        ),
        migrations.RenameIndex(
            model_name='slide',
            new_name='slide_sort_order_ix',
            old_name='slide_sort_order_idx',
        ),
        migrations.RenameIndex(
            model_name='slide',
            new_name='slider_slide_date_start_ix',
            old_name='slider_slid_date_st_65e1d1_btree',
        ),
        migrations.RenameIndex(
            model_name='slide',
            new_name='slider_slide_date_end_ix',
            old_name='slider_slid_date_en_f1dc56_btree',
        ),
        migrations.RenameIndex(
            model_name='slider',
            new_name='slider_created_at_ix',
            old_name='slider_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='slider',
            new_name='slider_updated_at_ix',
            old_name='slider_updated_at_idx',
        ),
    ]
