# Generated by Django 5.2.1 on 2025-05-23 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0008_rename_slide_created_at_idx_slide_created_at_ix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='thumbnail',
        ),
    ]
