# Generated by Django 5.0.4 on 2024-04-11 11:43
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("region", "0002_region_region_created_at_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="region",
            options={
                "ordering": ["-sort_order"],
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
            },
        ),
    ]
