# Generated by Django 6.0.5 on 2026-05-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0006_rename_region_created_at_idx_region_created_at_ix_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='regiontranslation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='regiontranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='region_region_translation_uniq_lang'),
        ),
    ]
