# Generated by Django 6.0.8 on 2026-08-25 07:33

import django.contrib.postgres.indexes
import django.db.models.deletion
import djmoney.models.fields
import parler.fields
import parler.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0012_add_price_at_add_to_cartitem'),
        ('order', '0047_order_discount_amount_order_discount_amount_currency_and_more'),
        ('product', '0041_alter_historicalproduct_history_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trigger', models.CharField(choices=[('AUTOMATIC', 'Automatic'), ('CODE', 'Coupon code')], default='CODE', help_text='Automatic promotions apply to every eligible cart; code promotions require the shopper to enter a coupon code', max_length=10, verbose_name='Trigger')),
                ('benefit_type', models.CharField(choices=[('PERCENTAGE', 'Percentage off'), ('FIXED_AMOUNT', 'Fixed amount off'), ('FREE_SHIPPING', 'Free shipping')], default='PERCENTAGE', max_length=20, verbose_name='Benefit Type')),
                ('benefit_value', models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Percent (0-100) for percentage benefits, EUR amount for fixed-amount benefits; ignored for free shipping', max_digits=11, verbose_name='Benefit Value')),
                ('target_scope', models.CharField(choices=[('ORDER', 'Entire order'), ('PRODUCTS', 'Specific products'), ('CATEGORIES', 'Specific categories')], default='ORDER', max_length=10, verbose_name='Target Scope')),
                ('min_subtotal_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3, null=True)),
                ('min_subtotal', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, help_text='Cart items total (incl. VAT) required for the promotion to apply', max_digits=11, null=True, verbose_name='Minimum Subtotal')),
                ('first_order_only', models.BooleanField(default=False, help_text='Apply only to customers with no previous orders. For guests this is checked against the checkout email and is best-effort.', verbose_name='First Order Only')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Starts At')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Ends At')),
                ('stackable', models.BooleanField(default=False, help_text='Stackable promotions combine with each other; a non-stackable promotion applies alone and only when it beats the combined stackable discount. Ignored for free shipping, which always combines.', verbose_name='Stackable')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Lower numbers apply first among stackable promotions', verbose_name='Priority')),
                ('max_discount_amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3, null=True)),
                ('max_discount_amount', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, help_text='Ceiling for the discount of a single application', max_digits=11, null=True, verbose_name='Maximum Discount Amount')),
                ('usage_limit_total', models.PositiveIntegerField(blank=True, help_text='Maximum number of orders that may use this promotion', null=True, verbose_name='Total Usage Limit')),
                ('usage_limit_per_customer', models.PositiveIntegerField(blank=True, null=True, verbose_name='Per-customer Usage Limit')),
                ('categories', models.ManyToManyField(blank=True, help_text="Only used when target scope is 'Specific categories'; subcategories are included automatically", related_name='promotions', to='product.productcategory')),
                ('products', models.ManyToManyField(blank=True, help_text="Only used when target scope is 'Specific products'", related_name='promotions', to='product.product')),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotions',
                'db_table': 'promotion',
                'ordering': ['-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PromotionCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Case-insensitive; stored uppercase', max_length=40, unique=True, verbose_name='Code')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Maximum number of orders that may use this specific code (1 for single-use bulk codes); empty means unlimited', null=True, verbose_name='Usage Limit')),
                ('assigned_to_email', models.EmailField(blank=True, default='', help_text='When set, only checkouts with this email can redeem the code — covers guests without an account', max_length=254, verbose_name='Assigned To Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='When set, only this customer can redeem the code (personal coupon)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_promotion_codes', to=settings.AUTH_USER_MODEL)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='promotion.promotion')),
            ],
            options={
                'verbose_name': 'Promotion Code',
                'verbose_name_plural': 'Promotion Codes',
                'db_table': 'promotion_code',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartPromotionCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_codes', to='cart.cart')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_applications', to='promotion.promotioncode')),
            ],
            options={
                'verbose_name': 'Cart Promotion Code',
                'verbose_name_plural': 'Cart Promotion Codes',
                'db_table': 'promotion_cart_code',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionRedemption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, default='', help_text='Checkout email — used for guest per-customer limits', max_length=254, verbose_name='Email')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=11, verbose_name='Amount')),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to='promotion.promotioncode')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_redemptions', to='order.order')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='promotion.promotion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promotion Redemption',
                'verbose_name_plural': 'Promotion Redemptions',
                'db_table': 'promotion_redemption',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('master', parler.fields.TranslationsForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='promotion.promotion')),
            ],
            options={
                'db_table': 'promotion_translation',
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='promotion_created_at_ix'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['updated_at'], name='promotion_updated_at_ix'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['is_active', 'starts_at', 'ends_at'], name='promotion_live_ix'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['trigger'], name='promotion_trigger_ix'),
        ),
        migrations.AddIndex(
            model_name='promotioncode',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='promotioncode_created_at_ix'),
        ),
        migrations.AddIndex(
            model_name='promotioncode',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['updated_at'], name='promotioncode_updated_at_ix'),
        ),
        migrations.AddIndex(
            model_name='promotioncode',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['promotion'], name='promotion_code_promo_ix'),
        ),
        migrations.AddConstraint(
            model_name='cartpromotioncode',
            constraint=models.UniqueConstraint(fields=('cart', 'code'), name='unique_code_per_cart'),
        ),
        migrations.AddIndex(
            model_name='promotionredemption',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='promotionredemption_created_at_ix'),
        ),
        migrations.AddIndex(
            model_name='promotionredemption',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['updated_at'], name='promotionredemption_updated_at_ix'),
        ),
        migrations.AddIndex(
            model_name='promotionredemption',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['promotion', 'user'], name='promo_redeem_user_ix'),
        ),
        migrations.AddIndex(
            model_name='promotionredemption',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['promotion', 'email'], name='promo_redeem_email_ix'),
        ),
        migrations.AddConstraint(
            model_name='promotionredemption',
            constraint=models.UniqueConstraint(fields=('promotion', 'order'), name='unique_promotion_per_order'),
        ),
        migrations.AlterUniqueTogether(
            name='promotiontranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
