# Generated by Django 6.0.8 on 2026-08-25 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='promotionredemption',
            new_name='promo_redeem_created_ix',
            old_name='promotionredemption_created_at_ix',
        ),
        migrations.RenameIndex(
            model_name='promotionredemption',
            new_name='promo_redeem_updated_ix',
            old_name='promotionredemption_updated_at_ix',
        ),
    ]
