# Generated by Django 6.0.8 on 2026-08-25 10:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_alter_historicalproduct_history_user_and_more'),
        ('promotion', '0002_rename_promotionredemption_created_at_ix_promo_redeem_created_ix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='buy_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='BXGY: eligible units the shopper must buy per application', null=True, verbose_name='Buy Quantity'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='exclude_discounted_products',
            field=models.BooleanField(default=False, help_text='Skip products that already carry a product-level markdown (discount percent > 0)', verbose_name='Exclude Already-discounted Products'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='excluded_categories',
            field=models.ManyToManyField(blank=True, help_text='Products in these categories (subcategories included) are never counted or discounted by this promotion', related_name='excluded_from_promotions', to='product.productcategory'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='excluded_products',
            field=models.ManyToManyField(blank=True, help_text='Never counted or discounted by this promotion, whatever the target scope', related_name='excluded_from_promotions', to='product.product'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='get_discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('100'), help_text="BXGY: discount applied to the 'get' units — 100 means free, 50 means half price", max_digits=5, verbose_name='Get Discount Percent'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='get_products',
            field=models.ManyToManyField(blank=True, help_text='BXGY: the reward pool (empty = same products as the buy side). FREE_GIFT: the gift product (set exactly one).', related_name='promotions_as_reward', to='product.product'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='get_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='BXGY: units discounted per application. FREE_GIFT: gift units added to the order', null=True, verbose_name='Get Quantity'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='min_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum number of ELIGIBLE units (after scope and exclusions) the cart must contain', null=True, verbose_name='Minimum Quantity'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='benefit_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage off'), ('FIXED_AMOUNT', 'Fixed amount off'), ('FREE_SHIPPING', 'Free shipping'), ('BXGY', 'Buy X get Y discounted'), ('FREE_GIFT', 'Free gift item')], default='PERCENTAGE', max_length=20, verbose_name='Benefit Type'),
        ),
    ]
