# Generated by Django 6.0.8 on 2026-10-01 00:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_field_verbose_names'),
        ('order', '0062_field_verbose_names'),
        ('product', '0048_field_verbose_names'),
        ('promotion', '0004_created_at_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartpromotioncode',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_codes', to='cart.cart', verbose_name='Cart'),
        ),
        migrations.AlterField(
            model_name='cartpromotioncode',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_applications', to='promotion.promotioncode', verbose_name='Promotion Code'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text="Only used when target scope is 'Specific categories'; subcategories are included automatically", related_name='promotions', to='product.productcategory', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='excluded_categories',
            field=models.ManyToManyField(blank=True, help_text='Products in these categories (subcategories included) are never counted or discounted by this promotion', related_name='excluded_from_promotions', to='product.productcategory', verbose_name='Excluded Categories'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='excluded_products',
            field=models.ManyToManyField(blank=True, help_text='Never counted or discounted by this promotion, whatever the target scope', related_name='excluded_from_promotions', to='product.product', verbose_name='Excluded Products'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='get_products',
            field=models.ManyToManyField(blank=True, help_text='BXGY: the reward pool (empty = same products as the buy side). FREE_GIFT: the gift product (set exactly one).', related_name='promotions_as_reward', to='product.product', verbose_name='Reward Products'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(blank=True, help_text="Only used when target scope is 'Specific products'", related_name='promotions', to='product.product', verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='promotioncode',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='When set, only this customer can redeem the code (personal coupon)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_promotion_codes', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AlterField(
            model_name='promotioncode',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='promotion.promotion', verbose_name='Promotion'),
        ),
        migrations.AlterField(
            model_name='promotionredemption',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to='promotion.promotioncode', verbose_name='Promotion Code'),
        ),
        migrations.AlterField(
            model_name='promotionredemption',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_redemptions', to='order.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='promotionredemption',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='promotion.promotion', verbose_name='Promotion'),
        ),
        migrations.AlterField(
            model_name='promotionredemption',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_redemptions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
