# Generated by Django 4.2 on 2023-04-13 23:50
import uuid

import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PayWay",
            fields=[
                (
                    "sort_order",
                    models.IntegerField(db_index=True, editable=False, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Credit Card", "CREDIT_CARD"),
                            ("Pay On Delivery", "PAY_ON_DELIVERY"),
                            ("Pay On Store", "PAY_ON_STORE"),
                            ("PayPal", "PAY_PAL"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
                ),
                (
                    "free_for_order_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
                ),
            ],
            options={
                "verbose_name_plural": "Payment Methods",
            },
        ),
    ]
