# Generated by Django 4.2.1 on 2023-05-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pay_way", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payway",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to="uploads/pay_way/"
            ),
        ),
    ]
