# Generated by Django 5.2.9 on 2026-01-17 15:54

import core.fields.image
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay_way', '0009_remove_payway_pay_way_free_order_ix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payway',
            name='icon',
            field=core.fields.image.ImageAndSvgField(blank=True, null=True, upload_to='uploads/products/', verbose_name='Icon'),
        ),
    ]
