# Generated by Django 6.0.5 on 2026-05-13 11:31

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay_way', '0012_alter_paywaytranslation_name'),
        ('shipping', '0005_seed_acs_print_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayWayShippingExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('shipping_kind', models.CharField(choices=[('home_delivery', 'Home delivery'), ('pickup_point', 'Pickup point / locker')], max_length=32, verbose_name='Shipping kind')),
                ('note', models.TextField(blank=True, default='', help_text="Optional explanation for why this combination is blocked (e.g. 'PAY ON THE GO not yet active on the BoxNow partner account — re-enable when ops confirms'). Visible to admins only — never shown to customers.", verbose_name='Note')),
                ('pay_way', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_exclusions', to='pay_way.payway', verbose_name='Pay way')),
                ('shipping_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_way_exclusions', to='shipping.shippingprovider', verbose_name='Shipping provider')),
            ],
            options={
                'verbose_name': 'PayWay shipping exclusion',
                'verbose_name_plural': 'PayWay shipping exclusions',
                'ordering': ['shipping_provider', 'shipping_kind', 'pay_way'],
                'indexes': [django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='payway_excl_created_at_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['updated_at'], name='payway_excl_updated_at_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['shipping_provider', 'shipping_kind'], name='payway_excl_provider_kind_ix')],
                'constraints': [models.UniqueConstraint(fields=('pay_way', 'shipping_provider', 'shipping_kind'), name='payway_shipping_exclusion_unique')],
            },
        ),
    ]
