# Generated by Django 6.0.5 on 2026-05-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay_way', '0013_paywayshippingexclusion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paywaytranslation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='paywaytranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='pay_way_payway_translation_uniq_lang'),
        ),
    ]
