# Generated by Django 6.0.7 on 2026-07-11 18:18

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay_way', '0015_alter_payway_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paywaytranslation',
            name='instructions',
            field=tinymce.models.HTMLField(blank=True, help_text='Instructions for the customer on how to complete payment (e.g., bank transfer details)', null=True, verbose_name='Payment Instructions'),
        ),
    ]
