# Generated by Django 6.0.8 on 2026-08-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay_way', '0017_alter_payway_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payway',
            name='configuration',
            field=models.JSONField(blank=True, help_text='Provider-specific non-secret configuration only (display options, callback URLs, feature flags). Secrets — API keys, webhook secrets, OAuth client_secrets — live on the Tenant model fields (stripe_secret_key, viva_wallet_*, acs_*, box_now_*, meta_capi_*) so they can be scoped per-tenant and rotated independently. Keys matching common secret patterns are rejected at save time.', null=True, verbose_name='Provider Configuration'),
        ),
    ]
