# Generated by Django 6.0.8 on 2026-09-08 18:28

import django.contrib.postgres.indexes
from django.db import migrations, models


def backfill_settlement(apps, schema_editor):
    """Derive ``settlement`` for every existing row.

    ``AddField`` above stamps the model default (``online``) onto every
    existing row, which is wrong for all of them except the online
    providers — left alone, the seeded ``cash_on_delivery`` pay-way
    would come out of this migration claiming to be paid online, and
    every COD order would mint a PREPAID voucher collecting nothing.
    So the mapping has to run in the same migration as the AddField.

    Mirrors the definition the booleans encoded before ``settlement``
    existed (see ``PaySettlement`` for why one boolean could not tell
    courier-cash and carrier-terminal apart):

        is_online_payment                        -> ONLINE
        else requires_confirmation               -> OFFLINE_TRANSFER
        else                                     -> COURIER_CASH

    Nothing maps to ``CARRIER_TERMINAL``: no pay-way could have meant
    it before this migration, because the product it represents
    (BoxNow PAY ON THE GO) had no pay-way of its own — that is the bug
    this model change exists to fix. It is seeded separately.
    """
    PayWay = apps.get_model("pay_way", "PayWay")
    db = schema_editor.connection.alias

    PayWay.objects.using(db).filter(is_online_payment=True).update(
        settlement="online"
    )
    PayWay.objects.using(db).filter(
        is_online_payment=False, requires_confirmation=True
    ).update(settlement="offline_transfer")
    PayWay.objects.using(db).filter(
        is_online_payment=False, requires_confirmation=False
    ).update(settlement="courier_cash")


def unbackfill_settlement(apps, schema_editor):
    """No-op reverse: ``settlement`` is dropped by the AddField reversal.

    The booleans are never modified by the forward pass, so there is
    nothing to restore.
    """
    return


class Migration(migrations.Migration):

    dependencies = [
        ('pay_way', '0019_seed_default_pay_ways'),
    ]

    operations = [
        migrations.AddField(
            model_name='payway',
            name='settlement',
            field=models.CharField(choices=[('online', 'Paid online at checkout'), ('courier_cash', 'Cash or card to the courier on delivery'), ('carrier_terminal', "Card at the carrier's terminal on pickup"), ('offline_transfer', 'Settled off-platform (e.g. bank transfer)')], default='online', help_text="How the money changes hands. This is the authoritative discriminator for the shipping layer: a carrier declares which settlements it can physically perform, and the voucher's payment mode derives from it. Do not re-derive it from the deprecated booleans below.", max_length=32, verbose_name='Settlement'),
        ),
        migrations.RunPython(
            backfill_settlement,
            unbackfill_settlement,
            elidable=False,
        ),
        migrations.AlterField(
            model_name='payway',
            name='is_online_payment',
            field=models.BooleanField(default=False, help_text='Deprecated mirror of ``settlement == ONLINE``. Dropped in the release after settlement lands.', verbose_name='Is Online Payment'),
        ),
        migrations.AlterField(
            model_name='payway',
            name='requires_confirmation',
            field=models.BooleanField(default=False, help_text='Deprecated mirror of ``settlement == OFFLINE_TRANSFER``. Dropped in the release after settlement lands.', verbose_name='Requires Confirmation'),
        ),
        migrations.AddIndex(
            model_name='payway',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['settlement'], name='pay_way_settlement_ix'),
        ),
    ]
