# Generated by Django 6.0.8 on 2026-09-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    """Relabel CARRIER_TERMINAL. Choices only — no DDL.

    The label said "Card at the carrier's terminal on pickup". BOX NOW
    Αντικαταβολή has no terminal and takes no card at the locker: the
    carrier sends a payment link after dispatch and activates the
    pickup PIN once it clears. The wrong wording was admin-visible and
    baked into schema.yml, and it had already misled a change.

    The VALUE stays ``carrier_terminal`` — what the member
    discriminates is who collects and when, which is unchanged, and
    renaming it would be a data migration for no behavioural gain.

    Django does not enforce choices at the database level, so
    ``sqlmigrate`` reports ``(no-op)``: nothing to lock, safe under the
    PreSync hook regardless of table size.
    """


    dependencies = [
        ('pay_way', '0023_purge_stale_potg_translation_cache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payway',
            name='settlement',
            field=models.CharField(choices=[('online', 'Paid online at checkout'), ('courier_cash', 'Cash or card to the courier on delivery'), ('carrier_terminal', 'Paid to the carrier before pickup'), ('offline_transfer', 'Settled off-platform (e.g. bank transfer)')], default='online', help_text="How the money changes hands. This is the authoritative discriminator for the shipping layer: a carrier declares which settlements it can physically perform, and the voucher's payment mode derives from it. Do not re-derive it from the deprecated booleans below.", max_length=32, verbose_name='Settlement'),
        ),
    ]
