# Generated by Django 6.0.8 on 2026-09-27 12:37

import core.fields.rich_text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay_way', '0024_alter_payway_settlement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paywaytranslation',
            name='instructions',
            field=core.fields.rich_text.RichTextField(blank=True, help_text='Instructions for the customer on how to complete payment (e.g., bank transfer details)', null=True, verbose_name='Payment Instructions'),
        ),
    ]
