# Generated by Django 6.0.8 on 2026-09-29 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0012_seed_iso_countries'),
        ('pay_way', '0025_rich_text_field'),
        ('shipping', '0015_drop_map_metadata'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paywayshippingexclusion',
            name='payway_shipping_exclusion_unique',
        ),
        migrations.AddField(
            model_name='paywayshippingexclusion',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Delivery country this exclusion applies to. Leave empty to exclude the pay way for every country.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='country.country', verbose_name='Country'),
        ),
        migrations.AddConstraint(
            model_name='paywayshippingexclusion',
            constraint=models.UniqueConstraint(fields=('pay_way', 'shipping_provider', 'shipping_kind', 'country'), name='payway_shipping_exclusion_unique', nulls_distinct=False),
        ),
    ]
