# Generated by Django 6.0.8 on 2026-08-25 08:13

import django.contrib.postgres.indexes
import django.db.models.deletion
import djmoney.models.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0047_order_discount_amount_order_discount_amount_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCardPurchase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('buyer_email', models.EmailField(max_length=254, verbose_name='Buyer Email')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=11, verbose_name='Amount')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Recipient Email')),
                ('recipient_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Recipient Name')),
                ('sender_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Sender Name')),
                ('message', models.TextField(blank=True, default='', verbose_name='Message')),
                ('deliver_at', models.DateTimeField(blank=True, help_text='Empty means deliver immediately after payment', null=True, verbose_name='Deliver At')),
                ('status', models.CharField(choices=[('PENDING', 'Pending payment'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], default='PENDING', max_length=10, verbose_name='Status')),
                ('provider_code', models.CharField(blank=True, default='', max_length=50, verbose_name='Provider Code')),
                ('payment_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Payment ID')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_card_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gift Card Purchase',
                'verbose_name_plural': 'Gift Card Purchases',
                'db_table': 'giftcard_purchase',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Crypto-random, uppercased; the bearer secret', max_length=32, unique=True, verbose_name='Code')),
                ('initial_value_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3)),
                ('initial_value', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=11, verbose_name='Initial Value')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled')], default='ACTIVE', max_length=10, verbose_name='Status')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Defaults to GIFT_CARD_VALIDITY_DAYS after issue (Greek law: 5 years); empty means never expires', null=True, verbose_name='Expires At')),
                ('source', models.CharField(choices=[('ADMIN', 'Issued by admin'), ('PURCHASE', 'Purchased in store')], default='ADMIN', max_length=10, verbose_name='Source')),
                ('recipient_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Recipient Email')),
                ('recipient_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Recipient Name')),
                ('sender_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Sender Name')),
                ('message', models.TextField(blank=True, default='', verbose_name='Message')),
                ('deliver_at', models.DateTimeField(blank=True, null=True, verbose_name='Deliver At')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered At')),
                ('issued_to', models.ForeignKey(blank=True, help_text="Optional account link — lets the shopper see the card under 'My gift cards'. Redemption only needs the code.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_cards', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_cards', to='giftcard.giftcardpurchase')),
            ],
            options={
                'verbose_name': 'Gift Card',
                'verbose_name_plural': 'Gift Cards',
                'db_table': 'giftcard',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GiftCardTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('ISSUE', 'Issue'), ('REDEEM', 'Redeem'), ('REFUND_CREDIT', 'Refund credit'), ('ADJUST', 'Adjust'), ('EXPIRE', 'Expire')], max_length=15, verbose_name='Kind')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Signed: positive adds balance (issue/refund credit), negative removes it (redeem/expire)', max_digits=11, verbose_name='Amount')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Description')),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who made a manual adjustment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_card_adjustments_made', to=settings.AUTH_USER_MODEL)),
                ('gift_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='giftcard.giftcard')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_card_transactions', to='order.order')),
            ],
            options={
                'verbose_name': 'Gift Card Transaction',
                'verbose_name_plural': 'Gift Card Transactions',
                'db_table': 'giftcard_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='giftcardpurchase',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='giftcardpurchase_created_at_ix'),
        ),
        migrations.AddIndex(
            model_name='giftcardpurchase',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['updated_at'], name='giftcardpurchase_updated_at_ix'),
        ),
        migrations.AddIndex(
            model_name='giftcardpurchase',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['status'], name='giftcard_purchase_status_ix'),
        ),
        migrations.AddIndex(
            model_name='giftcardpurchase',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['payment_id'], name='giftcard_purchase_payment_ix'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='giftcard_created_at_ix'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['updated_at'], name='giftcard_updated_at_ix'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['status'], name='giftcard_status_ix'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['issued_to'], name='giftcard_issued_to_ix'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['expires_at'], name='giftcard_expires_ix'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['recipient_email'], name='giftcard_recipient_ix'),
        ),
        migrations.AddIndex(
            model_name='giftcardtransaction',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='giftcardtransaction_created_at_ix'),
        ),
        migrations.AddIndex(
            model_name='giftcardtransaction',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['updated_at'], name='giftcardtransaction_updated_at_ix'),
        ),
        migrations.AddIndex(
            model_name='giftcardtransaction',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['gift_card'], name='giftcard_tx_card_ix'),
        ),
        migrations.AddIndex(
            model_name='giftcardtransaction',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['kind'], name='giftcard_tx_kind_ix'),
        ),
        migrations.AddIndex(
            model_name='giftcardtransaction',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['order'], name='giftcard_tx_order_ix'),
        ),
        migrations.AddConstraint(
            model_name='giftcardtransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'REDEEM')), fields=('gift_card', 'order'), name='unique_giftcard_redeem_per_order'),
        ),
    ]
