# Generated by Django 6.0.8 on 2026-08-25 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='giftcardtransaction',
            new_name='giftcard_tx_created_ix',
            old_name='giftcardtransaction_created_at_ix',
        ),
        migrations.RenameIndex(
            model_name='giftcardtransaction',
            new_name='giftcard_tx_updated_ix',
            old_name='giftcardtransaction_updated_at_ix',
        ),
    ]
