# Generated by Django 6.0.8 on 2026-08-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0002_rename_giftcardtransaction_created_at_ix_giftcard_tx_created_ix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='expiry_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Stamped by the daily reminder sweep so each card is reminded exactly once', null=True, verbose_name='Expiry Reminder Sent At'),
        ),
    ]
