# Generated by Django 6.0.8 on 2026-08-25 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0003_giftcard_expiry_reminder_sent_at'),
        ('order', '0047_order_discount_amount_order_discount_amount_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='giftcardtransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'REFUND_CREDIT')), fields=('gift_card', 'order'), name='unique_giftcard_refund_per_order'),
        ),
    ]
