# Generated by Django 6.0.8 on 2026-10-01 00:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0004_giftcardtransaction_unique_giftcard_refund_per_order'),
        ('order', '0062_field_verbose_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcard',
            name='issued_to',
            field=models.ForeignKey(blank=True, help_text="Optional account link — lets the shopper see the card under 'My gift cards'. Redemption only needs the code.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_cards', to=settings.AUTH_USER_MODEL, verbose_name='Issued To'),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_cards', to='giftcard.giftcardpurchase', verbose_name='Purchase'),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='giftcardpurchase',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_card_purchases', to=settings.AUTH_USER_MODEL, verbose_name='Buyer'),
        ),
        migrations.AlterField(
            model_name='giftcardpurchase',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='giftcardtransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin who made a manual adjustment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_card_adjustments_made', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='giftcardtransaction',
            name='gift_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='giftcard.giftcard', verbose_name='Gift Card'),
        ),
        migrations.AlterField(
            model_name='giftcardtransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_card_transactions', to='order.order', verbose_name='Order'),
        ),
    ]
