# Generated by Django 5.2 on 2025-04-17 13:12

import uuid
from django.conf import settings
from django.db import migrations, models

def populate_session_key(apps, schema_editor):
    Cart = apps.get_model('cart', 'Cart')
    for cart in Cart.objects.filter(session_key__isnull=True):
        cart.session_key = str(uuid.uuid4())
        cart.save()

class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_remove_cart_cart_created_at_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(populate_session_key),  # Populate existing NULL session_key with uuid
        migrations.AddField(
            model_name='cart',
            name='session_key',
            field=models.CharField(
                blank=True,
                help_text='Session key for guest users',
                max_length=40,
                null=False,  # Make the field non-nullable
                verbose_name='Session Key',
                default=str(uuid.uuid4()),  # Set a default value for new records
            ),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(
                condition=models.Q(session_key__isnull=False),
                fields=['session_key'],
                name='unique_session_cart',
            ),
        ),
    ]
