# Generated by Django 6.0.8 on 2026-09-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_add_price_at_add_to_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='recommendation_impression_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='Recommendation impression'),
        ),
    ]
