# Generated by Django 6.0.8 on 2026-09-10 17:05

import django.contrib.postgres.indexes
import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0043_product_relation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('surface', models.CharField(choices=[('pdp', 'Product page'), ('cart', 'Cart'), ('out_of_stock', 'Out of stock'), ('empty_cart', 'Empty cart'), ('order_email', 'Order email')], max_length=20, unique=True, verbose_name='Surface')),
                ('strategy_chain', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Ordered list of strategy codes. Each fills the remaining slots in turn; a strategy that cannot answer for this store is skipped.', verbose_name='Strategy chain')),
                ('weights', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Strategy code → weight in 0..1. Missing codes default to 1.0. Updated nightly from attach rate on plans that learn.', verbose_name='Weights')),
                ('limit', models.PositiveSmallIntegerField(default=4, verbose_name='Limit')),
                ('min_fill', models.PositiveSmallIntegerField(default=2, help_text='Show nothing rather than fewer than this many suggestions.', verbose_name='Minimum fill')),
                ('price_band_ratio', models.DecimalField(blank=True, decimal_places=2, help_text="Drop candidates whose price is more than this many times the seed's, or less than 1/this. Empty disables the band.", max_digits=4, null=True, verbose_name='Price band ratio')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
            ],
            options={
                'verbose_name': 'Recommendation slot',
                'verbose_name_plural': 'Recommendation slots',
                'ordering': ['surface'],
                'indexes': [django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='recommendationslot_created_at_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['updated_at'], name='recommendationslot_updated_at_ix')],
            },
        ),
        migrations.CreateModel(
            name='RecommendationCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('curated', 'Merchant curated'), ('variant_group', 'Same variant group'), ('category', 'Same category'), ('attributes', 'Shared attributes, tags and brand'), ('semantic', 'Semantic similarity'), ('co_purchase', 'Bought together'), ('co_view', 'Viewed together'), ('popular', 'Popular')], max_length=20, verbose_name='Strategy')),
                ('score', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='Score')),
                ('relation_type', models.CharField(blank=True, choices=[('similar', 'Similar product'), ('complementary', 'Goes well with'), ('accessory', 'Accessory for'), ('replacement', 'Replacement for'), ('bundle', 'Bundle with')], default='', max_length=20, verbose_name='Relation type')),
                ('computed_at', models.DateTimeField(auto_now=True, verbose_name='Computed at')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='product.product', verbose_name='Candidate')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_candidates', to='product.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Recommendation candidate',
                'verbose_name_plural': 'Recommendation candidates',
                'indexes': [django.contrib.postgres.indexes.BTreeIndex(fields=['product', 'strategy', '-score'], name='rec_candidate_read_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['computed_at'], name='rec_candidate_at_ix')],
                'constraints': [models.UniqueConstraint(fields=('product', 'candidate', 'strategy'), name='recommendation_candidate_unique'), models.CheckConstraint(condition=models.Q(('product', models.F('candidate')), _negated=True), name='recommendation_candidate_not_self')],
            },
        ),
        migrations.CreateModel(
            name='RecommendationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface', models.CharField(choices=[('pdp', 'Product page'), ('cart', 'Cart'), ('out_of_stock', 'Out of stock'), ('empty_cart', 'Empty cart'), ('order_email', 'Order email')], max_length=20, verbose_name='Surface')),
                ('strategy', models.CharField(choices=[('curated', 'Merchant curated'), ('variant_group', 'Same variant group'), ('category', 'Same category'), ('attributes', 'Shared attributes, tags and brand'), ('semantic', 'Semantic similarity'), ('co_purchase', 'Bought together'), ('co_view', 'Viewed together'), ('popular', 'Popular')], max_length=20, verbose_name='Strategy')),
                ('kind', models.CharField(choices=[('impression', 'Impression'), ('click', 'Click'), ('attach', 'Attach')], max_length=12, verbose_name='Kind')),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Position')),
                ('impression_id', models.UUIDField(db_index=True, verbose_name='Impression')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Session key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_events', to='product.product', verbose_name='Product')),
                ('seed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='product.product', verbose_name='Seed product')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Recommendation event',
                'verbose_name_plural': 'Recommendation events',
                'ordering': ['-created_at'],
                'indexes': [django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='rec_event_created_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['kind', 'created_at'], name='rec_event_kind_at_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['surface', 'strategy', 'kind'], name='rec_event_surface_strategy_ix')],
            },
        ),
    ]
