# Generated by Django 6.0.8 on 2026-09-10 20:50

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationslot',
            name='weights',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Strategy code → weight in 0..1. Missing codes default to 1.0. Updated nightly from attach rate on plans that learn.', verbose_name='Weights'),
        ),
    ]
