# Generated by Django 6.0.8 on 2026-09-11 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0055_order_pay_way_key_snapshot'),
        ('product', '0043_product_relation'),
        ('recommendation', '0002_slot_weights_blank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationevent',
            name='cart_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Cart'),
        ),
        migrations.AddField(
            model_name='recommendationevent',
            name='matched_by',
            field=models.CharField(blank=True, choices=[('cart', 'Same cart'), ('user', 'Same customer')], default='', max_length=8, verbose_name='Matched by'),
        ),
        migrations.AddField(
            model_name='recommendationevent',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_events', to='order.order', verbose_name='Order'),
        ),
        migrations.AddConstraint(
            model_name='recommendationevent',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'attach')), fields=('order', 'product', 'impression_id'), name='rec_event_attach_unique'),
        ),
    ]
