# Generated by Django 6.0.8 on 2026-09-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_event_attach_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationevent',
            name='matched_by',
            field=models.CharField(blank=True, choices=[('impression', 'Carried from add to cart'), ('cart', 'Same cart'), ('user', 'Same customer')], default='', max_length=12, verbose_name='Matched by'),
        ),
    ]
