# Generated by Django 6.0.8 on 2026-09-30 23:11

import core.json_schema
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0004_attach_match_impression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationslot',
            name='strategy_chain',
            field=models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Ordered list of strategy codes. Each fills the remaining slots in turn; a strategy that cannot answer for this store is skipped.', validators=[core.json_schema.JSONSchemaValidator('recommendation.json_schemas.strategy_chain')], verbose_name='Strategy chain'),
        ),
        migrations.AlterField(
            model_name='recommendationslot',
            name='weights',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Strategy code → weight in 0..1. Missing codes default to 1.0. Updated nightly from attach rate on plans that learn.', validators=[core.json_schema.JSONSchemaValidator('recommendation.json_schemas.weights')], verbose_name='Weights'),
        ),
    ]
