# Generated by Django 6.0.4 on 2026-04-24 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='user_agent',
            field=models.TextField(blank=True, help_text='User agent string from the request', null=True, validators=[django.core.validators.MaxLengthValidator(512)]),
        ),
    ]
