# Generated by Django 6.0.8 on 2026-08-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_searchquery_user_agent_maxlen'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='uuid',
            field=models.UUIDField(editable=False, help_text='Public identifier echoed to the client as ``query_id`` so a later click can be attributed to this query. Nullable because rows predating click tracking have none.', null=True, unique=True),
        ),
    ]
