# Generated by Django 6.0.8 on 2026-10-01 00:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_searchquery_language_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchclick',
            name='position',
            field=models.IntegerField(help_text='Position of the result in search results (0-indexed)', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='searchclick',
            name='result_id',
            field=models.CharField(help_text='ID of the clicked result (Product or BlogPost ID)', max_length=100, verbose_name='Result ID'),
        ),
        migrations.AlterField(
            model_name='searchclick',
            name='result_type',
            field=models.CharField(choices=[('product', 'Product'), ('blog_post', 'Blog Post')], help_text='Type of result that was clicked', max_length=20, verbose_name='Result Type'),
        ),
        migrations.AlterField(
            model_name='searchclick',
            name='search_query',
            field=models.ForeignKey(help_text='The search query that led to this click', on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='search.searchquery', verbose_name='Search Query'),
        ),
        migrations.AlterField(
            model_name='searchclick',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the click occurred', verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='content_type',
            field=models.CharField(choices=[('product', 'Product'), ('blog_post', 'Blog Post'), ('federated', 'Federated')], db_index=True, help_text='Type of content being searched', max_length=20, verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='estimated_total_hits',
            field=models.IntegerField(help_text='Estimated total number of matching documents', verbose_name='Estimated Total Hits'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='language_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Language code for the search (e.g., 'en', 'el', 'de')", max_length=10, null=True, verbose_name='Language Code'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='processing_time_ms',
            field=models.IntegerField(blank=True, help_text='Time taken to process the search in milliseconds', null=True, verbose_name='Processing Time (ms)'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='query',
            field=models.CharField(db_index=True, help_text='The search query text entered by the user', max_length=500, verbose_name='Query'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='results_count',
            field=models.IntegerField(db_index=True, help_text='Number of results returned', verbose_name='Results Count'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='session_key',
            field=models.CharField(blank=True, default='', help_text='Session key for anonymous users', max_length=40, null=True, verbose_name='Session Key'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the search was performed', verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who performed the search (if authenticated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_queries', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='user_agent',
            field=models.TextField(blank=True, default='', help_text='User agent string from the request', null=True, validators=[django.core.validators.MaxLengthValidator(512)], verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='uuid',
            field=models.UUIDField(editable=False, help_text='Public identifier echoed to the client as ``query_id`` so a later click can be attributed to this query. Nullable because rows predating click tracking have none.', null=True, unique=True, verbose_name='UUID'),
        ),
    ]
