# Generated by Django 4.2.9 on 2024-03-01 13:54
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="useraddress",
            options={
                "ordering": ["-is_main", "-created_at"],
                "verbose_name": "User Address",
                "verbose_name_plural": "User Addresses",
            },
        ),
    ]
