# Generated by Django 4.2 on 2023-04-28 11:23
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="phone",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
