# Generated by Django 4.2.1 on 2023-05-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_useraccount_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
