# Generated by Django 5.0.3 on 2024-03-31 12:31
import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("country", "0002_country_country_created_at_idx_and_more"),
        ("region", "0002_region_region_created_at_idx_and_more"),
        ("user", "0003_useraddress_address_search_gin"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="useraccount",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["created_at"], name="useraccount_created_at_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useraccount",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["updated_at"], name="useraccount_updated_at_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useraccount",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=[
                    "email",
                    "first_name",
                    "last_name",
                    "phone",
                    "city",
                    "zipcode",
                    "address",
                    "place",
                ],
                name="user_account_trgm_idx",
                opclasses=[
                    "gin_trgm_ops",
                    "gin_trgm_ops",
                    "gin_trgm_ops",
                    "gin_trgm_ops",
                    "gin_trgm_ops",
                    "gin_trgm_ops",
                    "gin_trgm_ops",
                    "gin_trgm_ops",
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="useraddress",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["created_at"], name="useraddress_created_at_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useraddress",
            index=django.contrib.postgres.indexes.BTreeIndex(
                fields=["updated_at"], name="useraddress_updated_at_idx"
            ),
        ),
    ]
