# Generated by Django 5.0.4 on 2024-04-13 17:48
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_useraccount_useraccount_created_at_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="useraddress",
            options={
                "ordering": ["is_main", "-created_at"],
                "verbose_name": "User Address",
                "verbose_name_plural": "User Addresses",
            },
        ),
    ]
