# Generated by Django 5.0.6 on 2024-07-02 13:39
from django.db import migrations

import core.fields.image


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_alter_useraccount_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="image",
            field=core.fields.image.ImageAndSvgField(
                blank=True, null=True, upload_to="uploads/users/", verbose_name="Image"
            ),
        ),
    ]
