# Generated by Django 6.0.4 on 2026-04-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_useraccount_loyalty_tier_useraccount_total_xp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='last_reengagement_email_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent re-engagement email.', null=True, verbose_name='Last Re-engagement Email At'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='reengagement_email_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of re-engagement emails sent to this user.', verbose_name='Re-engagement Email Count'),
        ),
    ]
