# Generated by Django 6.0.4 on 2026-04-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_add_email_reminder_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='language_code',
            field=models.CharField(default='el', help_text='Preferred language for emails and UI messages.', max_length=10, verbose_name='Language'),
        ),
    ]
