# Generated by Django 6.0.4 on 2026-04-21 21:59

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_add_language_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=16, verbose_name='Status')),
                ('file_path', models.CharField(blank=True, default='', help_text='Path under MEDIA_ROOT/_private/exports/.', max_length=512, verbose_name='File Path')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='File Size (bytes)')),
                ('token', models.CharField(db_index=True, help_text='Random token carried by the download URL.', max_length=64, unique=True, verbose_name='Download Token')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the download link stops working.', null=True, verbose_name='Expires At')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Error Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_exports', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Data Export',
                'verbose_name_plural': 'User Data Exports',
                'ordering': ['-created_at'],
                'indexes': [django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='userdataexport_created_at_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['updated_at'], name='userdataexport_updated_at_ix'), models.Index(fields=['user', 'status'], name='user_userda_user_id_bdcba4_idx'), models.Index(fields=['expires_at'], name='user_userda_expires_3708e8_idx')],
            },
        ),
    ]
