# Generated by Django 6.0.5 on 2026-05-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_userdataexport'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptiontopictranslation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='subscriptiontopictranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='user_subscriptiontopic_translation_uniq_lang'),
        ),
    ]
