# Generated by Django 6.0.8 on 2026-09-09 03:20

import user.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_useraccount_facebook_alter_useraccount_github_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, help_text="Optional login handle — NOT the person's name, which belongs in First/Last name. Leave blank and one is generated from the email. 30 characters or fewer; letters, digits and @/./+/-/_ only (no spaces).", max_length=30, null=True, unique=True, validators=[user.validators.ExtendedUnicodeUsernameValidator()], verbose_name='Username'),
        ),
    ]
