# Generated by Django 6.0.8 on 2026-09-23 08:25
"""Guest newsletter subscriptions with a consent record.

Schema: ``UserSubscription`` rows may now be keyed by ``email`` alone
(the storefront newsletter form), with the consent and confirmation
evidence alongside; ``SubscriptionTopic`` holds at most one active
default newsletter topic.

Data, two steps:

- ``keep_one_default_newsletter_topic`` runs BEFORE that constraint is
  added. A schema holding several active default NEWSLETTER topics
  would otherwise fail the migration; the oldest (lowest pk) stays the
  default, the rest lose ``is_default`` and nothing else. Reverse is a
  no-op: which rows were defaults is not worth restoring into a state
  the constraint forbids.
- ``drop_confirmation_url_setting`` deletes the
  ``SUBSCRIPTION_CONFIRMATION_URL`` ``extra_settings`` row. The
  confirmation link is now a storefront page whose path is code, not
  store configuration (``user.utils.subscription
  .subscription_confirmation_url``); left behind, the row would sit in
  the admin Settings list editing nothing. Same shape as
  ``shipping/migrations/0006_drop_legacy_boxnow_enabled_setting.py``.
"""


import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


def keep_one_default_newsletter_topic(apps, _schema_editor):
    SubscriptionTopic = apps.get_model("user", "SubscriptionTopic")
    defaults = SubscriptionTopic.objects.filter(
        category="NEWSLETTER", is_default=True, is_active=True
    ).order_by("pk")
    keep = defaults.values_list("pk", flat=True).first()
    if keep is not None:
        defaults.exclude(pk=keep).update(is_default=False)


def drop_confirmation_url_setting(apps, _schema_editor):
    Setting = apps.get_model("extra_settings", "Setting")
    Setting.objects.filter(name="SUBSCRIPTION_CONFIRMATION_URL").delete()


def noop_reverse(apps, _schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_alter_useraccount_username'),
        # The Setting table must exist before its row is deleted.
        ('extra_settings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(drop_confirmation_url_setting, noop_reverse),
        migrations.AlterUniqueTogether(
            name='usersubscription',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='confirmation_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the current confirmation link was issued. The link expires a week later.', null=True, verbose_name='Confirmation Sent At'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmed At'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='confirmed_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Confirmed From IP'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='consent_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Consent IP'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='consent_text',
            field=models.TextField(blank=True, default='', help_text='The exact consent sentence shown to the subscriber.', verbose_name='Consent Text'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='consent_user_agent',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Consent User Agent'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='consented_at',
            field=models.DateTimeField(blank=True, help_text='When the subscriber submitted the consent.', null=True, verbose_name='Consented At'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='email',
            field=models.EmailField(blank=True, default='', help_text="The address submitted on the newsletter form. The recipient of a guest subscription; an account's subscription mails the account's own address.", max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='language',
            field=models.CharField(blank=True, default='', help_text='Language the subscription was made in; its emails use it.', max_length=10, verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='source',
            field=models.CharField(choices=[('NEWSLETTER_FORM', 'Newsletter form'), ('ACCOUNT', 'Account'), ('SIGNUP', 'Signup')], default='ACCOUNT', help_text='Where the subscription was made.', max_length=20, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='subscriptiontopic',
            name='is_default',
            field=models.BooleanField(default=False, help_text="Account and system topics: new users are subscribed automatically. Newsletter topic: the one the storefront newsletter form subscribes visitors to (at most one active). Topics of any other category are never subscribed automatically — they need the recipient's consent.", verbose_name='Default Subscription'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.RunPython(keep_one_default_newsletter_topic, noop_reverse),
        migrations.AddConstraint(
            model_name='subscriptiontopic',
            constraint=models.UniqueConstraint(models.F('category'), condition=models.Q(('category', 'NEWSLETTER'), ('is_active', True), ('is_default', True)), name='sub_topic_one_default_newsletter', violation_error_message='Only one active newsletter topic can be the default.'),
        ),
        migrations.AddConstraint(
            model_name='usersubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'topic'), name='user_sub_unique_user_topic'),
        ),
        migrations.AddConstraint(
            model_name='usersubscription',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('topic'), condition=models.Q(('user__isnull', True)), name='user_sub_unique_guest_email_topic'),
        ),
        migrations.AddConstraint(
            model_name='usersubscription',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), models.Q(('email', ''), _negated=True), _connector='OR'), name='user_sub_has_recipient'),
        ),
    ]
