# Generated by Django 6.0.8 on 2026-10-01 00:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0013_field_verbose_names'),
        ('loyalty', '0006_field_verbose_names'),
        ('region', '0011_field_verbose_names'),
        ('user', '0030_newsletter_guest_subscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontopic',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='country.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='loyalty_tier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='loyalty.loyaltytier', verbose_name='Loyalty Tier'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='region.region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_addresses', to='country.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_addresses', to='region.region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='userdataexport',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
