# Generated by Django 4.2 on 2023-04-13 23:50
import uuid

import django.utils.timezone
from django.db import migrations
from django.db import models

import tip.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(db_index=True, editable=False, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField(max_length=1000)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("success", "SUCCESS"),
                            ("info", "INFO"),
                            ("error", "ERROR"),
                            ("warning", "WARNING"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "icon",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="uploads/tip/",
                        validators=[tip.validators.validate_file_extension],
                    ),
                ),
                ("url", models.CharField(max_length=200)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
