# Generated by Django 5.0.6 on 2024-06-19 08:07
from django.db import migrations

import core.fields.image
import tip.validators


class Migration(migrations.Migration):
    dependencies = [
        ("tip", "0004_alter_tip_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tip",
            name="icon",
            field=core.fields.image.ImageAndSvgField(
                blank=True,
                null=True,
                upload_to="uploads/tip/",
                validators=[tip.validators.validate_file_extension],
                verbose_name="Icon",
            ),
        ),
    ]
