# Generated by Django 5.2.1 on 2025-05-14 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tip', '0006_alter_tip_sort_order'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tip',
            new_name='tip_created_at_ix',
            old_name='tip_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='tip',
            new_name='tip_updated_at_ix',
            old_name='tip_updated_at_idx',
        ),
        migrations.RenameIndex(
            model_name='tip',
            new_name='tip_sort_order_ix',
            old_name='tip_sort_order_idx',
        ),
    ]
