# Generated by Django 6.0.4 on 2026-04-29 10:11

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('code', models.SlugField(help_text="Stable identifier matching the registered carrier adapter (e.g. 'acs', 'boxnow').", max_length=32, unique=True, verbose_name='Code')),
                ('name', models.CharField(help_text="Display name shown to customers (e.g. 'ACS Courier').", max_length=64, verbose_name='Name')),
                ('is_active', models.BooleanField(default=False, help_text='Master switch — when False the provider is hidden from checkout regardless of capability flags.', verbose_name='Is Active')),
                ('supports_home_delivery', models.BooleanField(default=False, verbose_name='Supports Home Delivery')),
                ('supports_pickup_point', models.BooleanField(default=False, verbose_name='Supports Pickup Point')),
                ('live_mode', models.BooleanField(default=False, help_text="False = sandbox / test credentials. Used by the admin UI to warn operators that vouchers won't actually ship.", verbose_name='Live Mode')),
                ('priority', models.PositiveSmallIntegerField(default=0, help_text='Sort order in checkout — lower numbers appear first.', verbose_name='Priority')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Provider-specific configuration (supported countries, feature flags, branding hints).', verbose_name='Metadata')),
            ],
            options={
                'verbose_name': 'Shipping Provider',
                'verbose_name_plural': 'Shipping Providers',
                'ordering': ['priority', 'name'],
                'indexes': [django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='shippingprovider_created_at_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['updated_at'], name='shippingprovider_updated_at_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['code'], name='shipping_provider_code_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['is_active', 'priority'], name='shipping_provider_active_pri_ix')],
            },
        ),
    ]
