# Generated by Django 6.0.5 on 2026-05-22 09:07

import core.fields.image
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0006_drop_legacy_boxnow_enabled_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingprovider',
            name='logo',
            field=core.fields.image.ImageAndSvgField(blank=True, help_text='Brand logo shown on the checkout shipping picker and the order summary. PNG/JPG/SVG supported. Falls back to a shipped default in the storefront when blank, so a fresh deploy without uploaded assets still renders.', null=True, upload_to='uploads/shipping/', verbose_name='Logo'),
        ),
    ]
