# Generated by Django 6.0.5 on 2026-05-22 13:21

import core.fields.image
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0007_shippingprovider_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingprovider',
            name='logo_pickup_point',
            field=core.fields.image.ImageAndSvgField(blank=True, help_text="Optional pickup-point-specific logo (e.g. a locker illustration distinct from the carrier's home-delivery brand mark). When set, the storefront's ``/api/v1/shipping/options`` endpoint surfaces it on the pickup_point row's ``logoUrl`` so the locker card looks different from the home-delivery card for the same carrier. Falls back to ``logo`` when blank.", null=True, upload_to='uploads/shipping/', verbose_name='Pickup-point logo'),
        ),
        migrations.AlterField(
            model_name='shippingprovider',
            name='logo',
            field=core.fields.image.ImageAndSvgField(blank=True, help_text='Primary brand logo shown on the checkout shipping picker and the order summary — used for home-delivery rows and as the fallback for pickup-point rows when ``logo_pickup_point`` is empty. PNG/JPG/SVG. Falls back to a shipped default in the storefront when blank, so a fresh deploy without uploaded assets still renders.', null=True, upload_to='uploads/shipping/', verbose_name='Logo'),
        ),
    ]
