# Generated by Django 6.0.8 on 2026-09-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0011_convert_legacy_pricing_to_rates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingprovider',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Provider-specific configuration (feature flags, branding hints, locker/map chrome). Which countries this provider ships to is a ``ShippingRate`` question, not a metadata key — see the Rates inline below.', verbose_name='Metadata'),
        ),
    ]
