# Generated by Django 6.0.8 on 2026-09-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shipping", "0012_alter_shippingprovider_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalshippingrate",
            name="kind",
            field=models.CharField(
                choices=[
                    ("home_delivery", "Home delivery"),
                    ("pickup_point", "Pickup point / locker"),
                ],
                max_length=32,
                verbose_name="Shipping Kind",
            ),
        ),
        migrations.AlterField(
            model_name="shippingrate",
            name="kind",
            field=models.CharField(
                choices=[
                    ("home_delivery", "Home delivery"),
                    ("pickup_point", "Pickup point / locker"),
                ],
                max_length=32,
                verbose_name="Shipping Kind",
            ),
        ),
    ]
