# Generated by Django 6.0.8 on 2026-10-01 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0013_field_verbose_names'),
        ('shipping', '0015_drop_map_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalshippingrate',
            name='country',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='country.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='historicalshippingrate',
            name='provider',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shipping.shippingprovider', verbose_name='Shipping Provider'),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='country.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='shipping.shippingprovider', verbose_name='Shipping Provider'),
        ),
    ]
