# Generated by Django 6.0.8 on 2026-10-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0016_field_verbose_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshippingrate',
            name='delivery_days_max',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text="Slowest delivery, in business days after dispatch. The order's ``estimated_delivery`` date is dispatch plus this many business days. Blank with the minimum also blank.", null=True, verbose_name='Delivery Days (max)'),
        ),
        migrations.AddField(
            model_name='historicalshippingrate',
            name='delivery_days_min',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='Fastest delivery, in business days after dispatch. Blank means no estimate is advertised for this combination; set both bounds (equal for a fixed promise).', null=True, verbose_name='Delivery Days (min)'),
        ),
        migrations.AddField(
            model_name='shippingrate',
            name='delivery_days_max',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text="Slowest delivery, in business days after dispatch. The order's ``estimated_delivery`` date is dispatch plus this many business days. Blank with the minimum also blank.", null=True, verbose_name='Delivery Days (max)'),
        ),
        migrations.AddField(
            model_name='shippingrate',
            name='delivery_days_min',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='Fastest delivery, in business days after dispatch. Blank means no estimate is advertised for this combination; set both bounds (equal for a fixed promise).', null=True, verbose_name='Delivery Days (min)'),
        ),
    ]
