# Generated by Django 6.0.4 on 2026-05-01 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0038_drop_shipping_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaCapiEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('event_name', models.CharField(max_length=64, verbose_name='Event name')),
                ('event_id', models.CharField(help_text='UUID shared between the browser pixel and the server event so Meta can dedup the pair. Unique constraint is the second line of defence against double dispatch — the Celery task already short-circuits if a row with this event_id is already SENT.', max_length=128, unique=True, verbose_name='Event ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16, verbose_name='Status')),
                ('fbtrace_id', models.CharField(blank=True, default='', help_text="Meta's request trace ID. Quote this when filing a support ticket so they can find the request server-side.", max_length=128, verbose_name='Meta fbtrace_id')),
                ('events_received', models.PositiveSmallIntegerField(default=0, help_text='Number of events Meta acknowledged. Should be 1; values >1 indicate batched sends, 0 indicates a validation reject we logged but Meta dropped.', verbose_name='Events received')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Error message')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Sanitised request body (PII fields are hashed by the facebook_business SDK before serialisation). Stored for replay during incident debugging.', verbose_name='Payload')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meta_capi_events', to='order.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meta_capi_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meta CAPI Event',
                'verbose_name_plural': 'Meta CAPI Events',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['event_name', '-created_at'], name='meta_capi_m_event_n_def794_idx'), models.Index(fields=['status', '-created_at'], name='meta_capi_m_status_6db08d_idx')],
            },
        ),
    ]
