# Generated by Django 6.0.8 on 2026-10-01 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_capi', '0002_created_at_index'),
        ('order', '0062_field_verbose_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='metacapieventlog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meta_capi_events', to='order.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='metacapieventlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meta_capi_events', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
