# Generated by Django 4.2.4 on 2023-09-01 09:21
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="document_type",
            field=models.CharField(
                choices=[("RECEIPT", "Receipt"), ("INVOICE", "Invoice")],
                default="RECEIPT",
                max_length=100,
                verbose_name="Document Type",
            ),
        ),
    ]
