# Generated by Django 4.2.4 on 2023-08-29 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("country", "0001_initial"),
        ("region", "0001_initial"),
        ("order", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_country",
                to="country.country",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_region",
                to="region.region",
            ),
        ),
    ]
