# Generated by Django 4.2.1 on 2023-05-21 15:30
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="document_type",
            field=models.CharField(
                choices=[("receipt", "Receipt"), ("invoice", "Invoice")],
                default="receipt",
                max_length=10,
            ),
        ),
    ]
