# Generated by Django 4.2.8 on 2023-12-05 21:24
from decimal import Decimal

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="paid_amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=11,
                null=True,
                verbose_name="Paid Amount",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_price",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=11,
                verbose_name="Shipping Price",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2, max_digits=11, verbose_name="Price"
            ),
        ),
    ]
