# Generated by Django 5.2 on 2025-05-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_orderhistory_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='user_agent',
            field=models.TextField(blank=True, default='', help_text='User agent of the browser/client that made the change.', verbose_name='User Agent'),
            preserve_default=False,
        ),
    ]
