# Generated by Django 6.0.3 on 2026-04-05 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_alter_order_is_deleted'),
        ('product', '0029_alter_historicalproduct_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='product.product'),
        ),
    ]
