# Generated by Django 6.0.4 on 2026-04-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the most recent reminder email.', null=True, verbose_name='Last Reminder Sent At'),
        ),
        migrations.AddField(
            model_name='order',
            name='reminder_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of pending-order reminder emails sent.', verbose_name='Reminder Count'),
        ),
    ]
