# Generated by Django 6.0.4 on 2026-04-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0027_add_email_reminder_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreservation',
            name='abandonment_notified',
            field=models.BooleanField(default=False, help_text='True if the customer has been emailed about this abandoned reservation', verbose_name='Abandonment Notified'),
        ),
    ]
