# Generated by Django 6.0.4 on 2026-04-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0028_stockreservation_abandonment_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='language_code',
            field=models.CharField(default='el', help_text='Language captured at order creation, used when rendering order emails.', max_length=10, verbose_name='Language'),
        ),
    ]
