# Generated by Django 6.0.4 on 2026-04-20 12:01

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0006_remove_country_country_cou_alpha_2_398383_idx_and_more'),
        ('order', '0029_add_language_code'),
        ('pay_way', '0012_alter_paywaytranslation_name'),
        ('region', '0006_rename_region_created_at_idx_region_created_at_ix_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['user', '-created_at'], name='order_user_created_ix'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['payment_status', '-created_at'], name='order_paystatus_created_ix'),
        ),
    ]
