# Generated by Django 6.0.4 on 2026-04-21 17:55

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import djmoney.models.fields
import djmoney.money
import order.models.invoice
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_add_order_composite_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True, verbose_name='Year')),
                ('next_number', models.PositiveIntegerField(default=1, verbose_name='Next Number')),
            ],
            options={
                'verbose_name': 'Invoice Counter',
                'verbose_name_plural': 'Invoice Counters',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invoice_number', models.CharField(help_text='Sequential identifier in the form ``INV-{YEAR}-{NNNNNN}``. Gaps are not allowed by Greek tax law.', max_length=32, unique=True, verbose_name='Invoice Number')),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate, help_text='Fiscal date of issue. Immutable once the invoice is rendered — used for sequential numbering and reporting.', verbose_name='Issue Date')),
                ('document_file', models.FileField(blank=True, help_text='The rendered PDF. Stored in private storage — access only via signed URL from the download endpoint.', null=True, storage=order.models.invoice._private_invoice_storage, upload_to=order.models.invoice._invoice_upload_to, verbose_name='Document File')),
                ('subtotal_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3)),
                ('subtotal', djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'EUR'), max_digits=11, verbose_name='Subtotal (excl. VAT)')),
                ('total_vat_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3)),
                ('total_vat', djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'EUR'), max_digits=11, verbose_name='Total VAT')),
                ('total_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3)),
                ('total', djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'EUR'), max_digits=11, verbose_name='Total (incl. VAT)')),
                ('vat_breakdown', models.JSONField(default=list, help_text='Cached list of ``{rate, subtotal, vat, gross}`` rows — frozen at issue time so re-rendering the invoice always yields the same VAT table even if product rates change.', verbose_name='VAT Breakdown')),
                ('seller_snapshot', models.JSONField(default=dict, help_text='Seller name / VAT ID / address captured at issue time.', verbose_name='Seller Snapshot')),
                ('buyer_snapshot', models.JSONField(default=dict, help_text='Buyer name / email / billing address captured at issue time.', verbose_name='Buyer Snapshot')),
                ('currency', models.CharField(default='EUR', max_length=10, verbose_name='Currency')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='order.order')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-issue_date', '-invoice_number'],
                'indexes': [django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='invoice_created_at_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['updated_at'], name='invoice_updated_at_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['issue_date'], name='invoice_issue_date_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['invoice_number'], name='invoice_invoice_number_ix')],
            },
        ),
    ]
