# Generated by Django 6.0.4 on 2026-04-22 12:23

import django.contrib.postgres.indexes
import order.models.invoice
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_invoicecounter_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='mydata_aa',
            field=models.PositiveIntegerField(blank=True, help_text='AADE ``aa`` field — strictly-increasing integer within ``(series, year)``. Must be gapless per Greek tax law.', null=True, verbose_name='myDATA Serial Number (aa)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='mydata_authentication_code',
            field=models.CharField(blank=True, default='', help_text='Short hash AADE generates alongside the MARK; part of the ``qr_url`` query string. Populated only via licensed provider channels (kept for forward compatibility).', max_length=128, verbose_name='myDATA Authentication Code'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='mydata_cancellation_mark',
            field=models.BigIntegerField(blank=True, help_text='9-series MARK returned by a successful ``CancelInvoice`` call — proves the cancellation registered.', null=True, verbose_name='myDATA Cancellation MARK'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='mydata_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp AADE assigned the MARK.', null=True, verbose_name='myDATA Confirmed At'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='mydata_error_code',
            field=models.CharField(blank=True, default='', help_text='Numeric AADE ``errorCode`` from the most recent failed submission (e.g. 101 XML syntax, 102 inactive VAT, 216/217 VAT category). Empty when last attempt succeeded.', max_length=10, verbose_name='myDATA Error Code'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='mydata_error_message',
            field=models.TextField(blank=True, default='', help_text='Human-readable message that accompanied the error code.', verbose_name='myDATA Error Message'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='mydata_invoice_type',
            field=models.CharField(blank=True, default='', help_text='AADE invoiceType code — e.g. 11.1 (B2C retail), 1.1 (B2B sales invoice), 5.1 (linked credit note).', max_length=10, verbose_name='myDATA Invoice Type'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='mydata_mark',
            field=models.BigIntegerField(blank=True, help_text='15-digit registration number assigned by AADE. This is the legally-authoritative identifier — printed on the PDF.', null=True, unique=True, verbose_name='myDATA MARK'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='mydata_qr_url',
            field=models.URLField(blank=True, default='', help_text='AADE-returned URL for the PDF QR code. NEVER synthesise — AADE changes the query-string parameters between schema versions; always store the string they return verbatim.', max_length=500, verbose_name='myDATA QR URL'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='mydata_series',
            field=models.CharField(blank=True, default='', help_text="AADE ``series`` field — the alphanumeric part of the document's unique identifier within the issuer's register.", max_length=50, verbose_name='myDATA Series'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='mydata_status',
            field=models.CharField(choices=[('NOT_SENT', 'Not sent'), ('PENDING', 'Pending submission'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed (MARK assigned)'), ('REJECTED', 'Rejected'), ('CANCELED', 'Canceled in myDATA')], default='NOT_SENT', help_text="Lifecycle state of the invoice's AADE myDATA submission. NOT_SENT is the resting state when the myDATA integration is disabled or the invoice predates it.", max_length=20, verbose_name='myDATA Status'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='mydata_submitted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the first transmission attempt — preserved across retries so reporting reflects the original send time.', null=True, verbose_name='myDATA Submitted At'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='mydata_uid',
            field=models.CharField(blank=True, default='', help_text="Deterministic SHA-1 fingerprint of (issuer VAT | year | branch | invoiceType | series | aa). Sent as the request's ``uid`` so retries dedupe against AADE error 228.", max_length=64, verbose_name='myDATA UID'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='document_file',
            field=models.FileField(blank=True, help_text='The rendered PDF. Stored in private storage — customer access goes through ``OrderViewSet.invoice_download`` (streamed through Django auth); direct storage URLs are signed via ``PrivateMediaStorage`` as a defence in depth.', null=True, storage=order.models.invoice._private_invoice_storage, upload_to=order.models.invoice._invoice_upload_to, verbose_name='Document File'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['mydata_status'], name='invoice_mydata_status_ix'),
        ),
    ]
