# Generated by Django 6.0.4 on 2026-04-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_invoice_mydata_aa_invoice_mydata_authentication_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_country',
            field=models.CharField(blank=True, default='', help_text='ISO 3166-1 alpha-2 country code of the buyer for tax purposes. Pairs with ``billing_vat_id``; determines which AADE invoice type (1.1 domestic, 1.2 intra-EU, 1.3 third-country) applies.', max_length=2, verbose_name='Billing Country'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_vat_id',
            field=models.CharField(blank=True, default='', help_text="Buyer's tax number (ΑΦΜ) — required when issuing an invoice (vs. a retail receipt). 9 digits for Greek ΑΦΜ, no ``EL`` / ``GR`` prefix.", max_length=12, verbose_name='Billing VAT ID'),
        ),
    ]
