# Generated by Django 6.0.4 on 2026-04-24 17:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_order_billing_country_order_billing_vat_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='user_agent',
            field=models.TextField(blank=True, help_text='User agent of the browser/client that made the change.', validators=[django.core.validators.MaxLengthValidator(512)], verbose_name='User Agent'),
        ),
    ]
