# Generated by Django 6.0.4 on 2026-04-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_order_user_set_null_orderhistory_user_agent_maxlen'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('home_delivery', 'Home delivery'), ('box_now_locker', 'BOX NOW Locker')], db_index=True, default='home_delivery', max_length=32, verbose_name='Shipping Method'),
        ),
    ]
