# Generated by Django 6.0.4 on 2026-04-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0036_initial_provider_registry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('home_delivery', 'Home delivery'), ('box_now_locker', 'BOX NOW Locker'), ('acs_smartpoint', 'ACS Smartpoint')], db_index=True, default='home_delivery', help_text='Legacy enum kept for backwards compatibility. New code reads the (shipping_provider, shipping_kind) pair instead — both fields are dual-written by OrderService until Phase 3 of the shipping abstraction migration.', max_length=32, verbose_name='Shipping Method'),
        ),
    ]
