# Generated by Django 6.0.4 on 2026-04-30 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0037_acs_smartpoint_shipping_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_method',
        ),
    ]
