# Generated by Django 6.0.4 on 2026-05-02 18:05

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0039_add_status_created_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="VivaWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created At"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Updated At"
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        help_text="Viva ``EventData.TransactionId`` — idempotency key",
                        max_length=64,
                        verbose_name="Transaction ID",
                    ),
                ),
                (
                    "event_type_id",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1796, "Transaction Payment Created"),
                            (1797, "Transaction Reversal Created"),
                            (1798, "Transaction Failed"),
                        ],
                        help_text="Viva ``EventTypeId`` — 1796/1797/1798",
                        verbose_name="Event Type ID",
                    ),
                ),
                (
                    "order_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Viva ``EventData.OrderCode`` — kept for audit",
                        max_length=64,
                        verbose_name="Order Code",
                    ),
                ),
                (
                    "status_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Viva ``EventData.StatusId`` ('F' = Finished)",
                        max_length=4,
                        verbose_name="Status ID",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("processed", "Processed"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                        ],
                        default="processed",
                        max_length=16,
                        verbose_name="Outcome",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Received At",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="viva_webhook_events",
                        to="order.order",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Viva Webhook Event",
                "verbose_name_plural": "Viva Webhook Events",
                "ordering": ["-received_at"],
                "indexes": [
                    django.contrib.postgres.indexes.BTreeIndex(
                        fields=["created_at"],
                        name="vivawebhookevent_created_at_ix",
                    ),
                    django.contrib.postgres.indexes.BTreeIndex(
                        fields=["updated_at"],
                        name="vivawebhookevent_updated_at_ix",
                    ),
                    django.contrib.postgres.indexes.BTreeIndex(
                        fields=["received_at"], name="viva_webhook_received_ix"
                    ),
                    django.contrib.postgres.indexes.BTreeIndex(
                        fields=["order"], name="viva_webhook_order_ix"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("transaction_id", "event_type_id"),
                        name="viva_webhook_event_unique",
                    )
                ],
            },
        ),
    ]
