# Generated by Django 6.0.5 on 2026-05-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0040_add_viva_webhook_event'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderhistorytranslation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='orderitemhistorytranslation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='orderhistorytranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='order_orderhistory_translation_uniq_lang'),
        ),
        migrations.AddConstraint(
            model_name='orderitemhistorytranslation',
            constraint=models.UniqueConstraint(fields=('language_code', 'master'), name='order_orderitemhistory_translation_uniq_lang'),
        ),
    ]
