# Generated by Django 6.0.5 on 2026-05-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0041_alter_orderhistorytranslation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='sort_order',
            field=models.IntegerField(null=True, verbose_name='Sort Order'),
        ),
    ]
