# Generated by Django 6.0.7 on 2026-07-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0042_alter_orderitem_sort_order'),
        ('product', '0039_add_product_brand'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='order_item_quantity_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('refunded_quantity__gte', 0), ('refunded_quantity__lte', models.F('quantity'))), name='order_item_refunded_within_quantity'),
        ),
    ]
