# Generated by Django 6.0.8 on 2026-08-19 10:58

import order.models.invoice
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0043_orderitem_order_item_quantity_gte_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='document_file',
            field=models.FileField(blank=True, help_text='The rendered PDF. Stored in per-tenant private storage — customer access goes through ``OrderViewSet.invoice_download`` (streamed through Django auth); the private tree lives outside every public web root as a defence in depth.', null=True, storage=order.models.invoice._private_invoice_storage, upload_to=order.models.invoice._invoice_upload_to, verbose_name='Document File'),
        ),
    ]
