# Generated by Django 6.0.8 on 2026-08-19 19:38

import djmoney.models.fields
import djmoney.money
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0044_alter_invoice_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='loyalty_discount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'EUR'), help_text='Amount deducted from the order total in exchange for loyalty points. Deducted by calculate_order_total_amount().', max_digits=11, verbose_name='Loyalty Discount'),
        ),
        migrations.AddField(
            model_name='order',
            name='loyalty_discount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3),
        ),
    ]
