# Generated by Django 6.0.8 on 2026-08-22 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0045_add_loyalty_discount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklog',
            name='performed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who performed the operation (null for system operations)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_operations', to=settings.AUTH_USER_MODEL),
        ),
    ]
