# Generated by Django 6.0.8 on 2026-08-25 07:33

import djmoney.models.fields
import djmoney.money
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0046_alter_stocklog_performed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'EUR'), help_text="Total discount granted by promotions/coupons, snapshotted at order creation. Breakdown lives in metadata['promotions'] + PromotionRedemption rows. Deducted by calculate_order_total_amount().", max_digits=11, verbose_name='Promotion Discount'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_card_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=djmoney.money.Money(0, 'EUR'), help_text='Portion of the order settled by gift-card balance. A payment, not a discount — it never reduces the taxable order value, only what the payment provider charges.', max_digits=11, verbose_name='Gift Card Amount'),
        ),
        migrations.AddField(
            model_name='order',
            name='gift_card_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3),
        ),
    ]
