# Generated by Django 6.0.8 on 2026-08-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0047_order_discount_amount_order_discount_amount_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_activity',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Billing Business Activity'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Billing City'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_company_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Billing Company Name'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_street',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Billing Street'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_street_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Billing Street Number'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_tax_office',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Billing Tax Office (ΔΟΥ)'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_zipcode',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Billing Zipcode'),
        ),
    ]
