# Generated by Django 6.0.8 on 2026-09-03 04:50

import djmoney.models.fields
import djmoney.money
from decimal import Decimal
from django.db import migrations

# django-money builds the companion ``*_currency`` column itself and has
# no ``db_default`` support, so Django emits DROP DEFAULT for those three
# right after ADD COLUMN — while the amount columns keep theirs from the
# field's ``db_default``. Migrations run BEFORE the new image rolls (Argo
# PreSync), so an old pod inserting an invoice would hit a not-null
# violation on the currency columns. Put the defaults back.
#
# This is invisible to migration state: a future AlterField on these
# MoneyFields will drop them again.
_CURRENCY_DEFAULTS = """
ALTER TABLE "order_invoice" ALTER COLUMN "shipping_currency" SET DEFAULT 'EUR';
ALTER TABLE "order_invoice" ALTER COLUMN "payment_fee_currency" SET DEFAULT 'EUR';
ALTER TABLE "order_invoice" ALTER COLUMN "discount_currency" SET DEFAULT 'EUR';
"""

_CURRENCY_DEFAULTS_REVERSE = """
ALTER TABLE "order_invoice" ALTER COLUMN "shipping_currency" DROP DEFAULT;
ALTER TABLE "order_invoice" ALTER COLUMN "payment_fee_currency" DROP DEFAULT;
ALTER TABLE "order_invoice" ALTER COLUMN "discount_currency" DROP DEFAULT;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0048_order_billing_activity_order_billing_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=djmoney.models.fields.MoneyField(db_default=Decimal('0'), decimal_places=2, default=djmoney.money.Money(0, 'EUR'), help_text='Informational only — the line values are already net of the allocation, so this never enters the total arithmetic.', max_digits=11, verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_fee',
            field=djmoney.models.fields.MoneyField(db_default=Decimal('0'), decimal_places=2, default=djmoney.money.Money(0, 'EUR'), max_digits=11, verbose_name='Payment Method Fee'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_fee_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipping',
            field=djmoney.models.fields.MoneyField(db_default=Decimal('0'), decimal_places=2, default=djmoney.money.Money(0, 'EUR'), max_digits=11, verbose_name='Shipping'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipping_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3),
        ),
        migrations.RunSQL(_CURRENCY_DEFAULTS, _CURRENCY_DEFAULTS_REVERSE),
    ]
