# Generated by Django 6.0.8 on 2026-09-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0055_order_pay_way_key_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='recommendation_impression_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='Recommendation impression'),
        ),
    ]
