# Generated by Django 6.0.8 on 2026-09-27 11:59

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0058_settle_returned_unpaid_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAttribution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='attribution', serialize=False, to='order.order', verbose_name='Order')),
                ('source_type', models.CharField(choices=[('direct', 'Direct'), ('campaign', 'Campaign'), ('paid', 'Paid'), ('social', 'Social'), ('search', 'Search'), ('referral', 'Referral'), ('agent', 'AI agent')], default='direct', max_length=16, verbose_name='Source type')),
                ('source', models.CharField(blank=True, default='', help_text="A known channel's key (e.g. ``instagram``), the referring host, or the raw ``utm_source``. Empty for a direct visit.", max_length=100, verbose_name='Order source')),
                ('medium', models.CharField(blank=True, default='', max_length=100, verbose_name='Traffic medium')),
                ('campaign', models.CharField(blank=True, default='', max_length=200, verbose_name='Campaign name')),
                ('referrer_host', models.CharField(blank=True, default='', max_length=255, verbose_name='Referrer host')),
                ('landing_path', models.CharField(blank=True, default='', max_length=500, verbose_name='Landing page')),
            ],
            options={
                'verbose_name': 'Order attribution',
                'verbose_name_plural': 'Order attributions',
                'indexes': [django.contrib.postgres.indexes.BTreeIndex(fields=['created_at'], name='orderattribution_created_at_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['updated_at'], name='orderattribution_updated_at_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['source_type'], name='order_attr_type_ix'), django.contrib.postgres.indexes.BTreeIndex(fields=['source'], name='order_attr_source_ix')],
            },
        ),
    ]
