# Generated by Django 6.0.8 on 2026-10-01 00:28

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0013_field_verbose_names'),
        ('order', '0061_order_drop_stock_reservation_ids_column'),
        ('pay_way', '0028_field_verbose_names'),
        ('product', '0048_field_verbose_names'),
        ('region', '0011_field_verbose_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='order.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='country.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted'),
        ),
        migrations.AlterField(
            model_name='order',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_way',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='pay_way.payway', verbose_name='Payment Method'),
        ),
        migrations.AlterField(
            model_name='order',
            name='private_metadata',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, verbose_name='Private Metadata'),
        ),
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='region.region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='order.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who made the change, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_changes', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='product.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='orderitemhistory',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='order.orderitem', verbose_name='Order Item'),
        ),
        migrations.AlterField(
            model_name='orderitemhistory',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who made the change, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_item_changes', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='orderitemhistory',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Order associated with this stock operation (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_logs', to='order.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='performed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who performed the operation (null for system operations)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_operations', to=settings.AUTH_USER_MODEL, verbose_name='Performed By'),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='product',
            field=models.ForeignKey(help_text='Product whose stock was modified', on_delete=django.db.models.deletion.CASCADE, related_name='stock_logs', to='product.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Order created from this reservation (set when consumed)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_reservations', to='order.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='product',
            field=models.ForeignKey(help_text='Product being reserved', on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to='product.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='reserved_by',
            field=models.ForeignKey(blank=True, help_text='User who made the reservation (null for guest users)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_reservations', to=settings.AUTH_USER_MODEL, verbose_name='Reserved By'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Payment Gateway'),
        ),
    ]
