# Generated by Django 6.0.8 on 2026-10-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0062_field_verbose_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_delivery',
            field=models.DateField(blank=True, help_text='Latest expected delivery date, fixed when the order was placed from the chosen shipping rate, the dispatch cutoff and business days. Null when the rate advertises no estimate. A promise made at checkout: later rate edits do not move it.', null=True, verbose_name='Estimated Delivery'),
        ),
    ]
